/**
 * generate_b1.cjs
 * Generates 22 × 20 = 440 B1-level words (IDs 886-1325),
 * validates no duplicates against existing words.json, then merges.
 */

const fs = require('fs');
const path = require('path');

const WORDS_PATH = path.join(__dirname, '..', 'src', 'data', 'words.json');
const existing = JSON.parse(fs.readFileSync(WORDS_PATH, 'utf8'));
const existingEns = new Set(existing.map(w => w.en));

let id = 886;

function w(topic, en, tr, type, exampleEn, exampleTr) {
  return { id: id++, topic, en, tr, type, exampleEn, exampleTr };
}

const T = (name) => name + ' (B1)';

const b1 = [

  // ── Selamlaşma ve Tanışma (B1) ─────────────────────────────────────────
  w(T('Selamlaşma ve Tanışma'), 'colleague',      'iş arkadaşı',      'isim',  'My colleague helped me finish the report.',           'İş arkadaşım raporu bitirmeme yardım etti.'),
  w(T('Selamlaşma ve Tanışma'), 'acquaintance',   'tanıdık',          'isim',  'She is an acquaintance, not a close friend.',         'O bir tanıdık, yakın arkadaş değil.'),
  w(T('Selamlaşma ve Tanışma'), 'eloquent',        'belagatlı',        'sıfat', 'She gave an eloquent speech at the ceremony.',        'Törende belagatlı bir konuşma yaptı.'),
  w(T('Selamlaşma ve Tanışma'), 'candid',          'açık sözlü',       'sıfat', 'He was candid about his feelings.',                   'Duygularını açık sözlülükle paylaştı.'),
  w(T('Selamlaşma ve Tanışma'), 'reputation',     'itibar',           'isim',  'She has a great reputation in her field.',            'Kendi alanında harika bir itibarı var.'),
  w(T('Selamlaşma ve Tanışma'), 'compliment',     'iltifat',          'isim',  'He gave her a sincere compliment.',                   'Ona içten bir iltifat etti.'),
  w(T('Selamlaşma ve Tanışma'), 'farewell',       'veda',             'isim',  'They said their farewells at the airport.',           'Havalimanında vedalaştılar.'),
  w(T('Selamlaşma ve Tanışma'), 'handshake',      'el sıkışma',       'isim',  'A firm handshake shows confidence.',                  'Sıkı bir el sıkışma güven gösterir.'),
  w(T('Selamlaşma ve Tanışma'), 'impression',     'izlenim',          'isim',  'She made a great first impression.',                  'Harika bir ilk izlenim bıraktı.'),
  w(T('Selamlaşma ve Tanışma'), 'networking',     'ağ kurma',         'isim',  'Networking is important for career growth.',          'Ağ kurma kariyer gelişimi için önemlidir.'),
  w(T('Selamlaşma ve Tanışma'), 'acknowledge',    'kabul etmek',      'fiil',  'He acknowledged her contribution to the project.',    'Projeye olan katkısını kabul etti.'),
  w(T('Selamlaşma ve Tanışma'), 'approachable',   'ulaşılabilir',     'sıfat', 'The manager is very approachable.',                   'Müdür çok ulaşılabilir biri.'),
  w(T('Selamlaşma ve Tanışma'), 'dialogue',        'diyalog',          'isim',  'Open dialogue helps resolve misunderstandings.',      'Açık diyalog yanlış anlamaları çözmeye yardımcı olur.'),
  w(T('Selamlaşma ve Tanışma'), 'mutual',         'karşılıklı',       'sıfat', 'We have many mutual friends.',                        'Pek çok ortak arkadaşımız var.'),
  w(T('Selamlaşma ve Tanışma'), 'sincere',        'samimi',           'sıfat', 'Her apology was sincere.',                            'Özrü samimiydi.'),
  w(T('Selamlaşma ve Tanışma'), 'bond',           'bağ',              'isim',  'They formed a strong bond over the years.',           'Yıllar içinde güçlü bir bağ kurdular.'),
  w(T('Selamlaşma ve Tanışma'), 'memorable',      'unutulmaz',        'sıfat', 'That was a memorable evening.',                       'O unutulmaz bir akşamdı.'),
  w(T('Selamlaşma ve Tanışma'), 'reunion',        'yeniden buluşma',  'isim',  'The class reunion was held last weekend.',            'Sınıf yeniden buluşması geçen hafta sonu yapıldı.'),
  w(T('Selamlaşma ve Tanışma'), 'trustworthy',    'güvenilir',        'sıfat', 'He is a trustworthy person.',                         'Güvenilir bir insandır.'),
  w(T('Selamlaşma ve Tanışma'), 'community',      'topluluk',         'isim',  'She is very active in her community.',                'Topluluğunda çok aktif.'),

  // ── Sayılar (B1) ──────────────────────────────────────────────────────
  w(T('Sayılar'), 'proportion',    'oran',          'isim',  'A large proportion of students passed.',         'Öğrencilerin büyük bir oranı geçti.'),
  w(T('Sayılar'), 'decimal',       'ondalık',       'isim',  'Write the answer as a decimal number.',          'Cevabı ondalık sayı olarak yaz.'),
  w(T('Sayılar'), 'percentage',    'yüzde',         'isim',  'What percentage of students passed the exam?',   'Öğrencilerin yüzde kaçı sınavı geçti?'),
  w(T('Sayılar'), 'estimate',      'tahmin etmek',  'fiil',  'Can you estimate the total cost?',              'Toplam maliyeti tahmin edebilir misin?'),
  w(T('Sayılar'), 'precise',       'kesin',         'sıfat', 'Give me the precise measurement.',               'Bana kesin ölçüyü ver.'),
  w(T('Sayılar'), 'approximate',   'yaklaşık',      'sıfat', 'The approximate distance is 50 km.',            'Yaklaşık mesafe 50 km\'dir.'),
  w(T('Sayılar'), 'equation',      'denklem',       'isim',  'Solve this equation for x.',                    'Bu denklemi x için çöz.'),
  w(T('Sayılar'), 'calculation',   'hesaplama',     'isim',  'Double-check your calculation.',                'Hesaplamalarını tekrar kontrol et.'),
  w(T('Sayılar'), 'statistic',     'istatistik',    'isim',  'The statistics show a clear trend.',             'İstatistikler açık bir eğilim gösteriyor.'),
  w(T('Sayılar'), 'formula',       'formül',        'isim',  'Use the correct formula to find the area.',     'Alanı bulmak için doğru formülü kullan.'),
  w(T('Sayılar'), 'ratio',         'oran',          'isim',  'The ratio of boys to girls is 3 to 2.',         'Erkek-kız oranı 3\'e 2\'dir.'),
  w(T('Sayılar'), 'median',        'medyan',        'isim',  'The median score of the class was 70.',          'Sınıfın medyan puanı 70\'ti.'),
  w(T('Sayılar'), 'maximum',       'maksimum',      'isim',  'What is the maximum speed allowed?',            'İzin verilen maksimum hız nedir?'),
  w(T('Sayılar'), 'minimum',       'minimum',       'isim',  'The minimum age to vote is 18.',                'Oy kullanma için asgari yaş 18\'dir.'),
  w(T('Sayılar'), 'exponent',      'üs',            'isim',  '2 to the power of 3 is an exponent example.',   '2\'nin 3. kuvveti bir üs örneğidir.'),
  w(T('Sayılar'), 'denominator',  'payda',         'isim',  'The denominator is the bottom number of a fraction.', 'Payda, kesrin alt sayısıdır.'),
  w(T('Sayılar'), 'subtract',      'çıkarmak',      'fiil',  'Subtract 15 from 100.',                         '100\'den 15 çıkar.'),
  w(T('Sayılar'), 'negative',      'negatif',       'sıfat', 'The temperature is negative today.',            'Bugün sıcaklık negatif.'),
  w(T('Sayılar'), 'sequence',      'dizi',          'isim',  'What is the next number in this sequence?',     'Bu dizideki sonraki sayı nedir?'),
  w(T('Sayılar'), 'infinite',      'sonsuz',        'sıfat', 'The universe is said to be infinite.',         'Evrenin sonsuz olduğu söylenir.'),

  // ── Renkler (B1) ──────────────────────────────────────────────────────
  w(T('Renkler'), 'cerulean',      'gök mavisi',    'isim',  'The sky was a deep cerulean blue.',              'Gökyüzü derin bir gök mavisi rengindeydi.'),
  w(T('Renkler'), 'crimson',       'kızıl',         'isim',  'She wore a crimson dress at the party.',         'Partide kızıl bir elbise giymişti.'),
  w(T('Renkler'), 'ecru',           'krem',          'isim',  'The tablecloth was ecru in color.',              'Masa örtüsü krem rengindeydi.'),
  w(T('Renkler'), 'vermilion',     'parlak kırmızı','isim',  'The artist used vermilion for the flowers.',     'Sanatçı çiçekler için parlak kırmızı kullandı.'),
  w(T('Renkler'), 'cobalt',        'kobalt mavisi', 'isim',  'He wore a cobalt blue shirt.',                   'Kobalt mavisi bir gömlek giymişti.'),
  w(T('Renkler'), 'charcoal',      'kömür grisi',   'isim',  'The charcoal jacket looked elegant.',            'Kömür grisi ceket şık görünüyordu.'),
  w(T('Renkler'), 'copper',        'bakır rengi',   'isim',  'Her hair had a copper tint.',                    'Saçlarında bakır rengi tonlar vardı.'),
  w(T('Renkler'), 'saffron',       'safran sarısı', 'isim',  'She wore a saffron-colored dress.',              'Safran sarısı renkte bir elbise giydi.'),
  w(T('Renkler'), 'lilac',         'leylak rengi',  'isim',  'The lilac blossoms filled the garden.',          'Leylak çiçekleri bahçeyi doldurdu.'),
  w(T('Renkler'), 'slate',         'kurşun grisi',  'isim',  'The roof tiles were slate grey.',                'Çatı kiremitleri kurşun grisi rengindeydi.'),
  w(T('Renkler'), 'amber',         'kehribar',      'isim',  'Her eyes were an amber color.',                  'Gözleri kehribar rengindeydi.'),
  w(T('Renkler'), 'vivid',         'canlı',         'sıfat', 'The painting used vivid colors.',                'Tablo canlı renkler kullandı.'),
  w(T('Renkler'), 'subdued',       'soluk',         'sıfat', 'The room was decorated in subdued shades.',      'Oda soluk tonlarla dekore edildi.'),
  w(T('Renkler'), 'transparent',   'şeffaf',        'sıfat', 'The glass is completely transparent.',          'Cam tamamen şeffaf.'),
  w(T('Renkler'), 'metallic',      'metalik',       'sıfat', 'The car had a metallic finish.',                 'Arabanın metalik bir görünümü vardı.'),
  w(T('Renkler'), 'hue',           'renk tonu',     'isim',  'The painting featured every hue of the rainbow.','Tablo gökkuşağının her renk tonunu içeriyordu.'),
  w(T('Renkler'), 'saturated',     'doygun',        'sıfat', 'Use more saturated colors for the poster.',     'Afiş için daha doygun renkler kullan.'),
  w(T('Renkler'), 'muted',         'soluk',         'sıfat', 'She preferred muted tones in her home.',        'Evinde soluk tonları tercih etti.'),
  w(T('Renkler'), 'contrast',      'kontrast',      'isim',  'There is strong contrast between the two colors.', 'İki renk arasında güçlü bir kontrast var.'),
  w(T('Renkler'), 'blend',         'karışım',       'isim',  'The blend of colors was stunning.',              'Renklerin karışımı çarpıcıydı.'),

  // ── Aile (B1) ─────────────────────────────────────────────────────────
  w(T('Aile'), 'guardian',         'veli',           'isim',  'The guardian signed the school forms.',         'Veli okul formlarını imzaladı.'),
  w(T('Aile'), 'inherit',          'miras almak',    'fiil',  'She will inherit the house from her parents.',  'Evi ailesinden miras alacak.'),
  w(T('Aile'), 'orphan',           'yetim',          'isim',  'The orphan was adopted by a kind family.',     'Yetim, şefkatli bir aile tarafından evlat edinildi.'),
  w(T('Aile'), 'divorce',          'boşanma',        'isim',  'The divorce was difficult for the children.',  'Boşanma çocuklar için zor oldu.'),
  w(T('Aile'), 'custody',          'velayet',        'isim',  'She was awarded full custody of the kids.',    'Çocukların tam velayeti ona verildi.'),
  w(T('Aile'), 'kin',              'akraba',         'isim',  'He has no close kin nearby.',                  'Yakınında yakın akrabası yok.'),
  w(T('Aile'), 'stepparent',       'üvey ebeveyn',   'isim',  'He gets along well with his stepparent.',     'Üvey ebeveynleriyle iyi geçiniyor.'),
  w(T('Aile'), 'upbringing',       'yetiştirilme',   'isim',  'Her upbringing was strict but loving.',        'Yetiştirilme tarzı sıkı ama sevgi doluydu.'),
  w(T('Aile'), 'affection',        'sevgi',          'isim',  'Children need affection to grow well.',        'Çocukların iyi gelişmek için sevgiye ihtiyacı var.'),
  w(T('Aile'), 'breadwinner',      'evin direği',    'isim',  'She became the breadwinner after losing his job.', 'İşini kaybettikten sonra evin direği oldu.'),
  w(T('Aile'), 'ancestor',         'ata',            'isim',  'Our ancestors lived in this village.',         'Atalarımız bu köyde yaşadı.'),
  w(T('Aile'), 'descendant',       'torun',          'isim',  'She is a descendant of a famous explorer.',   'Ünlü bir kaşifin torunudur.'),
  w(T('Aile'), 'estranged',        'yabancılaşmış',  'sıfat', 'He is estranged from his family.',            'Ailesinden yabancılaşmış.',),
  w(T('Aile'), 'nurture',          'beslemek',       'fiil',  'Parents must nurture their children.',         'Ebeveynler çocuklarını beslemelidir.'),
  w(T('Aile'), 'kinship',          'akrabalık',      'isim',  'Kinship ties are strong in this culture.',     'Bu kültürde akrabalık bağları güçlüdür.'),
  w(T('Aile'), 'unity',            'birlik',         'isim',  'Family unity is important in hard times.',     'Zor zamanlarda aile birliği önemlidir.'),
  w(T('Aile'), 'sacrifice',        'fedakarlık',     'isim',  'Parents make many sacrifices for their kids.', 'Ebeveynler çocukları için çok fedakarlık yapar.'),
  w(T('Aile'), 'reconcile',        'barışmak',       'fiil',  'They reconciled after years of conflict.',     'Yıllarca süren anlaşmazlıktan sonra barıştılar.'),
  w(T('Aile'), 'heritage',         'miras',          'isim',  'They are proud of their cultural heritage.',  'Kültürel miraslarıyla gurur duyuyorlar.'),
  w(T('Aile'), 'lineage',          'soy',            'isim',  'She traced her lineage back centuries.',        'Soyunu yüzyıllar öncesine kadar izledi.'),

  // ── Vücut (B1) ────────────────────────────────────────────────────────
  w(T('Vücut'), 'palpitation',     'çarpıntı',      'isim',  'She felt a palpitation after running.',         'Koşu sonrası çarpıntı hissetti.'),
  w(T('Vücut'), 'tissue',          'doku',          'isim',  'The tissue was damaged in the accident.',       'Kaza sırasında doku zarar gördü.'),
  w(T('Vücut'), 'artery',          'atardamar',     'isim',  'The artery carries blood from the heart.',     'Atardamar kalpten kan taşır.'),
  w(T('Vücut'), 'posture',         'duruş',         'isim',  'Good posture is essential for back health.',   'İyi duruş, sırt sağlığı için önemlidir.'),
  w(T('Vücut'), 'cartilage',       'kıkırdak',      'isim',  'Cartilage protects the joints.',               'Kıkırdak eklemleri korur.'),
  w(T('Vücut'), 'gland',           'bez',           'isim',  'The gland produces important hormones.',       'Bez önemli hormonlar üretir.'),
  w(T('Vücut'), 'immune',          'bağışıklık',    'sıfat', 'The immune system fights infections.',         'Bağışıklık sistemi enfeksiyonlarla savaşır.'),
  w(T('Vücut'), 'metabolism',      'metabolizma',   'isim',  'Exercise boosts your metabolism.',             'Egzersiz metabolizmanızı hızlandırır.'),
  w(T('Vücut'), 'neuron',          'nöron',         'isim',  'Neurons transmit signals in the brain.',       'Nöronlar beyindeki sinyalleri iletir.'),
  w(T('Vücut'), 'hormone',         'hormon',        'isim',  'Hormones regulate many body functions.',       'Hormonlar birçok vücut fonksiyonunu düzenler.'),
  w(T('Vücut'), 'vein',            'toplardamar',   'isim',  'Blood flows back to the heart through veins.', 'Kan toplardamarlar yoluyla kalbe geri döner.'),
  w(T('Vücut'), 'spinal',          'omurilik',      'sıfat', 'He suffered a spinal injury.',                 'Omurilik yaralanması geçirdi.'),
  w(T('Vücut'), 'respiratory',     'solunum',       'sıfat', 'Respiratory health is vital.',                 'Solunum sağlığı hayati önem taşır.'),
  w(T('Vücut'), 'reflex',          'refleks',       'isim',  'His reflexes were quick.',                     'Refleksleri hızlıydı.'),
  w(T('Vücut'), 'cavity',          'boşluk',        'isim',  'The chest cavity contains the lungs.',         'Göğüs boşluğu akciğerleri içerir.'),
  w(T('Vücut'), 'bruise',          'çürük',         'isim',  'She had a bruise on her arm.',                 'Kolunda bir çürük vardı.'),
  w(T('Vücut'), 'circulation',     'dolaşım',       'isim',  'Poor circulation causes cold hands.',          'Kötü dolaşım soğuk ellere neden olur.'),
  w(T('Vücut'), 'diagnose',        'teşhis koymak', 'fiil',  'The doctor diagnosed him with flu.',           'Doktor ona grip teşhisi koydu.'),
  w(T('Vücut'), 'affliction',      'hastalık',      'isim',  'He suffered from a rare affliction.',          'Nadir bir hastalıktan muzdaripti.'),
  w(T('Vücut'), 'remedy',         'çare',          'isim',  'Rest is the best remedy for a cold.',          'İstirahat, soğuk algınlığının en iyi çaresidir.'),

  // ── Yiyecekler (B1) ───────────────────────────────────────────────────
  w(T('Yiyecekler'), 'cuisine',       'mutfak',          'isim',  'Italian cuisine is popular worldwide.',         'İtalyan mutfağı dünya çapında popülerdir.'),
  w(T('Yiyecekler'), 'ingredient',    'malzeme',         'isim',  'What ingredients do you need for this recipe?', 'Bu tarif için hangi malzemelere ihtiyacın var?'),
  w(T('Yiyecekler'), 'marinate',      'marine etmek',    'fiil',  'Marinate the chicken overnight.',               'Tavuğu bir gece boyunca marine edin.'),
  w(T('Yiyecekler'), 'serving',        'porsiyon',        'isim',  'One serving contains 200 calories.',            'Bir porsiyon 200 kalori içerir.'),
  w(T('Yiyecekler'), 'nutrition',     'beslenme',        'isim',  'Nutrition labels help you make healthy choices.', 'Besin etiketleri sağlıklı seçimler yapmanıza yardımcı olur.'),
  w(T('Yiyecekler'), 'fermented',     'fermente',        'sıfat', 'Fermented foods are good for digestion.',       'Fermente gıdalar sindirim için iyidir.'),
  w(T('Yiyecekler'), 'seasoning',     'çeşni',           'isim',  'Add seasoning to taste.',                       'Tat için çeşni ekleyin.'),
  w(T('Yiyecekler'), 'garnish',       'süsleme',         'isim',  'The chef added a garnish of herbs.',            'Şef bitkisel bir süsleme ekledi.'),
  w(T('Yiyecekler'), 'appetizer',     'iştah açıcı',     'isim',  'We ordered soup as an appetizer.',              'Başlangıç olarak çorba sipariş ettik.'),
  w(T('Yiyecekler'), 'dessert',       'tatlı',           'isim',  'We shared a chocolate dessert.',                'Çikolatalı bir tatlıyı paylaştık.'),
  w(T('Yiyecekler'), 'beverage',      'içecek',          'isim',  'Please choose your beverage.',                  'Lütfen içeceğinizi seçin.'),
  w(T('Yiyecekler'), 'organic',       'organik',         'sıfat', 'She prefers to buy organic vegetables.',        'Organik sebze almayı tercih ediyor.'),
  w(T('Yiyecekler'), 'calorific',     'kalorili',        'sıfat', 'Fried food is very calorific.',                 'Kızartmalar çok kalorilidir.'),
  w(T('Yiyecekler'), 'texture',       'kıvam',           'isim',  'The cake had a smooth texture.',                'Pastanın pürüzsüz bir kıvamı vardı.'),
  w(T('Yiyecekler'), 'savoury',       'tuzlu',           'sıfat', 'I prefer savoury foods over sweet ones.',      'Tatlı yiyecekler yerine tuzluları tercih ederim.'),
  w(T('Yiyecekler'), 'bittersweet',   'acı tatlı',       'sıfat', 'The chocolate was bittersweet.',               'Çikolata acı tatlıydı.'),
  w(T('Yiyecekler'), 'culinary',      'mutfak sanatı',   'sıfat', 'She has a culinary degree.',                    'Mutfak sanatları diploması var.'),
  w(T('Yiyecekler'), 'staple',        'temel gıda',      'isim',  'Rice is a staple food in many countries.',     'Pirinç birçok ülkede temel gıdadır.'),
  w(T('Yiyecekler'), 'fermentation',  'fermantasyon',    'isim',  'Fermentation changes the flavor of food.',      'Fermantasyon yiyeceğin tadını değiştirir.'),
  w(T('Yiyecekler'), 'protein',       'protein',         'isim',  'Eggs are a great source of protein.',           'Yumurta harika bir protein kaynağıdır.'),

  // ── Giyim (B1) ────────────────────────────────────────────────────────
  w(T('Giyim'), 'attire',           'kıyafet',        'isim',  'Business attire is required for the event.',     'Etkinlik için iş kıyafeti gerekmektedir.'),
  w(T('Giyim'), 'tailor',           'terzi',          'isim',  'The tailor adjusted the suit perfectly.',        'Terzi takım elbiseyi mükemmel şekilde ayarladı.'),
  w(T('Giyim'), 'wrinkle',          'kırışıklık',     'isim',  'Iron the shirt to remove the wrinkles.',        'Kırışıklıkları gidermek için gömleği ütüle.'),
  w(T('Giyim'), 'mend',             'onarmak',        'fiil',  'She mended the torn seam.',                     'Yırtık dikişi onardı.'),
  w(T('Giyim'), 'textile',          'tekstil',        'isim',  'The textile industry is growing rapidly.',      'Tekstil endüstrisi hızla büyüyor.'),
  w(T('Giyim'), 'vintage',          'eski moda',      'sıfat', 'She wore a vintage dress to the party.',        'Partiye eski moda bir elbise giydi.'),
  w(T('Giyim'), 'alteration',       'tadilat',        'isim',  'She took the dress for alteration.',            'Elbiseyi tadilata götürdü.'),
  w(T('Giyim'), 'bespoke',          'ısmarlama',      'sıfat', 'He ordered a bespoke suit.',                    'Ismarlama bir takım elbise sipariş etti.'),
  w(T('Giyim'), 'hemline',          'etek ucu',       'isim',  'The hemline was raised for the new season.',    'Yeni sezon için etek ucu kısa yapıldı.'),
  w(T('Giyim'), 'accessory',        'aksesuar',       'isim',  'The right accessory can complete a look.',      'Doğru aksesuar bir görünümü tamamlayabilir.'),
  w(T('Giyim'), 'lining',           'astar',          'isim',  'The coat has a silk lining.',                   'Montun ipek bir astarı var.'),
  w(T('Giyim'), 'threadbare',       'yıpranmış',      'sıfat', 'The coat was old and threadbare.',              'Mont eski ve yıpranmıştı.'),
  w(T('Giyim'), 'sustainable',      'sürdürülebilir', 'sıfat', 'Sustainable fashion is gaining popularity.',   'Sürdürülebilir moda giderek popülerleşiyor.'),
  w(T('Giyim'), 'dye',              'boyamak',        'fiil',  'She dyed her skirt a new color.',               'Eteğini yeni bir renge boyadı.'),
  w(T('Giyim'), 'collection',       'koleksiyon',     'isim',  'The spring collection was impressive.',         'Bahar koleksiyonu etkileyiciydi.'),
  w(T('Giyim'), 'sheer',            'neredeyse şeffaf','sıfat', 'The blouse was made of sheer fabric.',         'Bluz neredeyse şeffaf kumaştan yapılmıştı.'),
  w(T('Giyim'), 'elastic',          'esnek',          'sıfat', 'The waistband is elastic for comfort.',         'Bel bandı rahatlık için esnektir.'),
  w(T('Giyim'), 'reversible',       'çift taraflı',   'sıfat', 'This jacket is reversible.',                   'Bu ceket çift taraflı.'),
  w(T('Giyim'), 'trendy',           'moda',           'sıfat', 'She always dresses in trendy clothes.',         'Her zaman modaya uygun giyinir.'),
  w(T('Giyim'), 'embroidery',       'nakış',          'isim',  'The blouse has beautiful embroidery on it.',   'Bluzun üzerinde güzel nakışlar var.'),

  // ── Ev ve Mobilya (B1) ────────────────────────────────────────────────
  w(T('Ev ve Mobilya'), 'renovation',   'yenileme',       'isim',  'The kitchen renovation took three weeks.',     'Mutfak yenilemesi üç hafta sürdü.'),
  w(T('Ev ve Mobilya'), 'landlord',     'ev sahibi',      'isim',  'The landlord raised the rent this year.',     'Ev sahibi bu yıl kira artırdı.'),
  w(T('Ev ve Mobilya'), 'tenant',       'kiracı',         'isim',  'The tenant signed a one-year lease.',         'Kiracı bir yıllık kira sözleşmesi imzaladı.'),
  w(T('Ev ve Mobilya'), 'mortgage',     'ipotek',         'isim',  'They took out a mortgage to buy the house.',  'Evi satın almak için ipotek çektiler.'),
  w(T('Ev ve Mobilya'), 'insulation',   'yalıtım',        'isim',  'Good insulation reduces heating costs.',      'İyi yalıtım ısıtma maliyetlerini azaltır.'),
  w(T('Ev ve Mobilya'), 'plumbing',     'sıhhi tesisat',  'isim',  'The plumbing was fixed by a professional.',   'Sıhhi tesisat bir profesyonel tarafından onarıldı.'),
  w(T('Ev ve Mobilya'), 'decor',        'dekorasyon',     'isim',  'The decor of the living room was elegant.',   'Oturma odasının dekorasyonu zarifti.'),
  w(T('Ev ve Mobilya'), 'leakage',      'sızıntı',        'isim',  'There was a water leakage in the ceiling.',   'Tavanda su sızıntısı vardı.'),
  w(T('Ev ve Mobilya'), 'furnish',      'döşemek',        'fiil',  'They furnished the apartment beautifully.',   'Daireyi güzelce döşediler.'),
  w(T('Ev ve Mobilya'), 'loft',         'çatı katı',      'isim',  'They converted the loft into a bedroom.',     'Çatı katını yatak odasına dönüştürdüler.'),
  w(T('Ev ve Mobilya'), 'foyer',        'giriş holü',     'isim',  'The guests waited in the foyer.',             'Misafirler giriş holünde bekledi.'),
  w(T('Ev ve Mobilya'), 'outlet',       'priz',           'isim',  'Plug the charger into the outlet.',           'Şarj cihazını prize tak.'),
  w(T('Ev ve Mobilya'), 'threshold',    'eşik',           'isim',  'He stood at the threshold of the door.',      'Kapının eşiğinde durdu.'),
  w(T('Ev ve Mobilya'), 'floorplan',    'kat planı',      'isim',  'The floorplan shows three bedrooms.',         'Kat planı üç yatak odası gösteriyor.'),
  w(T('Ev ve Mobilya'), 'upholstery',   'döşeme',         'isim',  'The sofa has leather upholstery.',            'Koltukta deri döşeme var.'),
  w(T('Ev ve Mobilya'), 'ventilation',  'havalandırma',   'isim',  'Proper ventilation prevents mold.',           'Uygun havalandırma küfe engel olur.'),
  w(T('Ev ve Mobilya'), 'detached',     'müstakil',       'sıfat', 'They live in a detached house.',              'Müstakil bir evde yaşıyorlar.'),
  w(T('Ev ve Mobilya'), 'faucet',       'musluk',         'isim',  'The faucet was dripping all night.',          'Musluk bütün gece damladı.'),
  w(T('Ev ve Mobilya'), 'remodeling',   'tadilat',        'isim',  'Major remodeling work began last month.',     'Geçen ay büyük tadilat çalışmaları başladı.'),
  w(T('Ev ve Mobilya'), 'storage',      'depolama',       'isim',  'There is plenty of storage in the kitchen.',  'Mutfakta bolca depolama alanı var.'),

  // ── Hayvanlar (B1) ────────────────────────────────────────────────────
  w(T('Hayvanlar'), 'predator',      'yırtıcı',         'isim',  'The lion is a predator at the top of the food chain.', 'Aslan, besin zincirinin zirvesindeki bir yırtıcıdır.'),
  w(T('Hayvanlar'), 'prey',          'av',              'isim',  'The deer was the prey of the wolf.',           'Geyik kurdun avıydı.'),
  w(T('Hayvanlar'), 'habitat',       'habitat',         'isim',  'Deforestation destroys animal habitats.',      'Ormansızlaşma hayvan habitatlarını yok eder.'),
  w(T('Hayvanlar'), 'camouflage',    'kamuflaj',        'isim',  'The chameleon uses camouflage to hide.',       'Bukalemun saklanmak için kamuflaj kullanır.'),
  w(T('Hayvanlar'), 'hibernate',     'kış uykusuna yatmak', 'fiil', 'Bears hibernate during winter.',           'Ayılar kışın kış uykusuna yatar.'),
  w(T('Hayvanlar'), 'domesticated',  'evcilleştirilmiş','sıfat', 'Dogs are domesticated animals.',             'Köpekler evcilleştirilmiş hayvanlardır.'),
  w(T('Hayvanlar'), 'endangered',    'nesli tehlikede', 'sıfat', 'The panda is an endangered species.',         'Panda nesli tehlikede olan bir türdür.'),
  w(T('Hayvanlar'), 'migration',     'göç',             'isim',  'Bird migration occurs twice a year.',          'Kuş göçü yılda iki kez gerçekleşir.'),
  w(T('Hayvanlar'), 'venom',         'zehir',           'isim',  'Some snakes produce deadly venom.',           'Bazı yılanlar ölümcül zehir üretir.'),
  w(T('Hayvanlar'), 'nocturnal',     'gece aktif',      'sıfat', 'Owls are nocturnal birds.',                   'Baykuşlar gece aktif kuşlardır.'),
  w(T('Hayvanlar'), 'omnivore',      'her şeyi yiyen',  'isim',  'Humans are omnivores.',                       'İnsanlar hepçildir.'),
  w(T('Hayvanlar'), 'herbivore',     'otçul',           'isim',  'Rabbits are herbivores.',                     'Tavşanlar otçul hayvanlardır.'),
  w(T('Hayvanlar'), 'carnivore',     'etçil',           'isim',  'Tigers are carnivores.',                      'Kaplanlar etçil hayvanlardır.'),
  w(T('Hayvanlar'), 'extinction',    'nesil tükenmesi', 'isim',  'Many species face extinction today.',         'Günümüzde pek çok tür nesil tükenmesiyle karşı karşıya.'),
  w(T('Hayvanlar'), 'sanctuary',     'sığınak',         'isim',  'The injured bird was taken to a sanctuary.',  'Yaralı kuş bir sığınağa götürüldü.'),
  w(T('Hayvanlar'), 'venomous',      'zehirli',         'sıfat', 'Be careful, that spider is venomous.',       'Dikkatli ol, o örümcek zehirlidir.'),
  w(T('Hayvanlar'), 'tame',          'evcil',           'sıfat', 'The horse became very tame over time.',      'At zamanla çok evcil hale geldi.'),
  w(T('Hayvanlar'), 'poaching',      'kaçak avcılık',   'isim',  'Poaching threatens many wildlife species.',  'Kaçak avcılık birçok yaban hayatı türünü tehdit ediyor.'),
  w(T('Hayvanlar'), 'mating',        'çiftleşme',       'isim',  'Peacocks display their feathers during mating season.', 'Tavus kuşları çiftleşme mevsiminde tüylerini açar.'),
  w(T('Hayvanlar'), 'camouflaged',   'kamufle edilmiş', 'sıfat', 'The insect was perfectly camouflaged on the bark.', 'Böcek kabuk üzerinde mükemmel şekilde kamufle edilmişti.'),

  // ── Günlük Fiiller (B1) ───────────────────────────────────────────────
  w(T('Günlük Fiiller'), 'accomplish',   'başarmak',       'fiil',  'She accomplished all her goals this year.',     'Bu yıl tüm hedeflerini başardı.'),
  w(T('Günlük Fiiller'), 'adapt',        'uyum sağlamak',  'fiil',  'He quickly adapted to the new environment.',   'Yeni ortama hızla uyum sağladı.'),
  w(T('Günlük Fiiller'), 'delay',        'ertelemek',      'fiil',  'They decided to delay the trip.',              'Geziy ertelemeye karar verdiler.'),
  w(T('Günlük Fiiller'), 'negotiate',    'müzakere etmek', 'fiil',  'They negotiated a better deal.',               'Daha iyi bir anlaşma müzakere ettiler.'),
  w(T('Günlük Fiiller'), 'motivate',     'motive etmek',   'fiil',  'The coach motivated the players before the game.', 'Koç oyuncuları maçtan önce motive etti.'),
  w(T('Günlük Fiiller'), 'participate',  'katılmak',       'fiil',  'Everyone is welcome to participate.',           'Herkes katılmaya davetlidir.'),
  w(T('Günlük Fiiller'), 'hesitate',     'tereddüt etmek', 'fiil',  'Don\'t hesitate to ask for help.',             'Yardım istemekten tereddüt etme.'),
  w(T('Günlük Fiiller'), 'prioritize',   'önceliklendirmek','fiil', 'Prioritize your health above everything.',      'Her şeyden önce sağlığını önceliklendir.'),
  w(T('Günlük Fiiller'), 'confront',     'yüzleşmek',      'fiil',  'She confronted her fear of heights.',          'Yükseklik korkusuyla yüzleşti.'),
  w(T('Günlük Fiiller'), 'evaluate',     'değerlendirmek', 'fiil',  'We need to evaluate our progress.',            'İlerlememizi değerlendirmemiz gerekiyor.'),
  w(T('Günlük Fiiller'), 'eliminate',    'ortadan kaldırmak','fiil','We must eliminate all possible risks.',         'Tüm olası riskleri ortadan kaldırmalıyız.'),
  w(T('Günlük Fiiller'), 'establish',    'kurmak',         'fiil',  'They established a new company last year.',    'Geçen yıl yeni bir şirket kurdular.'),
  w(T('Günlük Fiiller'), 'maintain',     'sürdürmek',      'fiil',  'It is hard to maintain a healthy diet.',       'Sağlıklı bir diyet sürdürmek zordur.'),
  w(T('Günlük Fiiller'), 'overcome',     'üstesinden gelmek','fiil','She overcame many obstacles in her life.',     'Hayatında pek çok engelin üstesinden geldi.'),
  w(T('Günlük Fiiller'), 'perceive',     'algılamak',      'fiil',  'How do you perceive this situation?',          'Bu durumu nasıl algılıyorsunuz?'),
  w(T('Günlük Fiiller'), 'pursue',       'peşinden gitmek','fiil',  'He pursued his dream despite the challenges.', 'Zorluklara rağmen hayalinin peşinden gitti.'),
  w(T('Günlük Fiiller'), 'reconsider',   'yeniden düşünmek','fiil', 'Please reconsider your decision.',             'Lütfen kararınızı yeniden düşünün.'),
  w(T('Günlük Fiiller'), 'resolve',      'çözmek',         'fiil',  'We need to resolve this conflict quickly.',    'Bu çatışmayı hızlıca çözmemiz gerekiyor.'),
  w(T('Günlük Fiiller'), 'tolerate',     'tahammül etmek', 'fiil',  'She couldn\'t tolerate the noise anymore.',   'Artık gürültüye tahammül edemedi.'),
  w(T('Günlük Fiiller'), 'transform',    'dönüştürmek',    'fiil',  'Exercise can transform your body.',            'Egzersiz vücudunuzu dönüştürebilir.'),

  // ── Doğa ve Hava (B1) ─────────────────────────────────────────────────
  w(T('Doğa ve Hava'), 'desertification','çölleşme',      'isim',  'Desertification threatens farmland in Africa.',  'Çölleşme Afrika\'daki tarım arazilerini tehdit ediyor.'),
  w(T('Doğa ve Hava'), 'inundation',   'su baskını',     'isim',  'The inundation left roads impassable.',        'Su baskını yolları geçilmez hale getirdi.'),
  w(T('Doğa ve Hava'), 'glacier',      'buzul',          'isim',  'Glaciers are melting due to global warming.',  'Buzullar küresel ısınma nedeniyle eriyor.'),
  w(T('Doğa ve Hava'), 'erosion',      'erozyon',        'isim',  'Erosion damaged the coastline.',               'Erozyon kıyı şeridine zarar verdi.'),
  w(T('Doğa ve Hava'), 'ecosystem',    'ekosistem',      'isim',  'We must protect the ocean ecosystem.',         'Okyanus ekosistemini korumamız gerekiyor.'),
  w(T('Doğa ve Hava'), 'precipitation','yağış',          'isim',  'High precipitation is expected this week.',    'Bu hafta yüksek yağış bekleniyor.'),
  w(T('Doğa ve Hava'), 'humidity',     'nem',            'isim',  'The humidity made the heat unbearable.',       'Nem sıcağı dayanılmaz kıldı.'),
  w(T('Doğa ve Hava'), 'landslide',    'heyelan',        'isim',  'A landslide blocked the mountain road.',       'Heyelan dağ yolunu kapattı.'),
  w(T('Doğa ve Hava'), 'biodiversity', 'biyoçeşitlilik', 'isim',  'Biodiversity is essential for life on Earth.', 'Biyoçeşitlilik, Dünya\'daki yaşam için elzemdir.'),
  w(T('Doğa ve Hava'), 'deforestation','ormansızlaşma',  'isim',  'Deforestation threatens wildlife.',            'Ormansızlaşma yaban hayatını tehdit ediyor.'),
  w(T('Doğa ve Hava'), 'altitude',     'rakım',          'isim',  'The altitude affected his breathing.',         'Rakım nefes almasını etkiledi.'),
  w(T('Doğa ve Hava'), 'terrain',      'arazi',          'isim',  'The terrain was rocky and difficult to cross.','Arazi kayalık ve geçilmesi zordu.'),
  w(T('Doğa ve Hava'), 'renewable',    'yenilenebilir',  'sıfat', 'We must invest in renewable energy.',          'Yenilenebilir enerjiye yatırım yapmalıyız.'),
  w(T('Doğa ve Hava'), 'tidal',        'gelgitli',       'sıfat', 'Tidal waves can be very destructive.',        'Gelgit dalgaları çok yıkıcı olabilir.'),
  w(T('Doğa ve Hava'), 'temperate',    'ılıman',         'sıfat', 'The region has a temperate climate.',         'Bölgenin ılıman bir iklimi var.'),
  w(T('Doğa ve Hava'), 'catastrophe',  'felaket',        'isim',  'The earthquake was a natural catastrophe.',   'Deprem doğal bir felaket ti.'),
  w(T('Doğa ve Hava'), 'emission',     'emisyon',        'isim',  'We need to reduce carbon emissions.',          'Karbon emisyonlarını azaltmamız gerekiyor.'),
  w(T('Doğa ve Hava'), 'conservation', 'koruma',         'isim',  'Wildlife conservation is a global issue.',     'Yaban hayatı koruma küresel bir sorundur.'),
  w(T('Doğa ve Hava'), 'estuary',      'haliç',          'isim',  'The estuary is home to many birds.',           'Haliç birçok kuşa ev sahipliği yapar.'),
  w(T('Doğa ve Hava'), 'gust',         'rüzgar kası',    'isim',  'A strong gust of wind knocked the sign down.', 'Güçlü bir rüzgar kasırgası tabelayı devirdi.'),

  // ── Günler, Aylar, Mevsimler (B1) ─────────────────────────────────────
  w(T('Günler, Aylar, Mevsimler'), 'fiscal',        'mali',           'sıfat', 'The fiscal year ends in December.',             'Mali yıl Aralık\'ta sona erer.'),
  w(T('Günler, Aylar, Mevsimler'), 'solstice',      'gün dönümü',     'isim',  'The summer solstice is the longest day.',       'Yaz gün dönümü en uzun gündür.'),
  w(T('Günler, Aylar, Mevsimler'), 'equinox',       'ekinoks',        'isim',  'Day and night are equal at the equinox.',       'Ekinoksta gün ve gece eşittir.'),
  w(T('Günler, Aylar, Mevsimler'), 'leap year',     'artık yıl',      'isim',  'February has 29 days in a leap year.',          'Artık yılda Şubat 29 gün çeker.'),
  w(T('Günler, Aylar, Mevsimler'), 'millennium',    'bin yıl',        'isim',  'A new millennium began in the year 2000.',      'Yeni bir bin yıl 2000 yılında başladı.'),
  w(T('Günler, Aylar, Mevsimler'), 'quarterly',     'üç aylık',       'sıfat', 'The report is published quarterly.',            'Rapor üç ayda bir yayımlanır.'),
  w(T('Günler, Aylar, Mevsimler'), 'commemoration', 'anma töreni',    'isim',  'The commemoration was held on the 10th.',       'Anma töreni 10\'unda yapıldı.'),
  w(T('Günler, Aylar, Mevsimler'), 'epoch',         'çağ',            'isim',  'We are entering a new technological epoch.',   'Yeni bir teknolojik çağa giriyoruz.'),
  w(T('Günler, Aylar, Mevsimler'), 'biannual',      'yılda iki kez',  'sıfat', 'The event is held biannually.',                 'Etkinlik yılda iki kez düzenlenir.'),
  w(T('Günler, Aylar, Mevsimler'), 'era',           'dönem',          'isim',  'The Renaissance was an important era.',         'Rönesans önemli bir dönemdi.'),
  w(T('Günler, Aylar, Mevsimler'), 'overdue',       'gecikmiş',       'sıfat', 'The library book is long overdue.',             'Kütüphane kitabı çoktan gecikmiş.'),
  w(T('Günler, Aylar, Mevsimler'), 'timetable',     'zaman çizelgesi','isim',  'The project timetable was updated.',            'Proje zaman çizelgesi güncellendi.'),
  w(T('Günler, Aylar, Mevsimler'), 'interval',      'aralık',         'isim',  'There was a short interval between sessions.',  'Oturumlar arasında kısa bir aralık vardı.'),
  w(T('Günler, Aylar, Mevsimler'), 'longevity',     'uzun ömürlülük', 'isim',  'Regular exercise contributes to longevity.',    'Düzenli egzersiz uzun ömürlülüğe katkıda bulunur.'),
  w(T('Günler, Aylar, Mevsimler'), 'perpetual',     'sürekli',        'sıfat', 'She was in a state of perpetual stress.',       'Sürekli bir stres halindeydi.'),
  w(T('Günler, Aylar, Mevsimler'), 'consecutive',   'ardışık',        'sıfat', 'He worked five consecutive days.',              'Beş ardışık gün çalıştı.'),
  w(T('Günler, Aylar, Mevsimler'), 'milestone',     'kilometre taşı', 'isim',  'Graduating was a major milestone.',             'Mezun olmak büyük bir kilometre taşıydı.'),
  w(T('Günler, Aylar, Mevsimler'), 'transition',    'geçiş',          'isim',  'The transition from summer to autumn was fast.','Yazdan sonbahara geçiş hızlıydı.'),
  w(T('Günler, Aylar, Mevsimler'), 'interim',       'geçici',         'sıfat', 'An interim manager was appointed.',             'Geçici bir müdür atandı.'),
  w(T('Günler, Aylar, Mevsimler'), 'prolonged',     'uzayan',         'sıfat', 'There was a prolonged silence in the room.',   'Odada uzayan bir sessizlik oldu.'),

  // ── Zaman (B1) ────────────────────────────────────────────────────────
  w(T('Zaman'), 'simultaneous',   'eş zamanlı',     'sıfat', 'Simultaneous translation was provided.',          'Eş zamanlı çeviri sağlandı.'),
  w(T('Zaman'), 'momentary',      'anlık',          'sıfat', 'There was a momentary pause in the music.',       'Müzikte anlık bir duraklama oldu.'),
  w(T('Zaman'), 'elapsed',        'geçmiş',         'sıfat', 'An hour had elapsed since he left.',              'Ayrılmasından bu yana bir saat geçmişti.'),
  w(T('Zaman'), 'eventual',       'nihai',          'sıfat', 'The eventual outcome was a success.',             'Nihai sonuç bir başarıydı.'),
  w(T('Zaman'), 'promptly',       'derhal',         'zarf',  'She replied promptly to all emails.',             'Tüm e-postalara derhal yanıt verdi.'),
  w(T('Zaman'), 'postpone',       'ertelemek',      'fiil',  'The meeting was postponed to next week.',         'Toplantı gelecek haftaya ertelendi.'),
  w(T('Zaman'), 'punctual',       'dakik',          'sıfat', 'He is always punctual for appointments.',        'Randevularına her zaman dakiktir.'),
  w(T('Zaman'), 'obsolete',       'eskimiş',        'sıfat', 'That technology is now obsolete.',               'O teknoloji artık eskimiş.'),
  w(T('Zaman'), 'contemporary',   'çağdaş',         'sıfat', 'She is a contemporary artist.',                  'Çağdaş bir sanatçıdır.'),
  w(T('Zaman'), 'foreseeable',    'öngörülebilir',  'sıfat', 'In the foreseeable future, nothing will change.','Öngörülebilir gelecekte hiçbir şey değişmeyecek.'),
  w(T('Zaman'), 'timely',         'zamanında',      'sıfat', 'A timely response is important in business.',    'İş dünyasında zamanında yanıt önemlidir.'),
  w(T('Zaman'), 'outdated',       'güncelliğini yitirmiş','sıfat','The system is outdated and needs updating.','Sistem güncelliğini yitirmiş ve güncellenmesi gerekiyor.'),
  w(T('Zaman'), 'chronological',  'kronolojik',     'sıfat', 'List the events in chronological order.',        'Olayları kronolojik sıraya göre listele.'),
  w(T('Zaman'), 'recurrent',      'tekrarlayan',    'sıfat', 'He had recurrent headaches.',                    'Tekrarlayan baş ağrıları vardı.'),
  w(T('Zaman'), 'imminent',       'yakın',          'sıfat', 'The storm was imminent.',                        'Fırtına yakındı.'),
  w(T('Zaman'), 'lapse',          'geçmek',         'fiil',  'Time seems to lapse quickly when you are busy.', 'Meşgulken zaman hızla geçiyor gibi görünür.'),
  w(T('Zaman'), 'expedite',       'hızlandırmak',   'fiil',  'We need to expedite the delivery process.',      'Teslimat sürecini hızlandırmamız gerekiyor.'),
  w(T('Zaman'), 'cutoff',         'son tarih',      'isim',  'The cutoff date for applications is Friday.',   'Başvurular için son tarih Cuma\'dır.'),
  w(T('Zaman'), 'linger',         'oyalanmak',      'fiil',  'Don\'t linger in the doorway.',                 'Kapı eşiğinde oyalanma.'),
  w(T('Zaman'), 'retrospect',     'geriye bakış',   'isim',  'In retrospect, the decision was wrong.',         'Geriye bakıldığında, karar yanlıştı.'),

  // ── Ulaşım (B1) ───────────────────────────────────────────────────────
  w(T('Ulaşım'), 'commute',       'işe gidip gelmek','fiil', 'He commutes two hours every day.',               'Her gün iki saat işe gidip geliyor.'),
  w(T('Ulaşım'), 'infrastructure','altyapı',         'isim', 'The transport infrastructure needs improvement.', 'Ulaşım altyapısının iyileştirilmesi gerekiyor.'),
  w(T('Ulaşım'), 'exhaust',       'egzoz',           'isim', 'Electric cars produce no exhaust fumes.',        'Elektrikli araçlar egzoz dumanı üretmez.'),
  w(T('Ulaşım'), 'congestion',    'trafik sıkışıklığı','isim','Traffic congestion is a big problem in cities.','Trafik sıkışıklığı şehirlerde büyük bir sorundur.'),
  w(T('Ulaşım'), 'carpool',       'araç paylaşımı',  'isim', 'Carpooling reduces traffic and pollution.',      'Araç paylaşımı trafiği ve kirliliği azaltır.'),
  w(T('Ulaşım'), 'itinerary',     'seyahat planı',   'isim', 'The travel agency sent us the itinerary.',       'Seyahat acentesi bize seyahat planını gönderdi.'),
  w(T('Ulaşım'), 'navigation',    'navigasyon',      'isim', 'GPS navigation made driving much easier.',       'GPS navigasyon araç kullanmayı çok kolaylaştırdı.'),
  w(T('Ulaşım'), 'pedestrian',    'yaya',            'isim', 'Pedestrians should use the crosswalk.',          'Yayalar yaya geçidini kullanmalıdır.'),
  w(T('Ulaşım'), 'cargo',         'kargo',           'isim', 'The ship was loaded with cargo.',                'Gemi kargoyla yüklendi.'),
  w(T('Ulaşım'), 'transit',       'transit',         'isim', 'The goods were in transit for two weeks.',       'Mallar iki hafta boyunca transit taşımadaydı.'),
  w(T('Ulaşım'), 'overpass',      'köprülü kavşak',  'isim', 'The overpass was built to ease traffic.',        'Köprülü kavşak trafiği rahatlatmak için inşa edildi.'),
  w(T('Ulaşım'), 'roundabout',    'dönel kavşak',    'isim', 'Turn left at the roundabout.',                   'Dönel kavşakta sola dönün.'),
  w(T('Ulaşım'), 'commuter',      'işe gidip gelen', 'isim', 'The train is full of commuters in the morning.', 'Tren sabahları işe gidip gelenlerle dolu.'),
  w(T('Ulaşım'), 'toll',          'ücret',           'isim', 'There is a toll to cross this bridge.',          'Bu köprüden geçmek için ücret alınır.'),
  w(T('Ulaşım'), 'bypass',        'çevre yolu',      'isim', 'We took the bypass to avoid traffic.',           'Trafikten kaçınmak için çevre yolunu kullandık.'),
  w(T('Ulaşım'), 'depart',        'hareket etmek',   'fiil', 'The train departs at 8 am.',                    'Tren sabah 8\'de hareket eder.'),
  w(T('Ulaşım'), 'terminal',      'terminal',        'isim', 'Check-in is at terminal 2.',                     'Check-in terminal 2\'dedir.'),
  w(T('Ulaşım'), 'elevation',     'yükseklik',       'isim', 'The plane reached its cruising elevation.',      'Uçak seyir yüksekliğine ulaştı.'),
  w(T('Ulaşım'), 'layover',       'aktarma',         'isim', 'Our flight has a three-hour layover in Paris.',  'Uçuşumuzun Paris\'te üç saatlik aktarması var.'),
  w(T('Ulaşım'), 'dispatch',      'sevkiyat',        'isim', 'The dispatch center coordinated all deliveries.','Sevkiyat merkezi tüm teslimatları koordine etti.'),

  // ── Şehir ve Mekanlar (B1) ────────────────────────────────────────────
  w(T('Şehir ve Mekanlar'), 'metropolitan',  'büyükşehir',     'sıfat', 'Istanbul is a metropolitan city.',              'İstanbul büyükşehirdir.'),
  w(T('Şehir ve Mekanlar'), 'borough',       'bölge',          'isim',  'Each borough has its own council.',             'Her bölgenin kendi konseyi var.'),
  w(T('Şehir ve Mekanlar'), 'precinct',      'semt',           'isim',  'The police precinct covers this area.',         'Polis semt birimi bu bölgeyi kapsıyor.'),
  w(T('Şehir ve Mekanlar'), 'municipality',  'belediye',       'isim',  'The municipality fixed the roads.',             'Belediye yolları tamir etti.'),
  w(T('Şehir ve Mekanlar'), 'gentrification','soylulaştırma',  'isim',  'Gentrification is changing the old neighborhood.','Soylulaştırma eski mahalleyi değiştiriyor.'),
  w(T('Şehir ve Mekanlar'), 'alley',         'ara sokak',      'isim',  'They walked through a narrow alley.',           'Dar bir ara sokaktan geçtiler.'),
  w(T('Şehir ve Mekanlar'), 'boulevard',     'bulvar',         'isim',  'The café is on the main boulevard.',            'Kafe ana bulvardadır.'),
  w(T('Şehir ve Mekanlar'), 'monument',      'anıt',           'isim',  'The monument was built to honor the soldiers.', 'Anıt askerleri onurlandırmak için inşa edildi.'),
  w(T('Şehir ve Mekanlar'), 'plaza',         'meydan',         'isim',  'We met at the central plaza.',                  'Merkez meydanda buluştuk.'),
  w(T('Şehir ve Mekanlar'), 'periphery',     'kenar mahalle',  'isim',  'They moved to the periphery of the city.',     'Şehrin kenar mahallesine taşındılar.'),
  w(T('Şehir ve Mekanlar'), 'urban',         'kentsel',        'sıfat', 'Urban areas face unique challenges.',           'Kentsel alanlar kendine özgü zorluklarla karşı karşıya.'),
  w(T('Şehir ve Mekanlar'), 'rural',         'kırsal',         'sıfat', 'She prefers rural life over city life.',        'Şehir yerine kırsal yaşamı tercih ediyor.'),
  w(T('Şehir ve Mekanlar'), 'civic',         'sivil',          'sıfat', 'Citizens have civic responsibilities.',          'Vatandaşların sivil sorumlulukları vardır.'),
  w(T('Şehir ve Mekanlar'), 'residential',   'konut',          'sıfat', 'This is a residential area.',                   'Burası konut bölgesidir.'),
  w(T('Şehir ve Mekanlar'), 'commercial',    'ticari',         'sıfat', 'The commercial district is very busy.',         'Ticari bölge çok işlek.'),
  w(T('Şehir ve Mekanlar'), 'zoning',        'imar',           'isim',  'Zoning laws limit building heights.',           'İmar yasaları bina yüksekliklerini sınırlar.'),
  w(T('Şehir ve Mekanlar'), 'pedestrianize', 'yayalaştırmak',  'fiil',  'The city decided to pedestrianize the center.', 'Şehir merkezi yayalaştırmaya karar verdi.'),
  w(T('Şehir ve Mekanlar'), 'greenspace',    'yeşil alan',     'isim',  'More greenspace is needed in the city.',        'Şehirde daha fazla yeşil alan gerekiyor.'),
  w(T('Şehir ve Mekanlar'), 'architecture',  'mimari',         'isim',  'The city is known for its unique architecture.','Şehir kendine özgü mimarisiyle tanınır.'),
  w(T('Şehir ve Mekanlar'), 'sewage',        'kanalizasyon',   'isim',  'The sewage system needs an upgrade.',           'Kanalizasyon sistemi yenilenmeye ihtiyaç duyuyor.'),

  // ── Alışveriş (B1) ────────────────────────────────────────────────────
  w(T('Alışveriş'), 'guarantee',     'güvence',          'isim',  'The product comes with a satisfaction guarantee.','Ürün memnuniyet güvencesiyle geliyor.'),
  w(T('Alışveriş'), 'installment',   'taksit',           'isim',  'She paid for the laptop in installments.',       'Dizüstü bilgisayarı taksitle ödedi.'),
  w(T('Alışveriş'), 'wholesale',     'toptan',           'isim',  'They bought the goods at wholesale prices.',     'Malları toptan fiyata satın aldılar.'),
  w(T('Alışveriş'), 'retail',        'perakende',        'isim',  'Retail prices are higher than wholesale.',       'Perakende fiyatlar toptandan daha yüksektir.'),
  w(T('Alışveriş'), 'reimbursement', 'geri ödeme',       'isim',  'She requested reimbursement for the broken item.','Kırık ürün için geri ödeme talep etti.'),
  w(T('Alışveriş'), 'barter',        'takas',            'isim',  'In some markets, barter is still used.',        'Bazı pazarlarda hâlâ takas kullanılmaktadır.'),
  w(T('Alışveriş'), 'loyalty card',  'sadakat kartı',    'isim',  'Use your loyalty card to earn points.',         'Puan kazanmak için sadakat kartını kullan.'),
  w(T('Alışveriş'), 'billing',       'fatura kesme',     'isim',  'Monthly billing is sent automatically.',         'Aylık fatura kesme otomatik olarak yapılır.'),
  w(T('Alışveriş'), 'counterfeit',   'sahte',            'sıfat', 'The bag was counterfeit, not an original.',     'Çanta orijinal değil, sahteydi.'),
  w(T('Alışveriş'), 'vendor',        'satıcı',           'isim',  'The street vendor sold fresh fruit.',           'Sokak satıcısı taze meyve satıyordu.'),
  w(T('Alışveriş'), 'auction',       'müzayede',         'isim',  'The painting was sold at auction.',              'Tablo müzayedede satıldı.'),
  w(T('Alışveriş'), 'surplus',       'fazlalık',         'isim',  'The store had a surplus of winter coats.',      'Mağazanın kış montlarında fazlalık vardı.'),
  w(T('Alışveriş'), 'consumerism',   'tüketicilik',      'isim',  'Consumerism is driving overconsumption.',       'Tüketicilik aşırı tüketime yol açıyor.'),
  w(T('Alışveriş'), 'transaction',   'işlem',            'isim',  'The bank declined the transaction.',             'Banka işlemi reddetti.'),
  w(T('Alışveriş'), 'bargain',        'pazarlık yapmak',  'fiil',  'She bargained for a lower price at the market.','Pazarda daha düşük bir fiyat için pazarlık yaptı.'),
  w(T('Alışveriş'), 'subscribe',     'abone olmak',      'fiil',  'Subscribe to get exclusive discounts.',          'Özel indirimler için abone ol.'),
  w(T('Alışveriş'), 'premium',       'birinci kalite',   'sıfat', 'This is a premium brand.',                      'Bu birinci kalite bir markadır.'),
  w(T('Alışveriş'), 'coupon',        'kupon',            'isim',  'She used a coupon for 10% off.',                 'Yüzde 10 indirim için kupon kullandı.'),
  w(T('Alışveriş'), 'expenditure',   'harcama',          'isim',  'Monthly expenditure must be kept under control.','Aylık harcamalar kontrol altında tutulmalıdır.'),
  w(T('Alışveriş'), 'impulse',       'dürtü',            'isim',  'He made an impulse purchase at the store.',     'Mağazada dürtüsel bir satın alma yaptı.'),

  // ── Meslekler (B1) ────────────────────────────────────────────────────
  w(T('Meslekler'), 'entrepreneur',  'girişimci',       'isim',  'She became a successful entrepreneur.',          'Başarılı bir girişimci oldu.'),
  w(T('Meslekler'), 'consultant',    'danışman',        'isim',  'They hired a consultant to improve sales.',      'Satışları artırmak için bir danışman tuttular.'),
  w(T('Meslekler'), 'freelancer',    'serbest çalışan', 'isim',  'He works as a freelancer from home.',            'Evden serbest çalışan olarak çalışıyor.'),
  w(T('Meslekler'), 'supervisor',    'amir',            'isim',  'The supervisor reviewed the work.',              'Amir çalışmayı gözden geçirdi.'),
  w(T('Meslekler'), 'recruiter',     'işe alım uzmanı', 'isim',  'The recruiter contacted me about the vacancy.',  'İşe alım uzmanı pozisyon hakkında benimle iletişime geçti.'),
  w(T('Meslekler'), 'intern',        'stajyer',         'isim',  'The intern worked in the marketing department.', 'Stajyer pazarlama departmanında çalıştı.'),
  w(T('Meslekler'), 'executive',     'yönetici',        'isim',  'The executive made an important decision.',      'Yönetici önemli bir karar aldı.'),
  w(T('Meslekler'), 'analyst',       'analist',         'isim',  'The analyst reviewed the market trends.',       'Analist piyasa trendlerini inceledi.'),
  w(T('Meslekler'), 'mediator',      'arabulucu',       'isim',  'A mediator helped resolve the dispute.',        'Arabulucu anlaşmazlığı çözmeye yardımcı oldu.'),
  w(T('Meslekler'), 'auditor',       'denetçi',         'isim',  'The auditor checked the company\'s finances.',  'Denetçi şirketin finanslarını kontrol etti.'),
  w(T('Meslekler'), 'diplomat',      'diplomat',        'isim',  'The diplomat negotiated a peace treaty.',       'Diplomat bir barış antlaşması müzakere etti.'),
  w(T('Meslekler'), 'craftsman',     'zanaatkar',       'isim',  'The craftsman made a beautiful table.',         'Zanaatkar güzel bir masa yaptı.'),
  w(T('Meslekler'), 'paralegal',     'hukuk asistanı',  'isim',  'The paralegal prepared the legal documents.',   'Hukuk asistanı yasal belgeleri hazırladı.'),
  w(T('Meslekler'), 'curator',       'küratör',         'isim',  'The curator organized the art exhibition.',     'Küratör sanat sergisini düzenledi.'),
  w(T('Meslekler'), 'pharmacist',    'eczacı',          'isim',  'The pharmacist explained how to take the medicine.','Eczacı ilacı nasıl alacağını anlattı.'),
  w(T('Meslekler'), 'radiologist',   'radyolog',        'isim',  'The radiologist read the x-ray.',               'Radyolog röntgeni okudu.'),
  w(T('Meslekler'), 'horticulturist','bahçıvan uzmanı',  'isim', 'The horticulturist advised on plant care.',      'Bahçıvan uzmanı bitki bakımı konusunda tavsiyelerde bulundu.'),
  w(T('Meslekler'), 'logistician',   'lojistikçi',      'isim',  'The logistician coordinated the supply chain.', 'Lojistikçi tedarik zincirini koordine etti.'),
  w(T('Meslekler'), 'biomedical',    'biyomedikal',     'sıfat', 'She works in biomedical research.',             'Biyomedikal araştırmada çalışıyor.'),
  w(T('Meslekler'), 'actuary',       'aktüer',          'isim',  'The actuary calculated insurance risks.',        'Aktüer sigorta risklerini hesapladı.'),

  // ── Okul ve Eğitim (B1) ───────────────────────────────────────────────
  w(T('Okul ve Eğitim'), 'coursework',   'ders çalışması',  'isim',  'The coursework was assessed throughout the year.','Ders çalışması yıl boyunca değerlendirildi.'),
  w(T('Okul ve Eğitim'), 'fellowship',   'akademik burs',   'isim',  'She received a fellowship to study abroad.',    'Yurt dışında çalışmak için akademik burs aldı.'),
  w(T('Okul ve Eğitim'), 'dissertation', 'tez',             'isim',  'He submitted his dissertation last week.',      'Geçen hafta tezini teslim etti.'),
  w(T('Okul ve Eğitim'), 'trimester',    'üç aylık dönem',  'isim',  'The school year is divided into trimesters.',   'Okul yılı üç aylık dönemlere ayrılmıştır.'),
  w(T('Okul ve Eğitim'), 'syllabus',     'ders programı',   'isim',  'Read the syllabus before the first class.',     'İlk dersten önce ders programını oku.'),
  w(T('Okul ve Eğitim'), 'accredited',   'akredite',        'sıfat', 'Make sure the institution is accredited.',     'Kurumun akredite olduğundan emin ol.'),
  w(T('Okul ve Eğitim'), 'enrollment',   'kayıt',           'isim',  'Enrollment for the new term is now open.',     'Yeni dönem kayıtları şimdi açık.'),
  w(T('Okul ve Eğitim'), 'tutoring',     'özel ders',       'isim',  'He provided tutoring in mathematics.',          'Matematikte özel ders verdi.'),
  w(T('Okul ve Eğitim'), 'plagiarism',   'intihal',         'isim',  'Plagiarism is a serious academic offence.',    'İntihal ciddi bir akademik suçtur.'),
  w(T('Okul ve Eğitim'), 'certify',      'sertifikalandırmak','fiil','The program certifies students in first aid.',  'Program öğrencileri ilk yardım konusunda sertifikalandırır.'),
  w(T('Okul ve Eğitim'), 'elective',     'seçmeli ders',    'isim',  'Students can choose any elective they like.',  'Öğrenciler istedikleri seçmeli dersi seçebilir.'),
  w(T('Okul ve Eğitim'), 'faculty',      'fakülte',         'isim',  'She is part of the science faculty.',           'Fen fakültesinin bir üyesidir.'),
  w(T('Okul ve Eğitim'), 'transcript',   'transkript',      'isim',  'Submit your official transcript.',              'Resmi transkriptini teslim et.'),
  w(T('Okul ve Eğitim'), 'postgraduate', 'lisansüstü',      'sıfat', 'He enrolled in a postgraduate program.',       'Lisansüstü programa kayıt yaptırdı.'),
  w(T('Okul ve Eğitim'), 'academic',     'akademik',        'sıfat', 'Her academic performance improved this year.', 'Akademik performansı bu yıl iyileşti.'),
  w(T('Okul ve Eğitim'), 'internship',   'staj',            'isim',  'The internship gave her valuable experience.',  'Staj ona değerli deneyim kazandırdı.'),
  w(T('Okul ve Eğitim'), 'mentorship',   'mentorluk',       'isim',  'Good mentorship can guide your career.',        'İyi mentorluk kariyerinizi yönlendirebilir.'),
  w(T('Okul ve Eğitim'), 'pedagogy',     'pedagoji',        'isim',  'Modern pedagogy focuses on the student.',       'Modern pedagoji öğrenciye odaklanır.'),
  w(T('Okul ve Eğitim'), 'literacy',     'okuryazarlık',    'isim',  'Digital literacy is essential nowadays.',       'Dijital okuryazarlık günümüzde zorunludur.'),
  w(T('Okul ve Eğitim'), 'recess',       'teneffüs',        'isim',  'Children played outside during recess.',        'Çocuklar teneffüste dışarıda oynadı.'),

  // ── Sağlık (B1) ───────────────────────────────────────────────────────
  w(T('Sağlık'), 'rehabilitation',  'rehabilitasyon',   'isim',  'He underwent rehabilitation after surgery.',     'Ameliyat sonrası rehabilitasyon gördü.'),
  w(T('Sağlık'), 'chronic',         'kronik',           'sıfat', 'She suffers from chronic back pain.',            'Kronik sırt ağrısı çekiyor.'),
  w(T('Sağlık'), 'epidemic',        'salgın',           'isim',  'The epidemic spread across multiple countries.',  'Salgın birçok ülkeye yayıldı.'),
  w(T('Sağlık'), 'vaccination',     'aşılama',          'isim',  'Vaccination helps prevent serious diseases.',    'Aşılama ciddi hastalıkların önüne geçer.'),
  w(T('Sağlık'), 'prognosis',       'prognoz',          'isim',  'The doctor gave a positive prognosis.',          'Doktor olumlu bir prognoz verdi.'),
  w(T('Sağlık'), 'sanitation',      'sanitasyon',       'isim',  'Sanitation is vital for public health.',         'Sanitasyon, halk sağlığı için hayati önem taşır.'),
  w(T('Sağlık'), 'contagious',      'bulaşıcı',         'sıfat', 'The virus is highly contagious.',               'Virüs son derece bulaşıcıdır.'),
  w(T('Sağlık'), 'preventable',     'önlenebilir',      'sıfat', 'Many diseases are preventable with vaccines.',  'Pek çok hastalık aşıyla önlenebilir.'),
  w(T('Sağlık'), 'physiology',      'fizyoloji',        'isim',  'She studied physiology at university.',          'Üniversitede fizyoloji okudu.'),
  w(T('Sağlık'), 'malnourished',    'yetersiz beslenen','sıfat', 'The child was malnourished and frail.',          'Çocuk yetersiz besleniyor ve zayıftı.'),
  w(T('Sağlık'), 'ailment',         'rahatsızlık',      'isim',  'He complained about a minor ailment.',           'Küçük bir rahatsızlıktan şikayet etti.'),
  w(T('Sağlık'), 'immunity',        'bağışıklık',       'isim',  'A healthy diet boosts immunity.',                'Sağlıklı beslenme bağışıklığı güçlendirir.'),
  w(T('Sağlık'), 'sedentary',       'hareketsiz',       'sıfat', 'A sedentary lifestyle is bad for health.',       'Hareketsiz bir yaşam tarzı sağlık için kötüdür.'),
  w(T('Sağlık'), 'cardiologist',    'kardiyolog',        'isim',  'The cardiologist reviewed his heart results.',  'Kardiyolog kalp sonuçlarını inceledi.'),
  w(T('Sağlık'), 'dosage',          'dozaj',            'isim',  'Take the correct dosage of the medicine.',       'İlacın doğru dozajını alın.'),
  w(T('Sağlık'), 'ward',            'koğuş',            'isim',  'The patient was moved to a private ward.',       'Hasta özel bir koğuşa alındı.'),
  w(T('Sağlık'), 'prescription',    'reçete',           'isim',  'You need a prescription for this medicine.',     'Bu ilaç için reçeteye ihtiyacınız var.'),
  w(T('Sağlık'), 'outbreak',        'salgın patlak',    'isim',  'An outbreak of flu swept through the school.',   'Okulda grip salgını patlak verdi.'),
  w(T('Sağlık'), 'organ',           'organ',            'isim',  'Organ donation can save lives.',                 'Organ bağışı hayat kurtarabilir.'),
  w(T('Sağlık'), 'mental health',   'ruh sağlığı',      'isim',  'Mental health is as important as physical health.','Ruh sağlığı, fiziksel sağlık kadar önemlidir.'),

  // ── Spor (B1) ─────────────────────────────────────────────────────────
  w(T('Spor'), 'endurance',       'dayanıklılık',    'isim',  'Marathon running requires great endurance.',      'Maraton koşmak büyük dayanıklılık gerektirir.'),
  w(T('Spor'), 'agility',         'çeviklik',        'isim',  'Football players need agility.',                  'Futbolcular çevikliğe ihtiyaç duyar.'),
  w(T('Spor'), 'championship',    'şampiyona',       'isim',  'They won the national championship.',             'Ulusal şampiyonayı kazandılar.'),
  w(T('Spor'), 'penalty',         'penaltı',         'isim',  'He scored the winning penalty.',                  'Kazandıran penaltıyı o attı.'),
  w(T('Spor'), 'doping',          'doping',          'isim',  'Doping is banned in all professional sports.',   'Doping tüm profesyonel sporlarda yasaktır.'),
  w(T('Spor'), 'substitute',      'yedek oyuncu',    'isim',  'The substitute came on in the second half.',     'Yedek ikinci yarıda sahaya girdi.'),
  w(T('Spor'), 'umpire',          'hakem',           'isim',  'The umpire made a controversial call.',          'Hakem tartışmalı bir karar verdi.'),
  w(T('Spor'), 'hydration',       'sıvı alımı',      'isim',  'Good hydration is essential during exercise.',  'Egzersiz sırasında iyi sıvı alımı önemlidir.'),
  w(T('Spor'), 'stamina',         'enerji',          'isim',  'She has great stamina for a long race.',         'Uzun koşu için harika enerjisi var.'),
  w(T('Spor'), 'playoff',         'eleme',           'isim',  'The team advanced to the playoff round.',        'Takım eleme turuna ilerledi.'),
  w(T('Spor'), 'disqualified',    'diskalifiye',     'sıfat', 'The runner was disqualified for cheating.',      'Koşucu hile yapması nedeniyle diskalifiye edildi.'),
  w(T('Spor'), 'sportsmanship',   'centilmenlik',    'isim',  'Good sportsmanship means respecting opponents.', 'İyi centilmenlik rakiplere saygı göstermek anlamına gelir.'),
  w(T('Spor'), 'dash',            'kısa koşu',       'isim',  'She won the 100m dash easily.',                  '100 metre kısa koşusunu kolayca kazandı.'),
  w(T('Spor'), 'tactics',         'taktik',          'isim',  'The coach explained the team\'s tactics.',      'Koç takımın taktiklerini anlattı.'),
  w(T('Spor'), 'offside',         'ofsayt',          'isim',  'The goal was cancelled for offside.',           'Gol ofsayt nedeniyle iptal edildi.'),
  w(T('Spor'), 'fixture',         'maç programı',    'isim',  'The fixture list was published today.',          'Maç programı bugün yayımlandı.'),
  w(T('Spor'), 'podium',          'podyum',          'isim',  'The athlete stood on the podium to receive their medal.','Sporcu madalyasını almak için podyuma çıktı.'),
  w(T('Spor'), 'velocity',        'hız',             'isim',  'The velocity of the ball was incredible.',       'Topun hızı inanılmazdı.'),
  w(T('Spor'), 'physique',        'fizik yapı',      'isim',  'The swimmer had an impressive physique.',        'Yüzücünün etkileyici bir fizik yapısı vardı.'),
  w(T('Spor'), 'dehydrated',      'susuz kalmış',    'sıfat', 'The player was dehydrated after the match.',    'Oyuncu maçtan sonra susuz kalmıştı.'),

  // ── Duygular (B1) ─────────────────────────────────────────────────────
  w(T('Duygular'), 'ambivalent',    'kararsız',        'sıfat', 'She felt ambivalent about the decision.',        'Karar hakkında kararsız hissetti.'),
  w(T('Duygular'), 'nostalgic',     'nostaljik',       'sıfat', 'The song made him feel nostalgic.',             'Şarkı onu nostaljik hissettirdi.'),
  w(T('Duygular'), 'empathy',       'empati',          'isim',  'Empathy is understanding others\' feelings.',   'Empati, başkalarının duygularını anlamaktır.'),
  w(T('Duygular'), 'regret',        'pişmanlık',       'isim',  'She had deep regret over her words.',           'Sözleri için derin bir pişmanlık duydu.'),
  w(T('Duygular'), 'resentment',    'kırgınlık',       'isim',  'His resentment grew over the years.',           'Kırgınlığı yıllar içinde büyüdü.'),
  w(T('Duygular'), 'contentment',   'memnuniyet',      'isim',  'She felt a deep sense of contentment.',        'Derin bir memnuniyet hissi duydu.'),
  w(T('Duygular'), 'overwhelmed',   'bunalmış',        'sıfat', 'She felt overwhelmed by the workload.',         'İş yükü karşısında bunalmış hissetti.'),
  w(T('Duygular'), 'anticipation',  'beklenti',        'isim',  'He was full of anticipation before the trip.',  'Gezi öncesi beklentiyle doluydu.'),
  w(T('Duygular'), 'longing',       'özlem',           'isim',  'She felt a longing for her hometown.',          'Memleketi için özlem duydu.'),
  w(T('Duygular'), 'apprehensive',  'kaygılı',         'sıfat', 'He was apprehensive about the interview.',      'Mülakat konusunda kaygılıydı.'),
  w(T('Duygular'), 'gratitude',     'minnettarlık',    'isim',  'She expressed her gratitude with a smile.',     'Minnettarlığını bir gülümsemeyle dile getirdi.'),
  w(T('Duygular'), 'disillusioned', 'hayal kırıklığına uğramış','sıfat','He became disillusioned with politics.','Politikadan hayal kırıklığına uğradı.'),
  w(T('Duygular'), 'humiliation',   'aşağılanma',      'isim',  'The public humiliation was hard to bear.',      'Kamuoyu önünde aşağılanmak dayanılmazdı.'),
  w(T('Duygular'), 'enthusiasm',    'coşku',           'isim',  'The students showed great enthusiasm.',         'Öğrenciler büyük coşku gösterdi.'),
  w(T('Duygular'), 'indifferent',   'ilgisiz',         'sıfat', 'She seemed indifferent to the criticism.',     'Eleştiriye ilgisiz görünüyordu.'),
  w(T('Duygular'), 'compassionate', 'merhametli',      'sıfat', 'The nurse was very compassionate.',             'Hemşire çok merhametliydi.'),
  w(T('Duygular'), 'vulnerable',    'kırılgan',        'sıfat', 'Children are vulnerable in conflict zones.',   'Çocuklar çatışma bölgelerinde kırılgandır.'),
  w(T('Duygular'), 'irritable',     'sinirli',         'sıfat', 'He becomes irritable when he is tired.',       'Yorgun olduğunda sinirli hale gelir.'),
  w(T('Duygular'), 'serene',        'huzurlu',         'sıfat', 'The lake looked serene at dawn.',               'Göl şafakta huzurlu görünüyordu.'),
  w(T('Duygular'), 'poignant',       'dokunaklı',       'sıfat', 'The farewell scene was very poignant.',         'Veda sahnesi çok dokunaklıydı.'),

  // ── Teknoloji (B1) ────────────────────────────────────────────────────
  w(T('Teknoloji'), 'algorithm',     'algoritma',       'isim',  'The algorithm sorted the data quickly.',        'Algoritma verileri hızla sıraladı.'),
  w(T('Teknoloji'), 'bandwidth',     'bant genişliği',  'isim',  'High bandwidth allows faster internet.',        'Yüksek bant genişliği daha hızlı internet sağlar.'),
  w(T('Teknoloji'), 'encryption',    'şifreleme',       'isim',  'Encryption protects your personal data.',       'Şifreleme kişisel verilerinizi korur.'),
  w(T('Teknoloji'), 'cache',         'önbellek',        'isim',  'Clear the cache to improve app performance.',   'Uygulama performansını artırmak için önbelleği temizleyin.'),
  w(T('Teknoloji'), 'server',        'sunucu',          'isim',  'The server crashed during the update.',         'Güncelleme sırasında sunucu çöktü.'),
  w(T('Teknoloji'), 'firmware',      'ürün yazılımı',   'isim',  'Update the firmware on your router.',           'Yönlendiriciinizdeki ürün yazılımını güncelleyin.'),
  w(T('Teknoloji'), 'interface',     'arayüz',          'isim',  'The user interface is easy to navigate.',       'Kullanıcı arayüzü gezinmesi kolaydır.'),
  w(T('Teknoloji'), 'cybersecurity', 'siber güvenlik',  'isim',  'Cybersecurity is a growing field.',             'Siber güvenlik büyüyen bir alandır.'),
  w(T('Teknoloji'), 'prototype',     'prototip',        'isim',  'The engineers built a prototype first.',        'Mühendisler önce bir prototip yaptı.'),
  w(T('Teknoloji'), 'autonomous',    'otonom',          'sıfat', 'Autonomous vehicles are being tested now.',     'Otonom araçlar şu anda test ediliyor.'),
  w(T('Teknoloji'), 'blockchain',    'blok zinciri',    'isim',  'Blockchain ensures secure transactions.',       'Blok zinciri güvenli işlemler sağlar.'),
  w(T('Teknoloji'), 'sensor',        'sensör',          'isim',  'The sensor detects movement in the room.',      'Sensör odadaki hareketi algılar.'),
  w(T('Teknoloji'), 'processor',     'işlemci',         'isim',  'A faster processor improves performance.',      'Daha hızlı bir işlemci performansı artırır.'),
  w(T('Teknoloji'), 'latency',       'gecikme',         'isim',  'Low latency is critical for gaming.',           'Oyun oynamak için düşük gecikme kritik öneme sahiptir.'),
  w(T('Teknoloji'), 'scalable',      'ölçeklenebilir',  'sıfat', 'The system is scalable to millions of users.', 'Sistem milyonlarca kullanıcıya ölçeklenebilir.'),
  w(T('Teknoloji'), 'interoperability','birlikte çalışabilirlik','isim','Interoperability allows different systems to communicate.','Birlikte çalışabilirlik farklı sistemlerin iletişim kurmasını sağlar.'),
  w(T('Teknoloji'), 'debugging',     'hata ayıklama',   'isim',  'Debugging code can take hours.',                'Kod hata ayıklama saatler alabilir.'),
  w(T('Teknoloji'), 'iteration',     'yineleme',        'isim',  'Each iteration improved the product.',          'Her yineleme ürünü iyileştirdi.'),
  w(T('Teknoloji'), 'deployment',    'dağıtım',         'isim',  'The app deployment was successful.',            'Uygulama dağıtımı başarılı oldu.'),
  w(T('Teknoloji'), 'virtualization','sanallaştırma',   'isim',  'Virtualization allows multiple systems on one server.','Sanallaştırma bir sunucuda birden fazla sisteme izin verir.'),
];

// ── Duplicate check ────────────────────────────────────────────────────────────
const b1Ens = b1.map(w => w.en);
const internalDups = b1Ens.filter((en, i) => b1Ens.indexOf(en) !== i);
if (internalDups.length > 0) {
  console.error('INTERNAL DUPLICATES in B1:', [...new Set(internalDups)]);
  process.exit(1);
}

const crossDups = b1Ens.filter(en => existingEns.has(en));
if (crossDups.length > 0) {
  console.error('CROSS DUPLICATES (already in words.json):', crossDups);
  process.exit(1);
}

const merged = [...existing, ...b1];
fs.writeFileSync(WORDS_PATH, JSON.stringify(merged, null, 2));
console.log(`✅ Done! Added ${b1.length} B1 words. Total: ${merged.length}`);
