const fs = require('fs');
const path = require('path');

const a2 = [
  // Selamlaşma ve Tanışma (446-465)
  {id:446,topic:'Selamlaşma ve Tanışma',en:'introduce',tr:'tanıtmak',type:'fiil',exampleEn:'Let me introduce my friend.',exampleTr:'Arkadaşımı tanıtayım.'},
  {id:447,topic:'Selamlaşma ve Tanışma',en:'conversation',tr:'sohbet',type:'isim',exampleEn:'We had a great conversation.',exampleTr:'Harika bir sohbet ettik.'},
  {id:448,topic:'Selamlaşma ve Tanışma',en:'invitation',tr:'davet',type:'isim',exampleEn:'Thank you for the invitation.',exampleTr:'Davet için teşekkürler.'},
  {id:449,topic:'Selamlaşma ve Tanışma',en:'nationality',tr:'milliyet',type:'isim',exampleEn:'What is your nationality?',exampleTr:'Milliyetin ne?'},
  {id:450,topic:'Selamlaşma ve Tanışma',en:'language',tr:'dil',type:'isim',exampleEn:'English is an important language.',exampleTr:'İngilizce önemli bir dildir.'},
  {id:451,topic:'Selamlaşma ve Tanışma',en:'repeat',tr:'tekrarlamak',type:'fiil',exampleEn:'Can you repeat that please?',exampleTr:'Lütfen tekrar eder misiniz?'},
  {id:452,topic:'Selamlaşma ve Tanışma',en:'polite',tr:'nazik',type:'sıfat',exampleEn:'She is always very polite.',exampleTr:'O her zaman çok naziktir.'},
  {id:453,topic:'Selamlaşma ve Tanışma',en:'formal',tr:'resmi',type:'sıfat',exampleEn:'This is a formal meeting.',exampleTr:'Bu resmi bir toplantıdır.'},
  {id:454,topic:'Selamlaşma ve Tanışma',en:'casual',tr:'gündelik',type:'sıfat',exampleEn:'Wear casual clothes today.',exampleTr:'Bugün gündelik kıyafet giy.'},
  {id:455,topic:'Selamlaşma ve Tanışma',en:'surname',tr:'soyadı',type:'isim',exampleEn:'What is your surname?',exampleTr:'Soyadın ne?'},
  {id:456,topic:'Selamlaşma ve Tanışma',en:'origin',tr:'köken',type:'isim',exampleEn:'What is your country of origin?',exampleTr:'Köken ülken neresi?'},
  {id:457,topic:'Selamlaşma ve Tanışma',en:'abroad',tr:'yurt dışı',type:'zarf',exampleEn:'She studied abroad for a year.',exampleTr:'Bir yıl yurt dışında okudu.'},
  {id:458,topic:'Selamlaşma ve Tanışma',en:'phrase',tr:'deyim',type:'isim',exampleEn:'Learn useful phrases in English.',exampleTr:'İngilizce faydalı deyimler öğren.'},
  {id:459,topic:'Selamlaşma ve Tanışma',en:'accent',tr:'aksan',type:'isim',exampleEn:'He has a strong British accent.',exampleTr:'Güçlü bir İngiliz aksanı var.'},
  {id:460,topic:'Selamlaşma ve Tanışma',en:'respond',tr:'yanıt vermek',type:'fiil',exampleEn:'Please respond to my message.',exampleTr:'Mesajıma yanıt ver lütfen.'},
  {id:461,topic:'Selamlaşma ve Tanışma',en:'greet',tr:'selamlamak',type:'fiil',exampleEn:'He greeted everyone with a smile.',exampleTr:'Herkesi gülümseyerek selamladı.'},
  {id:462,topic:'Selamlaşma ve Tanışma',en:'culture',tr:'kültür',type:'isim',exampleEn:'Every country has its own culture.',exampleTr:'Her ülkenin kendine özgü kültürü var.'},
  {id:463,topic:'Selamlaşma ve Tanışma',en:'gesture',tr:'jest',type:'isim',exampleEn:'A handshake is a common gesture.',exampleTr:'El sıkışma yaygın bir jesttir.'},
  {id:464,topic:'Selamlaşma ve Tanışma',en:'fluent',tr:'akıcı',type:'sıfat',exampleEn:'She is fluent in three languages.',exampleTr:'Üç dilde akıcı konuşuyor.'},
  {id:465,topic:'Selamlaşma ve Tanışma',en:'translate',tr:'çevirmek',type:'fiil',exampleEn:'Can you translate this sentence?',exampleTr:'Bu cümleyi çevirebilir misin?'},

  // Sayılar (466-485)
  {id:466,topic:'Sayılar',en:'zero',tr:'sıfır',type:'isim',exampleEn:'The temperature is zero degrees.',exampleTr:'Sıcaklık sıfır derece.'},
  {id:467,topic:'Sayılar',en:'million',tr:'milyon',type:'isim',exampleEn:'One million people live here.',exampleTr:'Burada bir milyon insan yaşıyor.'},
  {id:468,topic:'Sayılar',en:'billion',tr:'milyar',type:'isim',exampleEn:'The world has eight billion people.',exampleTr:'Dünyada sekiz milyar insan var.'},
  {id:469,topic:'Sayılar',en:'first',tr:'birinci',type:'sıfat',exampleEn:'She finished first in the race.',exampleTr:'Yarışta birinci oldu.'},
  {id:470,topic:'Sayılar',en:'third',tr:'üçüncü',type:'sıfat',exampleEn:'He lives on the third floor.',exampleTr:'Üçüncü katta oturuyor.'},
  {id:471,topic:'Sayılar',en:'half',tr:'yarım',type:'isim',exampleEn:'I ate half of the pizza.',exampleTr:'Pizzanın yarısını yedim.'},
  {id:472,topic:'Sayılar',en:'quarter',tr:'çeyrek',type:'isim',exampleEn:'It is a quarter past three.',exampleTr:'Saat üçü çeyrek geçiyor.'},
  {id:473,topic:'Sayılar',en:'double',tr:'iki katı',type:'sıfat',exampleEn:'She earns double my salary.',exampleTr:'Maaşımın iki katını kazanıyor.'},
  {id:474,topic:'Sayılar',en:'triple',tr:'üç katı',type:'sıfat',exampleEn:'The price is triple what it was.',exampleTr:'Fiyat eskisinin üç katı.'},
  {id:475,topic:'Sayılar',en:'plus',tr:'artı',type:'isim',exampleEn:'Five plus three equals eight.',exampleTr:'Beş artı üç sekiz eder.'},
  {id:476,topic:'Sayılar',en:'minus',tr:'eksi',type:'isim',exampleEn:'Ten minus four equals six.',exampleTr:'On eksi dört altı eder.'},
  {id:477,topic:'Sayılar',en:'multiply',tr:'çarpmak',type:'fiil',exampleEn:'Multiply five by four.',exampleTr:'Beşi dörtle çarp.'},
  {id:478,topic:'Sayılar',en:'divide',tr:'bölmek',type:'fiil',exampleEn:'Divide twelve by three.',exampleTr:'On ikiyi üçe böl.'},
  {id:479,topic:'Sayılar',en:'average',tr:'ortalama',type:'isim',exampleEn:'The average score is seventy.',exampleTr:'Ortalama puan yetmiş.'},
  {id:480,topic:'Sayılar',en:'percent',tr:'yüzde',type:'isim',exampleEn:'Fifty percent of students passed.',exampleTr:'Öğrencilerin yüzde ellisi geçti.'},
  {id:481,topic:'Sayılar',en:'fraction',tr:'kesir',type:'isim',exampleEn:'One third is a fraction.',exampleTr:'Üçte bir bir kesirdir.'},
  {id:482,topic:'Sayılar',en:'calculate',tr:'hesaplamak',type:'fiil',exampleEn:'Calculate the total price.',exampleTr:'Toplam fiyatı hesapla.'},
  {id:483,topic:'Sayılar',en:'equal',tr:'eşit',type:'sıfat',exampleEn:'Both sides are equal.',exampleTr:'Her iki taraf da eşittir.'},
  {id:484,topic:'Sayılar',en:'sum',tr:'toplam',type:'isim',exampleEn:'What is the sum of these numbers?',exampleTr:'Bu sayıların toplamı nedir?'},
  {id:485,topic:'Sayılar',en:'measure',tr:'ölçmek',type:'fiil',exampleEn:'Measure the length of the room.',exampleTr:'Odanın uzunluğunu ölç.'},

  // Renkler (486-505)
  {id:486,topic:'Renkler',en:'silver',tr:'gümüş rengi',type:'sıfat',exampleEn:'She has a silver necklace.',exampleTr:'Gümüş renkli bir kolyesi var.'},
  {id:487,topic:'Renkler',en:'gold',tr:'altın rengi',type:'sıfat',exampleEn:'The medal is gold.',exampleTr:'Madalya altın renginde.'},
  {id:488,topic:'Renkler',en:'navy',tr:'lacivert',type:'sıfat',exampleEn:'He wore a navy blue jacket.',exampleTr:'Lacivert bir ceket giydi.'},
  {id:489,topic:'Renkler',en:'cream',tr:'krem rengi',type:'sıfat',exampleEn:'The walls are cream coloured.',exampleTr:'Duvarlar krem renginde.'},
  {id:490,topic:'Renkler',en:'beige',tr:'bej',type:'sıfat',exampleEn:'She is wearing beige trousers.',exampleTr:'Bej pantolon giyiyor.'},
  {id:491,topic:'Renkler',en:'turquoise',tr:'turkuaz',type:'sıfat',exampleEn:'The sea looks turquoise today.',exampleTr:'Deniz bugün turkuaz görünüyor.'},
  {id:492,topic:'Renkler',en:'coral',tr:'mercan rengi',type:'sıfat',exampleEn:'She bought a coral dress.',exampleTr:'Mercan renkli bir elbise aldı.'},
  {id:493,topic:'Renkler',en:'lime',tr:'limon yeşili',type:'sıfat',exampleEn:'He wore a lime green shirt.',exampleTr:'Limon yeşili gömlek giydi.'},
  {id:494,topic:'Renkler',en:'indigo',tr:'çivit mavisi',type:'sıfat',exampleEn:'The sky turned indigo at dusk.',exampleTr:'Alacakaranlıkta gökyüzü çivit mavisine döndü.'},
  {id:495,topic:'Renkler',en:'teal',tr:'zümrüt yeşili',type:'sıfat',exampleEn:'She painted the door teal.',exampleTr:'Kapıyı zümrüt yeşiline boyadı.'},
  {id:496,topic:'Renkler',en:'magenta',tr:'magenta',type:'sıfat',exampleEn:'The flower is bright magenta.',exampleTr:'Çiçek parlak magenta renginde.'},
  {id:497,topic:'Renkler',en:'scarlet',tr:'kıpkırmızı',type:'sıfat',exampleEn:'She wore a scarlet coat.',exampleTr:'Kıpkırmızı bir palto giyiyordu.'},
  {id:498,topic:'Renkler',en:'ivory',tr:'fildişi rengi',type:'sıfat',exampleEn:'The wedding dress is ivory white.',exampleTr:'Gelinlik fildişi beyazı renkte.'},
  {id:499,topic:'Renkler',en:'maroon',tr:'bordo',type:'sıfat',exampleEn:'He drives a maroon car.',exampleTr:'Bordo bir araba kullanıyor.'},
  {id:500,topic:'Renkler',en:'olive',tr:'zeytin yeşili',type:'sıfat',exampleEn:'He wore an olive green jacket.',exampleTr:'Zeytin yeşili ceket giydi.'},
  {id:501,topic:'Renkler',en:'pastel',tr:'pastel',type:'sıfat',exampleEn:'The room has pastel colours.',exampleTr:'Odanın pastel renkleri var.'},
  {id:502,topic:'Renkler',en:'shade',tr:'ton',type:'isim',exampleEn:'Choose a darker shade of blue.',exampleTr:'Daha koyu bir mavi tonu seç.'},
  {id:503,topic:'Renkler',en:'tint',tr:'açık ton',type:'isim',exampleEn:'Add a tint of yellow to white.',exampleTr:'Beyaza biraz sarı tonu ekle.'},
  {id:504,topic:'Renkler',en:'pattern',tr:'desen',type:'isim',exampleEn:'I like the pattern on this fabric.',exampleTr:'Bu kumaştaki deseni seviyorum.'},
  {id:505,topic:'Renkler',en:'stripe',tr:'çizgi',type:'isim',exampleEn:'The shirt has red and white stripes.',exampleTr:'Gömleğin kırmızı ve beyaz çizgileri var.'},

  // Aile (506-525)
  {id:506,topic:'Aile',en:'twin',tr:'ikiz',type:'isim',exampleEn:'She has a twin brother.',exampleTr:'Bir ikiz erkek kardeşi var.'},
  {id:507,topic:'Aile',en:'nephew',tr:'erkek yeğen',type:'isim',exampleEn:'My nephew is five years old.',exampleTr:'Erkek yeğenim beş yaşında.'},
  {id:508,topic:'Aile',en:'niece',tr:'kız yeğen',type:'isim',exampleEn:'My niece loves to dance.',exampleTr:'Kız yeğenim dans etmeyi seviyor.'},
  {id:509,topic:'Aile',en:'relative',tr:'akraba',type:'isim',exampleEn:'We visited our relatives.',exampleTr:'Akrabalarımızı ziyaret ettik.'},
  {id:510,topic:'Aile',en:'stepmother',tr:'üvey anne',type:'isim',exampleEn:'His stepmother is very kind.',exampleTr:'Üvey annesi çok nazik.'},
  {id:511,topic:'Aile',en:'stepfather',tr:'üvey baba',type:'isim',exampleEn:'Her stepfather helps with homework.',exampleTr:'Üvey babası ödevlerde yardım eder.'},
  {id:512,topic:'Aile',en:'generation',tr:'nesil',type:'isim',exampleEn:'Each generation is different.',exampleTr:'Her nesil farklıdır.'},
  {id:513,topic:'Aile',en:'birth',tr:'doğum',type:'isim',exampleEn:'The birth of a baby is special.',exampleTr:'Bir bebeğin doğumu özeldir.'},
  {id:514,topic:'Aile',en:'adult',tr:'yetişkin',type:'isim',exampleEn:'Only adults can enter this place.',exampleTr:'Buraya sadece yetişkinler girebilir.'},
  {id:515,topic:'Aile',en:'teenager',tr:'ergen',type:'isim',exampleEn:'My sister is a teenager now.',exampleTr:'Kız kardeşim artık ergen.'},
  {id:516,topic:'Aile',en:'toddler',tr:'yürümeye başlayan çocuk',type:'isim',exampleEn:'The toddler learned to walk.',exampleTr:'Yürümeye başlayan çocuk yürümeyi öğrendi.'},
  {id:517,topic:'Aile',en:'married',tr:'evli',type:'sıfat',exampleEn:'They got married last year.',exampleTr:'Geçen yıl evlendiler.'},
  {id:518,topic:'Aile',en:'divorced',tr:'boşanmış',type:'sıfat',exampleEn:'Her parents are divorced.',exampleTr:'Ebeveynleri boşanmış.'},
  {id:519,topic:'Aile',en:'widow',tr:'dul',type:'isim',exampleEn:'She became a widow last year.',exampleTr:'Geçen yıl dul kaldı.'},
  {id:520,topic:'Aile',en:'relationship',tr:'ilişki',type:'isim',exampleEn:'They have a good relationship.',exampleTr:'İyi bir ilişkileri var.'},
  {id:521,topic:'Aile',en:'household',tr:'hane',type:'isim',exampleEn:'Four people live in this household.',exampleTr:'Bu hanede dört kişi yaşıyor.'},
  {id:522,topic:'Aile',en:'grandchild',tr:'torun',type:'isim',exampleEn:'She has three grandchildren.',exampleTr:'Üç torunu var.'},
  {id:523,topic:'Aile',en:'sibling',tr:'kardeş',type:'isim',exampleEn:'I have two siblings.',exampleTr:'İki kardeşim var.'},
  {id:524,topic:'Aile',en:'partner',tr:'eş',type:'isim',exampleEn:'My partner and I cook together.',exampleTr:'Eşim ve ben birlikte yemek yapıyoruz.'},
  {id:525,topic:'Aile',en:'adopt',tr:'evlat edinmek',type:'fiil',exampleEn:'They decided to adopt a child.',exampleTr:'Bir çocuk evlat edinmeye karar verdiler.'},

  // Vücut (526-545)
  {id:526,topic:'Vücut',en:'thumb',tr:'başparmak',type:'isim',exampleEn:'She hurt her thumb.',exampleTr:'Başparmağını incitti.'},
  {id:527,topic:'Vücut',en:'palm',tr:'avuç içi',type:'isim',exampleEn:'She held the coin in her palm.',exampleTr:'Parayı avuç içinde tuttu.'},
  {id:528,topic:'Vücut',en:'wrist',tr:'bilek',type:'isim',exampleEn:'She wears a watch on her wrist.',exampleTr:'Bileğinde saat takıyor.'},
  {id:529,topic:'Vücut',en:'ankle',tr:'ayak bileği',type:'isim',exampleEn:'He twisted his ankle.',exampleTr:'Ayak bileğini burdu.'},
  {id:530,topic:'Vücut',en:'heel',tr:'topuk',type:'isim',exampleEn:'My heel hurts after walking.',exampleTr:'Yürüdükten sonra topuğum ağrıyor.'},
  {id:531,topic:'Vücut',en:'toe',tr:'ayak parmağı',type:'isim',exampleEn:'He stubbed his toe on the chair.',exampleTr:'Ayak parmağını sandalyeye çarptı.'},
  {id:532,topic:'Vücut',en:'chin',tr:'çene',type:'isim',exampleEn:'He has a small chin.',exampleTr:'Küçük bir çenesi var.'},
  {id:533,topic:'Vücut',en:'cheek',tr:'yanak',type:'isim',exampleEn:'She kissed her baby on the cheek.',exampleTr:'Bebeğini yanağından öptü.'},
  {id:534,topic:'Vücut',en:'jaw',tr:'alt çene',type:'isim',exampleEn:'He broke his jaw in an accident.',exampleTr:'Kazada alt çenesini kırdı.'},
  {id:535,topic:'Vücut',en:'brow',tr:'kaş',type:'isim',exampleEn:'She raised her brow in surprise.',exampleTr:'Şaşkınlıkla kaşını kaldırdı.'},
  {id:536,topic:'Vücut',en:'lip',tr:'dudak',type:'isim',exampleEn:'She put lipstick on her lips.',exampleTr:'Dudaklarına ruj sürdü.'},
  {id:537,topic:'Vücut',en:'tongue',tr:'dil',type:'isim',exampleEn:'He burnt his tongue on hot soup.',exampleTr:'Sıcak çorbada dilini yaktı.'},
  {id:538,topic:'Vücut',en:'throat',tr:'boğaz',type:'isim',exampleEn:'I have a sore throat today.',exampleTr:'Bugün boğazım ağrıyor.'},
  {id:539,topic:'Vücut',en:'chest',tr:'göğüs',type:'isim',exampleEn:'He has chest pain.',exampleTr:'Göğüs ağrısı var.'},
  {id:540,topic:'Vücut',en:'hip',tr:'kalça',type:'isim',exampleEn:'She broke her hip in a fall.',exampleTr:'Düşünce kalçasını kırdı.'},
  {id:541,topic:'Vücut',en:'elbow',tr:'dirsek',type:'isim',exampleEn:'He hit his elbow on the table.',exampleTr:'Dirseğini masaya çarptı.'},
  {id:542,topic:'Vücut',en:'fist',tr:'yumruk',type:'isim',exampleEn:'He raised his fist in the air.',exampleTr:'Yumruğunu havaya kaldırdı.'},
  {id:543,topic:'Vücut',en:'nail',tr:'tırnak',type:'isim',exampleEn:'She painted her nails red.',exampleTr:'Tırnaklarını kırmızıya boyadı.'},
  {id:544,topic:'Vücut',en:'skin',tr:'cilt',type:'isim',exampleEn:'Her skin is very soft.',exampleTr:'Cildi çok yumuşak.'},
  {id:545,topic:'Vücut',en:'bone',tr:'kemik',type:'isim',exampleEn:'He broke a bone in his hand.',exampleTr:'Elinde bir kemik kırdı.'},

  // Yiyecekler (546-565)
  {id:546,topic:'Yiyecekler',en:'pasta',tr:'makarna',type:'isim',exampleEn:'I cook pasta every week.',exampleTr:'Her hafta makarna pişiriyorum.'},
  {id:547,topic:'Yiyecekler',en:'sandwich',tr:'sandviç',type:'isim',exampleEn:'I ate a cheese sandwich.',exampleTr:'Peynirli sandviç yedim.'},
  {id:548,topic:'Yiyecekler',en:'pizza',tr:'pizza',type:'isim',exampleEn:'We ordered a pizza last night.',exampleTr:'Dün gece pizza sipariş ettik.'},
  {id:549,topic:'Yiyecekler',en:'burger',tr:'hamburger',type:'isim',exampleEn:'He loves eating burgers.',exampleTr:'Hamburger yemeyi çok seviyor.'},
  {id:550,topic:'Yiyecekler',en:'mushroom',tr:'mantar',type:'isim',exampleEn:'She added mushrooms to the soup.',exampleTr:'Çorbaya mantar ekledi.'},
  {id:551,topic:'Yiyecekler',en:'carrot',tr:'havuç',type:'isim',exampleEn:'Carrots are good for your eyes.',exampleTr:'Havuç gözler için iyidir.'},
  {id:552,topic:'Yiyecekler',en:'onion',tr:'soğan',type:'isim',exampleEn:'Cut the onion into small pieces.',exampleTr:'Soğanı küçük parçalara kes.'},
  {id:553,topic:'Yiyecekler',en:'pepper',tr:'biber',type:'isim',exampleEn:'Add pepper to the salad.',exampleTr:'Salataya biber ekle.'},
  {id:554,topic:'Yiyecekler',en:'lemon',tr:'limon',type:'isim',exampleEn:'I drink lemon juice every morning.',exampleTr:'Her sabah limon suyu içiyorum.'},
  {id:555,topic:'Yiyecekler',en:'garlic',tr:'sarımsak',type:'isim',exampleEn:'Garlic gives food a strong flavour.',exampleTr:'Sarımsak yemeklere güçlü bir tat verir.'},
  {id:556,topic:'Yiyecekler',en:'strawberry',tr:'çilek',type:'isim',exampleEn:'Strawberries are my favourite fruit.',exampleTr:'Çilek en sevdiğim meyvedir.'},
  {id:557,topic:'Yiyecekler',en:'grape',tr:'üzüm',type:'isim',exampleEn:'I bought a bunch of grapes.',exampleTr:'Bir salkım üzüm aldım.'},
  {id:558,topic:'Yiyecekler',en:'watermelon',tr:'karpuz',type:'isim',exampleEn:'We eat watermelon in summer.',exampleTr:'Yazın karpuz yeriz.'},
  {id:559,topic:'Yiyecekler',en:'pear',tr:'armut',type:'isim',exampleEn:'The pear is sweet and juicy.',exampleTr:'Armut tatlı ve sulu.'},
  {id:560,topic:'Yiyecekler',en:'pineapple',tr:'ananas',type:'isim',exampleEn:'She put pineapple on the pizza.',exampleTr:'Pizzaya ananas koydu.'},
  {id:561,topic:'Yiyecekler',en:'yogurt',tr:'yoğurt',type:'isim',exampleEn:'I eat yogurt for breakfast.',exampleTr:'Kahvaltıda yoğurt yerim.'},
  {id:562,topic:'Yiyecekler',en:'sauce',tr:'sos',type:'isim',exampleEn:'She made a tomato sauce.',exampleTr:'Domates sosu yaptı.'},
  {id:563,topic:'Yiyecekler',en:'spice',tr:'baharat',type:'isim',exampleEn:'Add some spice to the dish.',exampleTr:'Yemeğe biraz baharat ekle.'},
  {id:564,topic:'Yiyecekler',en:'meal',tr:'öğün',type:'isim',exampleEn:'Dinner is my favourite meal.',exampleTr:'Akşam yemeği en sevdiğim öğün.'},
  {id:565,topic:'Yiyecekler',en:'portion',tr:'porsiyon',type:'isim',exampleEn:'The portion was very large.',exampleTr:'Porsiyon çok büyüktü.'},

  // Giyim (566-585)
  {id:566,topic:'Giyim',en:'suit',tr:'takım elbise',type:'isim',exampleEn:'He wore a suit to the interview.',exampleTr:'Mülakata takım elbise giydi.'},
  {id:567,topic:'Giyim',en:'tie',tr:'kravat',type:'isim',exampleEn:'He always wears a tie to work.',exampleTr:'İşe her zaman kravat takar.'},
  {id:568,topic:'Giyim',en:'belt',tr:'kemer',type:'isim',exampleEn:'He tightened his belt.',exampleTr:'Kemerini sıktı.'},
  {id:569,topic:'Giyim',en:'pocket',tr:'cep',type:'isim',exampleEn:'I keep my keys in my pocket.',exampleTr:'Anahtarlarımı cebimde tutuyorum.'},
  {id:570,topic:'Giyim',en:'button',tr:'düğme',type:'isim',exampleEn:'A button fell off his shirt.',exampleTr:'Gömleğinden bir düğme düştü.'},
  {id:571,topic:'Giyim',en:'zip',tr:'fermuar',type:'isim',exampleEn:'The zip on my jacket is broken.',exampleTr:'Ceketimin fermuarı bozuk.'},
  {id:572,topic:'Giyim',en:'sleeve',tr:'kol',type:'isim',exampleEn:'She rolled up her sleeves.',exampleTr:'Kollarını sıvadı.'},
  {id:573,topic:'Giyim',en:'collar',tr:'yaka',type:'isim',exampleEn:'He turned up his collar.',exampleTr:'Yakasını kaldırdı.'},
  {id:574,topic:'Giyim',en:'hood',tr:'kapüşon',type:'isim',exampleEn:'She pulled up her hood.',exampleTr:'Kapüşonunu çekti.'},
  {id:575,topic:'Giyim',en:'shorts',tr:'şort',type:'isim',exampleEn:'He wore shorts in the summer.',exampleTr:'Yazın şort giydi.'},
  {id:576,topic:'Giyim',en:'swimsuit',tr:'mayo',type:'isim',exampleEn:'She bought a new swimsuit.',exampleTr:'Yeni bir mayo aldı.'},
  {id:577,topic:'Giyim',en:'jeans',tr:'kot pantolon',type:'isim',exampleEn:'He wears jeans every day.',exampleTr:'Her gün kot pantolon giyiyor.'},
  {id:578,topic:'Giyim',en:'vest',tr:'yelek',type:'isim',exampleEn:'She wore a vest under her shirt.',exampleTr:'Gömleğinin altına yelek giydi.'},
  {id:579,topic:'Giyim',en:'cardigan',tr:'hırka',type:'isim',exampleEn:'She put on a warm cardigan.',exampleTr:'Sıcak bir hırka giydi.'},
  {id:580,topic:'Giyim',en:'blouse',tr:'bluz',type:'isim',exampleEn:'She wore a floral blouse.',exampleTr:'Çiçekli bir bluz giydi.'},
  {id:581,topic:'Giyim',en:'sandals',tr:'sandalet',type:'isim',exampleEn:'She wore sandals on the beach.',exampleTr:'Plajda sandalet giydi.'},
  {id:582,topic:'Giyim',en:'sneakers',tr:'spor ayakkabı',type:'isim',exampleEn:'He bought new sneakers.',exampleTr:'Yeni spor ayakkabı aldı.'},
  {id:583,topic:'Giyim',en:'fabric',tr:'kumaş',type:'isim',exampleEn:'This fabric is very soft.',exampleTr:'Bu kumaş çok yumuşak.'},
  {id:584,topic:'Giyim',en:'fashion',tr:'moda',type:'isim',exampleEn:'She works in the fashion industry.',exampleTr:'Moda sektöründe çalışıyor.'},
  {id:585,topic:'Giyim',en:'style',tr:'stil',type:'isim',exampleEn:'She has her own unique style.',exampleTr:'Kendine özgü bir stili var.'},

  // Ev ve Mobilya (586-605)
  {id:586,topic:'Ev ve Mobilya',en:'shelf',tr:'raf',type:'isim',exampleEn:'The books are on the shelf.',exampleTr:'Kitaplar rafta.'},
  {id:587,topic:'Ev ve Mobilya',en:'mirror',tr:'ayna',type:'isim',exampleEn:'She looked in the mirror.',exampleTr:'Aynaya baktı.'},
  {id:588,topic:'Ev ve Mobilya',en:'carpet',tr:'halı',type:'isim',exampleEn:'The carpet is very soft.',exampleTr:'Halı çok yumuşak.'},
  {id:589,topic:'Ev ve Mobilya',en:'curtain',tr:'perde',type:'isim',exampleEn:'Open the curtains to let in light.',exampleTr:'Işık girmesi için perdeleri aç.'},
  {id:590,topic:'Ev ve Mobilya',en:'pillow',tr:'yastık',type:'isim',exampleEn:'I need a new pillow.',exampleTr:'Yeni bir yastığa ihtiyacım var.'},
  {id:591,topic:'Ev ve Mobilya',en:'blanket',tr:'battaniye',type:'isim',exampleEn:'She put a blanket on the baby.',exampleTr:'Bebeğin üstüne battaniye örttü.'},
  {id:592,topic:'Ev ve Mobilya',en:'shower',tr:'duş',type:'isim',exampleEn:'I take a shower every morning.',exampleTr:'Her sabah duş alıyorum.'},
  {id:593,topic:'Ev ve Mobilya',en:'toilet',tr:'tuvalet',type:'isim',exampleEn:'The toilet is on the left.',exampleTr:'Tuvalet solda.'},
  {id:594,topic:'Ev ve Mobilya',en:'sink',tr:'lavabo',type:'isim',exampleEn:'Wash your hands in the sink.',exampleTr:'Ellerini lavaboda yıka.'},
  {id:595,topic:'Ev ve Mobilya',en:'tap',tr:'musluk',type:'isim',exampleEn:'Turn off the tap after use.',exampleTr:'Kullandıktan sonra musluğu kapat.'},
  {id:596,topic:'Ev ve Mobilya',en:'wardrobe',tr:'gardırop',type:'isim',exampleEn:'Her clothes are in the wardrobe.',exampleTr:'Kıyafetleri gardıropta.'},
  {id:597,topic:'Ev ve Mobilya',en:'drawer',tr:'çekmece',type:'isim',exampleEn:'Put the spoons in the drawer.',exampleTr:'Kaşıkları çekmeceye koy.'},
  {id:598,topic:'Ev ve Mobilya',en:'ceiling',tr:'tavan',type:'isim',exampleEn:'The ceiling is very high.',exampleTr:'Tavan çok yüksek.'},
  {id:599,topic:'Ev ve Mobilya',en:'balcony',tr:'balkon',type:'isim',exampleEn:'We had breakfast on the balcony.',exampleTr:'Balkonda kahvaltı ettik.'},
  {id:600,topic:'Ev ve Mobilya',en:'garage',tr:'garaj',type:'isim',exampleEn:'He parked his car in the garage.',exampleTr:'Arabasını garaja park etti.'},
  {id:601,topic:'Ev ve Mobilya',en:'basement',tr:'bodrum kat',type:'isim',exampleEn:'The washing machine is in the basement.',exampleTr:'Çamaşır makinesi bodrum katta.'},
  {id:602,topic:'Ev ve Mobilya',en:'attic',tr:'çatı katı',type:'isim',exampleEn:'Old boxes are stored in the attic.',exampleTr:'Eski kutular çatı katında saklanır.'},
  {id:603,topic:'Ev ve Mobilya',en:'hallway',tr:'koridor',type:'isim',exampleEn:'The shoes are in the hallway.',exampleTr:'Ayakkabılar koridorda.'},
  {id:604,topic:'Ev ve Mobilya',en:'furniture',tr:'mobilya',type:'isim',exampleEn:'We bought new furniture for the living room.',exampleTr:'Oturma odası için yeni mobilya aldık.'},
  {id:605,topic:'Ev ve Mobilya',en:'apartment',tr:'daire',type:'isim',exampleEn:'She lives in a small apartment.',exampleTr:'Küçük bir dairede yaşıyor.'},

  // Hayvanlar (606-625)
  {id:606,topic:'Hayvanlar',en:'wolf',tr:'kurt',type:'isim',exampleEn:'The wolf howled at the moon.',exampleTr:'Kurt aya uluyordu.'},
  {id:607,topic:'Hayvanlar',en:'tiger',tr:'kaplan',type:'isim',exampleEn:'The tiger is a powerful animal.',exampleTr:'Kaplan güçlü bir hayvandır.'},
  {id:608,topic:'Hayvanlar',en:'deer',tr:'geyik',type:'isim',exampleEn:'A deer ran across the road.',exampleTr:'Bir geyik yoldan geçti.'},
  {id:609,topic:'Hayvanlar',en:'fox',tr:'tilki',type:'isim',exampleEn:'The fox is a clever animal.',exampleTr:'Tilki zeki bir hayvandır.'},
  {id:610,topic:'Hayvanlar',en:'squirrel',tr:'sincap',type:'isim',exampleEn:'The squirrel collected nuts.',exampleTr:'Sincap fındık topladı.'},
  {id:611,topic:'Hayvanlar',en:'parrot',tr:'papağan',type:'isim',exampleEn:'The parrot can copy words.',exampleTr:'Papağan kelimeleri taklit edebilir.'},
  {id:612,topic:'Hayvanlar',en:'dolphin',tr:'yunus',type:'isim',exampleEn:'Dolphins are very intelligent.',exampleTr:'Yunuslar çok zekidir.'},
  {id:613,topic:'Hayvanlar',en:'crocodile',tr:'timsah',type:'isim',exampleEn:'The crocodile lives near water.',exampleTr:'Timsah suyun yakınında yaşar.'},
  {id:614,topic:'Hayvanlar',en:'penguin',tr:'penguen',type:'isim',exampleEn:'Penguins live in Antarctica.',exampleTr:'Penguenler Antarktika da yaşar.'},
  {id:615,topic:'Hayvanlar',en:'owl',tr:'baykuş',type:'isim',exampleEn:'The owl sleeps during the day.',exampleTr:'Baykuş gündüzleri uyur.'},
  {id:616,topic:'Hayvanlar',en:'goat',tr:'keçi',type:'isim',exampleEn:'The goat climbed the mountain.',exampleTr:'Keçi dağa tırmandı.'},
  {id:617,topic:'Hayvanlar',en:'donkey',tr:'eşek',type:'isim',exampleEn:'The donkey carried heavy bags.',exampleTr:'Eşek ağır çantalar taşıdı.'},
  {id:618,topic:'Hayvanlar',en:'camel',tr:'deve',type:'isim',exampleEn:'Camels live in the desert.',exampleTr:'Develer çölde yaşar.'},
  {id:619,topic:'Hayvanlar',en:'eagle',tr:'kartal',type:'isim',exampleEn:'The eagle flew high in the sky.',exampleTr:'Kartal gökyüzünde yüksekte uçtu.'},
  {id:620,topic:'Hayvanlar',en:'bat',tr:'yarasa',type:'isim',exampleEn:'Bats fly at night.',exampleTr:'Yarasalar geceleri uçar.'},
  {id:621,topic:'Hayvanlar',en:'shark',tr:'köpekbalığı',type:'isim',exampleEn:'The shark swam near the shore.',exampleTr:'Köpekbalığı kıyıya yakın yüzdü.'},
  {id:622,topic:'Hayvanlar',en:'lobster',tr:'ıstakoz',type:'isim',exampleEn:'Lobster is an expensive seafood.',exampleTr:'Istakoz pahalı bir deniz ürünüdür.'},
  {id:623,topic:'Hayvanlar',en:'butterfly',tr:'kelebek',type:'isim',exampleEn:'A butterfly landed on the flower.',exampleTr:'Bir kelebek çiçeğe kondu.'},
  {id:624,topic:'Hayvanlar',en:'ant',tr:'karınca',type:'isim',exampleEn:'Ants live in large groups.',exampleTr:'Karıncalar büyük gruplar halinde yaşar.'},
  {id:625,topic:'Hayvanlar',en:'worm',tr:'solucan',type:'isim',exampleEn:'Birds eat worms.',exampleTr:'Kuşlar solucan yer.'},

  // Günlük Fiiller (626-645)
  {id:626,topic:'Günlük Fiiller',en:'clean',tr:'temizlemek',type:'fiil',exampleEn:'I clean my room every week.',exampleTr:'Her hafta odamı temizlerim.'},
  {id:627,topic:'Günlük Fiiller',en:'wash',tr:'yıkamak',type:'fiil',exampleEn:'Wash your hands before eating.',exampleTr:'Yemekten önce ellerini yıka.'},
  {id:628,topic:'Günlük Fiiller',en:'buy',tr:'satın almak',type:'fiil',exampleEn:'I need to buy some groceries.',exampleTr:'Biraz market alışverişi yapmam gerek.'},
  {id:629,topic:'Günlük Fiiller',en:'carry',tr:'taşımak',type:'fiil',exampleEn:'Can you carry this box for me?',exampleTr:'Bu kutuyu benim için taşır mısın?'},
  {id:630,topic:'Günlük Fiiller',en:'bring',tr:'getirmek',type:'fiil',exampleEn:'Please bring me a glass of water.',exampleTr:'Lütfen bana bir bardak su getir.'},
  {id:631,topic:'Günlük Fiiller',en:'send',tr:'göndermek',type:'fiil',exampleEn:'I will send you a message.',exampleTr:'Sana bir mesaj göndereceğim.'},
  {id:632,topic:'Günlük Fiiller',en:'show',tr:'göstermek',type:'fiil',exampleEn:'Show me how to do this.',exampleTr:'Bunu nasıl yapacağımı göster.'},
  {id:633,topic:'Günlük Fiiller',en:'find',tr:'bulmak',type:'fiil',exampleEn:'I cannot find my keys.',exampleTr:'Anahtarlarımı bulamıyorum.'},
  {id:634,topic:'Günlük Fiiller',en:'return',tr:'geri dönmek',type:'fiil',exampleEn:'I will return home at seven.',exampleTr:'Eve yedide geri döneceğim.'},
  {id:635,topic:'Günlük Fiiller',en:'break',tr:'kırmak',type:'fiil',exampleEn:'Be careful not to break the glass.',exampleTr:'Bardağı kırmamaya dikkat et.'},
  {id:636,topic:'Günlük Fiiller',en:'fix',tr:'tamir etmek',type:'fiil',exampleEn:'Can you fix this broken chair?',exampleTr:'Bu kırık sandalyeyi tamir edebilir misin?'},
  {id:637,topic:'Günlük Fiiller',en:'start',tr:'başlamak',type:'fiil',exampleEn:'The class starts at nine.',exampleTr:'Ders dokuzda başlıyor.'},
  {id:638,topic:'Günlük Fiiller',en:'finish',tr:'bitirmek',type:'fiil',exampleEn:'I will finish work at five.',exampleTr:'Beşte işi bitireceğim.'},
  {id:639,topic:'Günlük Fiiller',en:'try',tr:'denemek',type:'fiil',exampleEn:'Try the new restaurant tonight.',exampleTr:'Bu gece yeni restoranı dene.'},
  {id:640,topic:'Günlük Fiiller',en:'choose',tr:'seçmek',type:'fiil',exampleEn:'Choose your favourite colour.',exampleTr:'En sevdiğin rengi seç.'},
  {id:641,topic:'Günlük Fiiller',en:'move',tr:'hareket etmek',type:'fiil',exampleEn:'Move the chair to the corner.',exampleTr:'Sandalyeyi köşeye taşı.'},
  {id:642,topic:'Günlük Fiiller',en:'think',tr:'düşünmek',type:'fiil',exampleEn:'Think before you speak.',exampleTr:'Konuşmadan önce düşün.'},
  {id:643,topic:'Günlük Fiiller',en:'forget',tr:'unutmak',type:'fiil',exampleEn:'I often forget my password.',exampleTr:'Şifremi sık sık unutuyorum.'},
  {id:644,topic:'Günlük Fiiller',en:'push',tr:'itmek',type:'fiil',exampleEn:'Push the door to open it.',exampleTr:'Kapıyı açmak için it.'},
  {id:645,topic:'Günlük Fiiller',en:'pull',tr:'çekmek',type:'fiil',exampleEn:'Pull the rope as hard as you can.',exampleTr:'İpi gücünce çek.'},

  // Doğa ve Hava (646-665)
  {id:646,topic:'Doğa ve Hava',en:'beach',tr:'plaj',type:'isim',exampleEn:'We went to the beach last weekend.',exampleTr:'Geçen hafta sonu plaja gittik.'},
  {id:647,topic:'Doğa ve Hava',en:'desert',tr:'çöl',type:'isim',exampleEn:'The Sahara is a famous desert.',exampleTr:'Sahra ünlü bir çöldür.'},
  {id:648,topic:'Doğa ve Hava',en:'forest',tr:'orman',type:'isim',exampleEn:'There are many animals in the forest.',exampleTr:'Ormanda birçok hayvan var.'},
  {id:649,topic:'Doğa ve Hava',en:'lake',tr:'göl',type:'isim',exampleEn:'We swam in the lake.',exampleTr:'Gölde yüzdük.'},
  {id:650,topic:'Doğa ve Hava',en:'valley',tr:'vadi',type:'isim',exampleEn:'The river flows through the valley.',exampleTr:'Nehir vadiden geçiyor.'},
  {id:651,topic:'Doğa ve Hava',en:'island',tr:'ada',type:'isim',exampleEn:'They went on holiday to an island.',exampleTr:'Bir adaya tatile gittiler.'},
  {id:652,topic:'Doğa ve Hava',en:'volcano',tr:'yanardağ',type:'isim',exampleEn:'The volcano erupted last year.',exampleTr:'Yanardağ geçen yıl patladı.'},
  {id:653,topic:'Doğa ve Hava',en:'earthquake',tr:'deprem',type:'isim',exampleEn:'There was an earthquake last night.',exampleTr:'Dün gece deprem oldu.'},
  {id:654,topic:'Doğa ve Hava',en:'rainbow',tr:'gökkuşağı',type:'isim',exampleEn:'A rainbow appeared after the rain.',exampleTr:'Yağmurdan sonra gökkuşağı belirdi.'},
  {id:655,topic:'Doğa ve Hava',en:'lightning',tr:'şimşek',type:'isim',exampleEn:'Lightning flashed across the sky.',exampleTr:'Gökyüzünde şimşek çaktı.'},
  {id:656,topic:'Doğa ve Hava',en:'thunder',tr:'gök gürültüsü',type:'isim',exampleEn:'The thunder was very loud.',exampleTr:'Gök gürültüsü çok güçlüydü.'},
  {id:657,topic:'Doğa ve Hava',en:'frost',tr:'kırağı',type:'isim',exampleEn:'There was frost on the grass this morning.',exampleTr:'Bu sabah çimenlerde kırağı vardı.'},
  {id:658,topic:'Doğa ve Hava',en:'hail',tr:'dolu',type:'isim',exampleEn:'Hail damaged the cars.',exampleTr:'Dolu arabalar hasar gördü.'},
  {id:659,topic:'Doğa ve Hava',en:'flood',tr:'sel',type:'isim',exampleEn:'The flood destroyed many homes.',exampleTr:'Sel birçok evi yıktı.'},
  {id:660,topic:'Doğa ve Hava',en:'drought',tr:'kuraklık',type:'isim',exampleEn:'The drought lasted for months.',exampleTr:'Kuraklık aylarca sürdü.'},
  {id:661,topic:'Doğa ve Hava',en:'soil',tr:'toprak',type:'isim',exampleEn:'The soil here is very fertile.',exampleTr:'Buradaki toprak çok verimli.'},
  {id:662,topic:'Doğa ve Hava',en:'rock',tr:'kaya',type:'isim',exampleEn:'She sat on a big rock.',exampleTr:'Büyük bir kayanın üstüne oturdu.'},
  {id:663,topic:'Doğa ve Hava',en:'sand',tr:'kum',type:'isim',exampleEn:'The children played in the sand.',exampleTr:'Çocuklar kumda oynadı.'},
  {id:664,topic:'Doğa ve Hava',en:'cliff',tr:'uçurum',type:'isim',exampleEn:'Do not stand near the cliff.',exampleTr:'Uçurumun yakınında durma.'},
  {id:665,topic:'Doğa ve Hava',en:'cave',tr:'mağara',type:'isim',exampleEn:'The explorers entered the cave.',exampleTr:'Kaşifler mağaraya girdi.'},

  // Günler, Aylar, Mevsimler (666-685)
  {id:666,topic:'Günler, Aylar, Mevsimler',en:'daily',tr:'günlük',type:'sıfat',exampleEn:'Exercise is part of my daily routine.',exampleTr:'Egzersiz günlük rutinimin bir parçası.'},
  {id:667,topic:'Günler, Aylar, Mevsimler',en:'weekly',tr:'haftalık',type:'sıfat',exampleEn:'We have a weekly meeting.',exampleTr:'Haftalık toplantımız var.'},
  {id:668,topic:'Günler, Aylar, Mevsimler',en:'monthly',tr:'aylık',type:'sıfat',exampleEn:'I pay monthly rent.',exampleTr:'Aylık kira ödüyorum.'},
  {id:669,topic:'Günler, Aylar, Mevsimler',en:'annual',tr:'yıllık',type:'sıfat',exampleEn:'We have an annual school trip.',exampleTr:'Yıllık okul gezimiz var.'},
  {id:670,topic:'Günler, Aylar, Mevsimler',en:'century',tr:'yüzyıl',type:'isim',exampleEn:'We live in the twenty-first century.',exampleTr:'Yirmi birinci yüzyılda yaşıyoruz.'},
  {id:671,topic:'Günler, Aylar, Mevsimler',en:'decade',tr:'on yıl',type:'isim',exampleEn:'Technology changed a lot in the last decade.',exampleTr:'Teknoloji son on yılda çok değişti.'},
  {id:672,topic:'Günler, Aylar, Mevsimler',en:'fortnight',tr:'iki hafta',type:'isim',exampleEn:'We go camping every fortnight.',exampleTr:'Her iki haftada bir kamp yapıyoruz.'},
  {id:673,topic:'Günler, Aylar, Mevsimler',en:'semester',tr:'sömestr',type:'isim',exampleEn:'The semester ends in June.',exampleTr:'Sömestr Haziran da bitiyor.'},
  {id:674,topic:'Günler, Aylar, Mevsimler',en:'weekend',tr:'hafta sonu',type:'isim',exampleEn:'We relax at the weekend.',exampleTr:'Hafta sonu dinleniyoruz.'},
  {id:675,topic:'Günler, Aylar, Mevsimler',en:'holiday',tr:'tatil',type:'isim',exampleEn:'We went to Italy for our holiday.',exampleTr:'Tatil için İtalyaya gittik.'},
  {id:676,topic:'Günler, Aylar, Mevsimler',en:'calendar',tr:'takvim',type:'isim',exampleEn:'Check the calendar for the date.',exampleTr:'Tarih için takvime bak.'},
  {id:677,topic:'Günler, Aylar, Mevsimler',en:'schedule',tr:'program',type:'isim',exampleEn:'My schedule is very busy this week.',exampleTr:'Bu haftaki programım çok yoğun.'},
  {id:678,topic:'Günler, Aylar, Mevsimler',en:'birthday',tr:'doğum günü',type:'isim',exampleEn:'Happy birthday to you!',exampleTr:'Doğum günün kutlu olsun!'},
  {id:679,topic:'Günler, Aylar, Mevsimler',en:'anniversary',tr:'yıl dönümü',type:'isim',exampleEn:'Today is our wedding anniversary.',exampleTr:'Bugün evlilik yıl dönümümüz.'},
  {id:680,topic:'Günler, Aylar, Mevsimler',en:'deadline',tr:'son tarih',type:'isim',exampleEn:'The deadline is on Friday.',exampleTr:'Son tarih Cuma günü.'},
  {id:681,topic:'Günler, Aylar, Mevsimler',en:'occasion',tr:'özel gün',type:'isim',exampleEn:'We dress nicely for special occasions.',exampleTr:'Özel günlerde güzel giyiniyoruz.'},
  {id:682,topic:'Günler, Aylar, Mevsimler',en:'period',tr:'dönem',type:'isim',exampleEn:'This is a difficult period for everyone.',exampleTr:'Bu herkes için zor bir dönem.'},
  {id:683,topic:'Günler, Aylar, Mevsimler',en:'duration',tr:'süre',type:'isim',exampleEn:'What is the duration of the film?',exampleTr:'Filmin süresi ne kadar?'},
  {id:684,topic:'Günler, Aylar, Mevsimler',en:'routine',tr:'rutin',type:'isim',exampleEn:'I follow a morning routine.',exampleTr:'Sabah rutinime uyuyorum.'},
  {id:685,topic:'Günler, Aylar, Mevsimler',en:'forecast',tr:'hava tahmini',type:'isim',exampleEn:'The forecast says it will rain tomorrow.',exampleTr:'Hava tahmini yarın yağmur yağacağını söylüyor.'},

  // Zaman (686-705)
  {id:686,topic:'Zaman',en:'midnight',tr:'gece yarısı',type:'isim',exampleEn:'We arrived home at midnight.',exampleTr:'Gece yarısı eve döndük.'},
  {id:687,topic:'Zaman',en:'noon',tr:'öğlen',type:'isim',exampleEn:'We eat lunch at noon.',exampleTr:'Öğlen yemek yiyoruz.'},
  {id:688,topic:'Zaman',en:'afternoon',tr:'öğleden sonra',type:'isim',exampleEn:'The meeting is in the afternoon.',exampleTr:'Toplantı öğleden sonra.'},
  {id:689,topic:'Zaman',en:'past',tr:'geçmiş',type:'isim',exampleEn:'Learn from the past.',exampleTr:'Geçmişten öğren.'},
  {id:690,topic:'Zaman',en:'present',tr:'şimdiki zaman',type:'isim',exampleEn:'Focus on the present moment.',exampleTr:'Şu ana odaklan.'},
  {id:691,topic:'Zaman',en:'future',tr:'gelecek',type:'isim',exampleEn:'Plan for the future.',exampleTr:'Gelecek için plan yap.'},
  {id:692,topic:'Zaman',en:'instant',tr:'an',type:'isim',exampleEn:'It happened in an instant.',exampleTr:'Bir anda gerçekleşti.'},
  {id:693,topic:'Zaman',en:'moment',tr:'kısa süre',type:'isim',exampleEn:'Wait a moment please.',exampleTr:'Bir an bekle lütfen.'},
  {id:694,topic:'Zaman',en:'recently',tr:'son zamanlarda',type:'zarf',exampleEn:'I recently started a new job.',exampleTr:'Son zamanlarda yeni bir işe başladım.'},
  {id:695,topic:'Zaman',en:'soon',tr:'yakında',type:'zarf',exampleEn:'The bus will arrive soon.',exampleTr:'Otobüs yakında gelecek.'},
  {id:696,topic:'Zaman',en:'already',tr:'zaten',type:'zarf',exampleEn:'I have already eaten.',exampleTr:'Zaten yedim.'},
  {id:697,topic:'Zaman',en:'still',tr:'hâlâ',type:'zarf',exampleEn:'She is still sleeping.',exampleTr:'Hâlâ uyuyor.'},
  {id:698,topic:'Zaman',en:'yet',tr:'henüz',type:'zarf',exampleEn:'I have not finished yet.',exampleTr:'Henüz bitirmedim.'},
  {id:699,topic:'Zaman',en:'since',tr:'beri',type:'zarf',exampleEn:'I have lived here since 2010.',exampleTr:'2010 dan beri burada yaşıyorum.'},
  {id:700,topic:'Zaman',en:'until',tr:'kadar',type:'zarf',exampleEn:'Wait here until I come back.',exampleTr:'Ben dönene kadar burada bekle.'},
  {id:701,topic:'Zaman',en:'before',tr:'önce',type:'zarf',exampleEn:'Wash your hands before eating.',exampleTr:'Yemekten önce ellerini yıka.'},
  {id:702,topic:'Zaman',en:'after',tr:'sonra',type:'zarf',exampleEn:'Call me after the meeting.',exampleTr:'Toplantıdan sonra ara.'},
  {id:703,topic:'Zaman',en:'during',tr:'boyunca',type:'zarf',exampleEn:'She slept during the film.',exampleTr:'Film boyunca uyudu.'},
  {id:704,topic:'Zaman',en:'meanwhile',tr:'bu sırada',type:'zarf',exampleEn:'Cook the pasta. Meanwhile prepare the sauce.',exampleTr:'Makarnayı pişir. Bu sırada sosu hazırla.'},
  {id:705,topic:'Zaman',en:'suddenly',tr:'aniden',type:'zarf',exampleEn:'The lights suddenly went off.',exampleTr:'Işıklar aniden söndü.'},

  // Ulaşım (706-725)
  {id:706,topic:'Ulaşım',en:'metro',tr:'metro',type:'isim',exampleEn:'I take the metro to work.',exampleTr:'İşe metroyla gidiyorum.'},
  {id:707,topic:'Ulaşım',en:'tram',tr:'tramvay',type:'isim',exampleEn:'The tram stops near my house.',exampleTr:'Tramvay evimin yakınında duruyor.'},
  {id:708,topic:'Ulaşım',en:'helicopter',tr:'helikopter',type:'isim',exampleEn:'The helicopter landed on the roof.',exampleTr:'Helikopter çatıya indi.'},
  {id:709,topic:'Ulaşım',en:'motorbike',tr:'motosiklet',type:'isim',exampleEn:'He rides a motorbike to school.',exampleTr:'Okula motosikletle gidiyor.'},
  {id:710,topic:'Ulaşım',en:'lorry',tr:'kamyon',type:'isim',exampleEn:'The lorry was carrying heavy boxes.',exampleTr:'Kamyon ağır kutular taşıyordu.'},
  {id:711,topic:'Ulaşım',en:'ferry',tr:'feribot',type:'isim',exampleEn:'We took the ferry to the island.',exampleTr:'Adaya feribotle gittik.'},
  {id:712,topic:'Ulaşım',en:'highway',tr:'karayolu',type:'isim',exampleEn:'Drive carefully on the highway.',exampleTr:'Karayolunda dikkatli sür.'},
  {id:713,topic:'Ulaşım',en:'motorway',tr:'otoyol',type:'isim',exampleEn:'The motorway was very busy.',exampleTr:'Otoyol çok kalabalıktı.'},
  {id:714,topic:'Ulaşım',en:'journey',tr:'yolculuk',type:'isim',exampleEn:'The journey took three hours.',exampleTr:'Yolculuk üç saat sürdü.'},
  {id:715,topic:'Ulaşım',en:'trip',tr:'gezi',type:'isim',exampleEn:'We planned a trip to Paris.',exampleTr:'Paris e bir gezi planladık.'},
  {id:716,topic:'Ulaşım',en:'passport',tr:'pasaport',type:'isim',exampleEn:'Do not forget your passport.',exampleTr:'Pasaportunuzu unutmayın.'},
  {id:717,topic:'Ulaşım',en:'luggage',tr:'bagaj',type:'isim',exampleEn:'My luggage is too heavy.',exampleTr:'Bagajım çok ağır.'},
  {id:718,topic:'Ulaşım',en:'platform',tr:'peron',type:'isim',exampleEn:'The train is at platform three.',exampleTr:'Tren üç numaralı peronda.'},
  {id:719,topic:'Ulaşım',en:'departure',tr:'kalkış',type:'isim',exampleEn:'The departure is at seven.',exampleTr:'Kalkış saat yedide.'},
  {id:720,topic:'Ulaşım',en:'destination',tr:'hedef',type:'isim',exampleEn:'What is your final destination?',exampleTr:'Son hedefiniz nere?'},
  {id:721,topic:'Ulaşım',en:'direction',tr:'yön',type:'isim',exampleEn:'Can you show me the direction?',exampleTr:'Bana yönü gösterir misin?'},
  {id:722,topic:'Ulaşım',en:'route',tr:'güzergah',type:'isim',exampleEn:'Take the shortest route.',exampleTr:'En kısa güzergahı al.'},
  {id:723,topic:'Ulaşım',en:'traffic',tr:'trafik',type:'isim',exampleEn:'The traffic was very bad today.',exampleTr:'Bugün trafik çok kötüydü.'},
  {id:724,topic:'Ulaşım',en:'fuel',tr:'yakıt',type:'isim',exampleEn:'The car needs more fuel.',exampleTr:'Arabanın daha fazla yakıta ihtiyacı var.'},
  {id:725,topic:'Ulaşım',en:'parking',tr:'otopark',type:'isim',exampleEn:'There is no parking here.',exampleTr:'Burada otopark yok.'},

  // Şehir ve Mekanlar (726-745)
  {id:726,topic:'Şehir ve Mekanlar',en:'stadium',tr:'stadyum',type:'isim',exampleEn:'The stadium was full of fans.',exampleTr:'Stadyum taraftarlarla doluydu.'},
  {id:727,topic:'Şehir ve Mekanlar',en:'zoo',tr:'hayvanat bahçesi',type:'isim',exampleEn:'The children loved the zoo.',exampleTr:'Çocuklar hayvanat bahçesini çok sevdi.'},
  {id:728,topic:'Şehir ve Mekanlar',en:'theatre',tr:'tiyatro',type:'isim',exampleEn:'We saw a play at the theatre.',exampleTr:'Tiyatroda bir oyun izledik.'},
  {id:729,topic:'Şehir ve Mekanlar',en:'port',tr:'liman',type:'isim',exampleEn:'The ship arrived at the port.',exampleTr:'Gemi limana yanaştı.'},
  {id:730,topic:'Şehir ve Mekanlar',en:'suburb',tr:'banliyö',type:'isim',exampleEn:'They live in the suburbs.',exampleTr:'Banliyöde yaşıyorlar.'},
  {id:731,topic:'Şehir ve Mekanlar',en:'neighbourhood',tr:'mahalle',type:'isim',exampleEn:'This is a quiet neighbourhood.',exampleTr:'Burası sessiz bir mahalle.'},
  {id:732,topic:'Şehir ve Mekanlar',en:'supermarket',tr:'süpermarket',type:'isim',exampleEn:'I buy food at the supermarket.',exampleTr:'Yiyecekleri süpermarketten alıyorum.'},
  {id:733,topic:'Şehir ve Mekanlar',en:'cafe',tr:'kafe',type:'isim',exampleEn:'Let us meet at the cafe.',exampleTr:'Kafede buluşalım.'},
  {id:734,topic:'Şehir ve Mekanlar',en:'embassy',tr:'büyükelçilik',type:'isim',exampleEn:'The embassy is in the city centre.',exampleTr:'Büyükelçilik şehir merkezinde.'},
  {id:735,topic:'Şehir ve Mekanlar',en:'gallery',tr:'galeri',type:'isim',exampleEn:'We visited an art gallery.',exampleTr:'Bir sanat galerisini ziyaret ettik.'},
  {id:736,topic:'Şehir ve Mekanlar',en:'university',tr:'üniversite',type:'isim',exampleEn:'She studies at a famous university.',exampleTr:'Ünlü bir üniversitede okuyor.'},
  {id:737,topic:'Şehir ve Mekanlar',en:'castle',tr:'kale',type:'isim',exampleEn:'The old castle is on the hill.',exampleTr:'Eski kale tepede.'},
  {id:738,topic:'Şehir ve Mekanlar',en:'harbour',tr:'iç liman',type:'isim',exampleEn:'Boats are parked in the harbour.',exampleTr:'Tekneler iç limanda park ediyor.'},
  {id:739,topic:'Şehir ve Mekanlar',en:'pier',tr:'iskele',type:'isim',exampleEn:'We walked along the pier.',exampleTr:'İskele boyunca yürüdük.'},
  {id:740,topic:'Şehir ve Mekanlar',en:'fountain',tr:'fıskiye',type:'isim',exampleEn:'There is a fountain in the square.',exampleTr:'Meydanda bir fıskiye var.'},
  {id:741,topic:'Şehir ve Mekanlar',en:'intersection',tr:'kavşak',type:'isim',exampleEn:'Turn left at the intersection.',exampleTr:'Kavşakta sola dön.'},
  {id:742,topic:'Şehir ve Mekanlar',en:'district',tr:'ilçe',type:'isim',exampleEn:'She lives in the central district.',exampleTr:'Merkez ilçede yaşıyor.'},
  {id:743,topic:'Şehir ve Mekanlar',en:'landmark',tr:'simge yapı',type:'isim',exampleEn:'The tower is a famous landmark.',exampleTr:'Kule ünlü bir simge yapıdır.'},
  {id:744,topic:'Şehir ve Mekanlar',en:'outskirts',tr:'şehir kenarı',type:'isim',exampleEn:'They live on the outskirts of the city.',exampleTr:'Şehrin kenarında yaşıyorlar.'},
  {id:745,topic:'Şehir ve Mekanlar',en:'complex',tr:'kompleks',type:'isim',exampleEn:'There is a sports complex nearby.',exampleTr:'Yakında bir spor kompleksi var.'},

  // Alışveriş (746-765)
  {id:746,topic:'Alışveriş',en:'sale',tr:'indirim',type:'isim',exampleEn:'Everything is on sale today.',exampleTr:'Bugün her şey indirimde.'},
  {id:747,topic:'Alışveriş',en:'refund',tr:'geri ödeme',type:'isim',exampleEn:'I asked for a refund.',exampleTr:'Geri ödeme istedim.'},
  {id:748,topic:'Alışveriş',en:'exchange',tr:'değiştirme',type:'isim',exampleEn:'Can I exchange this for a bigger size?',exampleTr:'Bunu daha büyük bedenle değiştirebilir miyim?'},
  {id:749,topic:'Alışveriş',en:'warranty',tr:'garanti',type:'isim',exampleEn:'The phone has a two year warranty.',exampleTr:'Telefonun iki yıllık garantisi var.'},
  {id:750,topic:'Alışveriş',en:'delivery',tr:'teslimat',type:'isim',exampleEn:'Free delivery on orders over fifty pounds.',exampleTr:'Elli pound üzerindeki siparişlerde ücretsiz teslimat.'},
  {id:751,topic:'Alışveriş',en:'order',tr:'sipariş',type:'isim',exampleEn:'I placed an order online.',exampleTr:'Çevrimiçi sipariş verdim.'},
  {id:752,topic:'Alışveriş',en:'item',tr:'ürün',type:'isim',exampleEn:'This item is out of stock.',exampleTr:'Bu ürün stokta yok.'},
  {id:753,topic:'Alışveriş',en:'stock',tr:'stok',type:'isim',exampleEn:'We have limited stock.',exampleTr:'Sınırlı stoğumuz var.'},
  {id:754,topic:'Alışveriş',en:'catalogue',tr:'katalog',type:'isim',exampleEn:'Look through the catalogue.',exampleTr:'Kataloğu inceleyin.'},
  {id:755,topic:'Alışveriş',en:'barcode',tr:'barkod',type:'isim',exampleEn:'Scan the barcode to pay.',exampleTr:'Ödeme yapmak için barkodu tara.'},
  {id:756,topic:'Alışveriş',en:'checkout',tr:'kasa',type:'isim',exampleEn:'Please go to the checkout.',exampleTr:'Lütfen kasaya gidin.'},
  {id:757,topic:'Alışveriş',en:'purchase',tr:'satın alma',type:'isim',exampleEn:'Keep the receipt for your purchase.',exampleTr:'Satın almanız için fişi saklayın.'},
  {id:758,topic:'Alışveriş',en:'gift',tr:'hediye',type:'isim',exampleEn:'I bought a gift for my mother.',exampleTr:'Annem için hediye aldım.'},
  {id:759,topic:'Alışveriş',en:'wrap',tr:'sarmak',type:'fiil',exampleEn:'Can you wrap this as a gift?',exampleTr:'Bunu hediye olarak sarar mısın?'},
  {id:760,topic:'Alışveriş',en:'value',tr:'değer',type:'isim',exampleEn:'This product offers great value.',exampleTr:'Bu ürün büyük değer sunuyor.'},
  {id:761,topic:'Alışveriş',en:'budget',tr:'bütçe',type:'isim',exampleEn:'We have a small budget.',exampleTr:'Küçük bir bütçemiz var.'},
  {id:762,topic:'Alışveriş',en:'wallet',tr:'cüzdan',type:'isim',exampleEn:'I left my wallet at home.',exampleTr:'Cüzdanımı evde unuttum.'},
  {id:763,topic:'Alışveriş',en:'invoice',tr:'fatura',type:'isim',exampleEn:'Send me the invoice by email.',exampleTr:'Faturayı e-posta ile gönder.'},
  {id:764,topic:'Alışveriş',en:'label',tr:'etiket',type:'isim',exampleEn:'Check the label for the price.',exampleTr:'Fiyat için etikete bak.'},
  {id:765,topic:'Alışveriş',en:'shop',tr:'dükkan',type:'isim',exampleEn:'There is a small shop on the corner.',exampleTr:'Köşede küçük bir dükkan var.'},

  // Meslekler (766-785)
  {id:766,topic:'Meslekler',en:'architect',tr:'mimar',type:'isim',exampleEn:'The architect designed the building.',exampleTr:'Mimar binayı tasarladı.'},
  {id:767,topic:'Meslekler',en:'accountant',tr:'muhasebeci',type:'isim',exampleEn:'The accountant checked the numbers.',exampleTr:'Muhasebeci sayıları kontrol etti.'},
  {id:768,topic:'Meslekler',en:'mechanic',tr:'tamirci',type:'isim',exampleEn:'The mechanic fixed my car.',exampleTr:'Tamirci arabamı tamir etti.'},
  {id:769,topic:'Meslekler',en:'plumber',tr:'tesisatçı',type:'isim',exampleEn:'We called a plumber for the leak.',exampleTr:'Sızıntı için tesisatçı aradık.'},
  {id:770,topic:'Meslekler',en:'electrician',tr:'elektrikçi',type:'isim',exampleEn:'The electrician fixed the lights.',exampleTr:'Elektrikçi lambaları tamir etti.'},
  {id:771,topic:'Meslekler',en:'photographer',tr:'fotoğrafçı',type:'isim',exampleEn:'The photographer took great pictures.',exampleTr:'Fotoğrafçı harika fotoğraflar çekti.'},
  {id:772,topic:'Meslekler',en:'secretary',tr:'sekreter',type:'isim',exampleEn:'The secretary answered all calls.',exampleTr:'Sekreter tüm aramaları yanıtladı.'},
  {id:773,topic:'Meslekler',en:'programmer',tr:'programcı',type:'isim',exampleEn:'She works as a programmer.',exampleTr:'Programcı olarak çalışıyor.'},
  {id:774,topic:'Meslekler',en:'chef',tr:'şef',type:'isim',exampleEn:'The chef prepared a delicious meal.',exampleTr:'Şef lezzetli bir yemek hazırladı.'},
  {id:775,topic:'Meslekler',en:'firefighter',tr:'itfaiyeci',type:'isim',exampleEn:'The firefighter saved the child.',exampleTr:'İtfaiyeci çocuğu kurtardı.'},
  {id:776,topic:'Meslekler',en:'surgeon',tr:'cerrah',type:'isim',exampleEn:'The surgeon performed the operation.',exampleTr:'Cerrah ameliyatı gerçekleştirdi.'},
  {id:777,topic:'Meslekler',en:'judge',tr:'hakim',type:'isim',exampleEn:'The judge made a fair decision.',exampleTr:'Hakim adil bir karar verdi.'},
  {id:778,topic:'Meslekler',en:'banker',tr:'bankacı',type:'isim',exampleEn:'He works as a banker in the city.',exampleTr:'Şehirde bankacı olarak çalışıyor.'},
  {id:779,topic:'Meslekler',en:'translator',tr:'çevirmen',type:'isim',exampleEn:'The translator spoke three languages.',exampleTr:'Çevirmen üç dil konuşuyordu.'},
  {id:780,topic:'Meslekler',en:'designer',tr:'tasarımcı',type:'isim',exampleEn:'She is a graphic designer.',exampleTr:'Grafik tasarımcı.'},
  {id:781,topic:'Meslekler',en:'veterinarian',tr:'veteriner',type:'isim',exampleEn:'The veterinarian treated the dog.',exampleTr:'Veteriner köpeği tedavi etti.'},
  {id:782,topic:'Meslekler',en:'librarian',tr:'kütüphaneci',type:'isim',exampleEn:'The librarian helped me find a book.',exampleTr:'Kütüphaneci kitap bulmama yardım etti.'},
  {id:783,topic:'Meslekler',en:'barber',tr:'berber',type:'isim',exampleEn:'He went to the barber for a haircut.',exampleTr:'Saç kestirmek için berbere gitti.'},
  {id:784,topic:'Meslekler',en:'coach',tr:'antrenör',type:'isim',exampleEn:'The coach trained the team every day.',exampleTr:'Antrenör her gün takımı antrenman yaptırdı.'},
  {id:785,topic:'Meslekler',en:'director',tr:'yönetmen',type:'isim',exampleEn:'The director made a famous film.',exampleTr:'Yönetmen ünlü bir film çekti.'},

  // Okul ve Eğitim (786-805)
  {id:786,topic:'Okul ve Eğitim',en:'certificate',tr:'sertifika',type:'isim',exampleEn:'She received a certificate for the course.',exampleTr:'Kurs için sertifika aldı.'},
  {id:787,topic:'Okul ve Eğitim',en:'scholarship',tr:'burs',type:'isim',exampleEn:'He won a scholarship to study abroad.',exampleTr:'Yurt dışında okumak için burs kazandı.'},
  {id:788,topic:'Okul ve Eğitim',en:'course',tr:'kurs',type:'isim',exampleEn:'I am taking an English course.',exampleTr:'İngilizce kursu alıyorum.'},
  {id:789,topic:'Okul ve Eğitim',en:'lecture',tr:'ders',type:'isim',exampleEn:'The lecture starts at ten.',exampleTr:'Ders saat onda başlıyor.'},
  {id:790,topic:'Okul ve Eğitim',en:'assignment',tr:'ödev',type:'isim',exampleEn:'Submit your assignment by Friday.',exampleTr:'Ödevini Cuma gününe kadar teslim et.'},
  {id:791,topic:'Okul ve Eğitim',en:'project',tr:'proje',type:'isim',exampleEn:'We worked on a science project.',exampleTr:'Bir fen projesinde çalıştık.'},
  {id:792,topic:'Okul ve Eğitim',en:'research',tr:'araştırma',type:'isim',exampleEn:'She did research on climate change.',exampleTr:'İklim değişikliği üzerine araştırma yaptı.'},
  {id:793,topic:'Okul ve Eğitim',en:'knowledge',tr:'bilgi',type:'isim',exampleEn:'He has a lot of knowledge about history.',exampleTr:'Tarih hakkında çok bilgisi var.'},
  {id:794,topic:'Okul ve Eğitim',en:'skill',tr:'beceri',type:'isim',exampleEn:'Reading is an important skill.',exampleTr:'Okumak önemli bir beceridir.'},
  {id:795,topic:'Okul ve Eğitim',en:'revision',tr:'tekrar',type:'isim',exampleEn:'Do revision before the exam.',exampleTr:'Sınavdan önce tekrar yap.'},
  {id:796,topic:'Okul ve Eğitim',en:'result',tr:'sonuç',type:'isim',exampleEn:'The exam results are out.',exampleTr:'Sınav sonuçları açıklandı.'},
  {id:797,topic:'Okul ve Eğitim',en:'presentation',tr:'sunum',type:'isim',exampleEn:'She gave a presentation to the class.',exampleTr:'Sınıfa sunum yaptı.'},
  {id:798,topic:'Okul ve Eğitim',en:'graduate',tr:'mezun olmak',type:'fiil',exampleEn:'She graduated from university last year.',exampleTr:'Geçen yıl üniversiteden mezun oldu.'},
  {id:799,topic:'Okul ve Eğitim',en:'degree',tr:'diploma',type:'isim',exampleEn:'He has a degree in science.',exampleTr:'Fen alanında diploması var.'},
  {id:800,topic:'Okul ve Eğitim',en:'curriculum',tr:'müfredat',type:'isim',exampleEn:'The curriculum changed this year.',exampleTr:'Müfredat bu yıl değişti.'},
  {id:801,topic:'Okul ve Eğitim',en:'classroom',tr:'derslik',type:'isim',exampleEn:'The classroom has thirty students.',exampleTr:'Derslikte otuz öğrenci var.'},
  {id:802,topic:'Okul ve Eğitim',en:'tutor',tr:'özel öğretmen',type:'isim',exampleEn:'She has a tutor for maths.',exampleTr:'Matematik için özel öğretmeni var.'},
  {id:803,topic:'Okul ve Eğitim',en:'rule',tr:'kural',type:'isim',exampleEn:'Follow the school rules.',exampleTr:'Okul kurallarına uy.'},
  {id:804,topic:'Okul ve Eğitim',en:'method',tr:'yöntem',type:'isim',exampleEn:'This is a good teaching method.',exampleTr:'Bu iyi bir öğretim yöntemidir.'},
  {id:805,topic:'Okul ve Eğitim',en:'educate',tr:'eğitmek',type:'fiil',exampleEn:'It is important to educate children.',exampleTr:'Çocukları eğitmek önemlidir.'},

  // Sağlık (806-825)
  {id:806,topic:'Sağlık',en:'symptom',tr:'belirti',type:'isim',exampleEn:'Fever is a common symptom.',exampleTr:'Ateş yaygın bir belirtidir.'},
  {id:807,topic:'Sağlık',en:'diagnosis',tr:'teşhis',type:'isim',exampleEn:'The doctor gave a quick diagnosis.',exampleTr:'Doktor hızlı bir teşhis koydu.'},
  {id:808,topic:'Sağlık',en:'treatment',tr:'tedavi',type:'isim',exampleEn:'The treatment was successful.',exampleTr:'Tedavi başarılı oldu.'},
  {id:809,topic:'Sağlık',en:'surgery',tr:'ameliyat',type:'isim',exampleEn:'He had surgery on his knee.',exampleTr:'Dizinden ameliyat oldu.'},
  {id:810,topic:'Sağlık',en:'blood',tr:'kan',type:'isim',exampleEn:'She donated blood last week.',exampleTr:'Geçen hafta kan bağışladı.'},
  {id:811,topic:'Sağlık',en:'pressure',tr:'tansiyon',type:'isim',exampleEn:'His blood pressure is high.',exampleTr:'Tansiyonu yüksek.'},
  {id:812,topic:'Sağlık',en:'pulse',tr:'nabız',type:'isim',exampleEn:'The nurse checked her pulse.',exampleTr:'Hemşire nabzını kontrol etti.'},
  {id:813,topic:'Sağlık',en:'infection',tr:'enfeksiyon',type:'isim',exampleEn:'He has an ear infection.',exampleTr:'Kulak enfeksiyonu var.'},
  {id:814,topic:'Sağlık',en:'wound',tr:'yara',type:'isim',exampleEn:'Clean the wound carefully.',exampleTr:'Yarayı dikkatlice temizle.'},
  {id:815,topic:'Sağlık',en:'bandage',tr:'sargı',type:'isim',exampleEn:'She put a bandage on her hand.',exampleTr:'Eline sargı sardı.'},
  {id:816,topic:'Sağlık',en:'vitamin',tr:'vitamin',type:'isim',exampleEn:'Take your vitamins every day.',exampleTr:'Her gün vitaminlerini al.'},
  {id:817,topic:'Sağlık',en:'diet',tr:'diyet',type:'isim',exampleEn:'She is on a healthy diet.',exampleTr:'Sağlıklı diyet yapıyor.'},
  {id:818,topic:'Sağlık',en:'mental',tr:'zihinsel',type:'sıfat',exampleEn:'Mental health is very important.',exampleTr:'Zihinsel sağlık çok önemlidir.'},
  {id:819,topic:'Sağlık',en:'stress',tr:'stres',type:'isim',exampleEn:'Too much stress is bad for health.',exampleTr:'Çok fazla stres sağlık için zararlıdır.'},
  {id:820,topic:'Sağlık',en:'anxiety',tr:'kaygı',type:'isim',exampleEn:'She has anxiety before exams.',exampleTr:'Sınavlardan önce kaygı duyuyor.'},
  {id:821,topic:'Sağlık',en:'therapy',tr:'terapi',type:'isim',exampleEn:'He goes to therapy every week.',exampleTr:'Her hafta terapiye gidiyor.'},
  {id:822,topic:'Sağlık',en:'hygiene',tr:'hijyen',type:'isim',exampleEn:'Good hygiene prevents illness.',exampleTr:'İyi hijyen hastalıkları önler.'},
  {id:823,topic:'Sağlık',en:'disabled',tr:'engelli',type:'sıfat',exampleEn:'The building has access for disabled people.',exampleTr:'Binada engelli erişimi var.'},
  {id:824,topic:'Sağlık',en:'cure',tr:'iyileştirmek',type:'fiil',exampleEn:'This medicine will cure your cold.',exampleTr:'Bu ilaç soğuk algınlığını iyileştirecek.'},
  {id:825,topic:'Sağlık',en:'clinic',tr:'klinik',type:'isim',exampleEn:'She works at a medical clinic.',exampleTr:'Tıp kliniğinde çalışıyor.'},

  // Spor (826-845)
  {id:826,topic:'Spor',en:'volleyball',tr:'voleybol',type:'isim',exampleEn:'She plays volleyball every week.',exampleTr:'Her hafta voleybol oynuyor.'},
  {id:827,topic:'Spor',en:'golf',tr:'golf',type:'isim',exampleEn:'My father loves playing golf.',exampleTr:'Babam golf oynamayı çok sever.'},
  {id:828,topic:'Spor',en:'boxing',tr:'boks',type:'isim',exampleEn:'He trains boxing three days a week.',exampleTr:'Haftada üç gün boks antrenmanı yapıyor.'},
  {id:829,topic:'Spor',en:'wrestling',tr:'güreş',type:'isim',exampleEn:'Wrestling is a traditional sport.',exampleTr:'Güreş geleneksel bir spordur.'},
  {id:830,topic:'Spor',en:'athletics',tr:'atletizm',type:'isim',exampleEn:'She competes in athletics.',exampleTr:'Atletizmde yarışıyor.'},
  {id:831,topic:'Spor',en:'marathon',tr:'maraton',type:'isim',exampleEn:'He ran his first marathon last year.',exampleTr:'Geçen yıl ilk maratonunu koştu.'},
  {id:832,topic:'Spor',en:'sprint',tr:'kısa koşu',type:'isim',exampleEn:'She won the hundred metre sprint.',exampleTr:'Yüz metre kısa koşusunu kazandı.'},
  {id:833,topic:'Spor',en:'relay',tr:'bayrak koşusu',type:'isim',exampleEn:'The team won the relay race.',exampleTr:'Takım bayrak koşusunu kazandı.'},
  {id:834,topic:'Spor',en:'champion',tr:'şampiyon',type:'isim',exampleEn:'She became world champion.',exampleTr:'Dünya şampiyonu oldu.'},
  {id:835,topic:'Spor',en:'tournament',tr:'turnuva',type:'isim',exampleEn:'They entered a football tournament.',exampleTr:'Futbol turnuvasına girdiler.'},
  {id:836,topic:'Spor',en:'trophy',tr:'kupa',type:'isim',exampleEn:'The team lifted the trophy.',exampleTr:'Takım kupayı kaldırdı.'},
  {id:837,topic:'Spor',en:'referee',tr:'hakem',type:'isim',exampleEn:'The referee blew his whistle.',exampleTr:'Hakem düdüğünü çaldı.'},
  {id:838,topic:'Spor',en:'medal',tr:'madalya',type:'isim',exampleEn:'She won a gold medal at the Olympics.',exampleTr:'Olimpiyatlarda altın madalya kazandı.'},
  {id:839,topic:'Spor',en:'circuit',tr:'pist',type:'isim',exampleEn:'The racing circuit is very long.',exampleTr:'Yarış pisti çok uzun.'},
  {id:840,topic:'Spor',en:'race',tr:'yarış',type:'isim',exampleEn:'He won the race easily.',exampleTr:'Yarışı kolayca kazandı.'},
  {id:841,topic:'Spor',en:'fitness',tr:'kondisyon',type:'isim',exampleEn:'Good fitness helps you stay healthy.',exampleTr:'İyi kondisyon sağlıklı kalmanıza yardımcı olur.'},
  {id:842,topic:'Spor',en:'strength',tr:'güç',type:'isim',exampleEn:'You need strength to lift weights.',exampleTr:'Ağırlık kaldırmak için güce ihtiyaç var.'},
  {id:843,topic:'Spor',en:'flexible',tr:'esnek',type:'sıfat',exampleEn:'Gymnasts must be very flexible.',exampleTr:'Jimnastikçiler çok esnek olmalıdır.'},
  {id:844,topic:'Spor',en:'compete',tr:'yarışmak',type:'fiil',exampleEn:'She loves to compete in races.',exampleTr:'Yarışlarda yarışmayı seviyor.'},
  {id:845,topic:'Spor',en:'defend',tr:'savunmak',type:'fiil',exampleEn:'The goalkeeper defended the goal well.',exampleTr:'Kaleci kaleyi iyi savundu.'},

  // Duygular (846-865)
  {id:846,topic:'Duygular',en:'nervous',tr:'gergin',type:'sıfat',exampleEn:'I always feel nervous before exams.',exampleTr:'Sınavlardan önce her zaman gergin hissediyorum.'},
  {id:847,topic:'Duygular',en:'jealous',tr:'kıskanç',type:'sıfat',exampleEn:'He was jealous of his brother.',exampleTr:'Erkek kardeşini kıskanıyordu.'},
  {id:848,topic:'Duygular',en:'confused',tr:'kafası karışık',type:'sıfat',exampleEn:'I am confused about the directions.',exampleTr:'Yönler hakkında kafam karışık.'},
  {id:849,topic:'Duygular',en:'embarrassed',tr:'mahcup',type:'sıfat',exampleEn:'She felt embarrassed in front of everyone.',exampleTr:'Herkesin önünde mahcup hissetti.'},
  {id:850,topic:'Duygular',en:'ashamed',tr:'utanmış',type:'sıfat',exampleEn:'He was ashamed of his behaviour.',exampleTr:'Davranışından utandı.'},
  {id:851,topic:'Duygular',en:'grateful',tr:'minnettar',type:'sıfat',exampleEn:'I am grateful for your help.',exampleTr:'Yardımın için minnettarım.'},
  {id:852,topic:'Duygular',en:'disappointed',tr:'hayal kırıklığına uğramış',type:'sıfat',exampleEn:'She was disappointed with the result.',exampleTr:'Sonuçtan hayal kırıklığına uğradı.'},
  {id:853,topic:'Duygular',en:'relieved',tr:'rahatlamış',type:'sıfat',exampleEn:'He was relieved when it was over.',exampleTr:'Bitince rahatladı.'},
  {id:854,topic:'Duygular',en:'hopeful',tr:'umutlu',type:'sıfat',exampleEn:'She is hopeful about the future.',exampleTr:'Gelecek konusunda umutlu.'},
  {id:855,topic:'Duygular',en:'cheerful',tr:'neşeli',type:'sıfat',exampleEn:'She is always cheerful in the mornings.',exampleTr:'Sabahları her zaman neşeli.'},
  {id:856,topic:'Duygular',en:'miserable',tr:'mutsuz',type:'sıfat',exampleEn:'He looked miserable all day.',exampleTr:'Bütün gün mutsuz görünüyordu.'},
  {id:857,topic:'Duygular',en:'anxious',tr:'endişeli',type:'sıfat',exampleEn:'She felt anxious waiting for news.',exampleTr:'Haber beklerken endişeli hissetti.'},
  {id:858,topic:'Duygular',en:'confident',tr:'kendinden emin',type:'sıfat',exampleEn:'He is confident in his abilities.',exampleTr:'Yeteneklerine güveniyor.'},
  {id:859,topic:'Duygular',en:'curious',tr:'meraklı',type:'sıfat',exampleEn:'Children are naturally curious.',exampleTr:'Çocuklar doğal olarak meraklıdır.'},
  {id:860,topic:'Duygular',en:'frustrated',tr:'sinirlenmiş',type:'sıfat',exampleEn:'She felt frustrated with the problem.',exampleTr:'Sorun karşısında sinirlenmiş hissetti.'},
  {id:861,topic:'Duygular',en:'content',tr:'memnun',type:'sıfat',exampleEn:'He is content with his life.',exampleTr:'Hayatından memnun.'},
  {id:862,topic:'Duygular',en:'shocked',tr:'şoke olmuş',type:'sıfat',exampleEn:'She was shocked by the news.',exampleTr:'Haberden şoke oldu.'},
  {id:863,topic:'Duygular',en:'homesick',tr:'memleket özlemi çeken',type:'sıfat',exampleEn:'She felt homesick while abroad.',exampleTr:'Yurt dışındayken memleket özlemi çekti.'},
  {id:864,topic:'Duygular',en:'envious',tr:'imrenen',type:'sıfat',exampleEn:'He was envious of her success.',exampleTr:'Başarısına imrendi.'},
  {id:865,topic:'Duygular',en:'passionate',tr:'tutkulu',type:'sıfat',exampleEn:'She is passionate about music.',exampleTr:'Müziğe karşı tutkulu.'},

  // Teknoloji (866-885)
  {id:866,topic:'Teknoloji',en:'laptop',tr:'dizüstü bilgisayar',type:'isim',exampleEn:'She works on her laptop every day.',exampleTr:'Her gün dizüstü bilgisayarında çalışıyor.'},
  {id:867,topic:'Teknoloji',en:'printer',tr:'yazıcı',type:'isim',exampleEn:'The printer is out of paper.',exampleTr:'Yazıcının kağıdı bitti.'},
  {id:868,topic:'Teknoloji',en:'scanner',tr:'tarayıcı',type:'isim',exampleEn:'Use the scanner to copy the document.',exampleTr:'Belgeyi kopyalamak için tarayıcıyı kullan.'},
  {id:869,topic:'Teknoloji',en:'microphone',tr:'mikrofon',type:'isim',exampleEn:'Speak into the microphone clearly.',exampleTr:'Mikrofona açıkça konuş.'},
  {id:870,topic:'Teknoloji',en:'speaker',tr:'hoparlör',type:'isim',exampleEn:'Turn up the speaker volume.',exampleTr:'Hoparlör sesini aç.'},
  {id:871,topic:'Teknoloji',en:'headphones',tr:'kulaklık',type:'isim',exampleEn:'She listens to music with headphones.',exampleTr:'Kulaklıkla müzik dinliyor.'},
  {id:872,topic:'Teknoloji',en:'cable',tr:'kablo',type:'isim',exampleEn:'Connect the cable to the computer.',exampleTr:'Kabloyu bilgisayara bağla.'},
  {id:873,topic:'Teknoloji',en:'wifi',tr:'kablosuz ağ',type:'isim',exampleEn:'Do you have wifi here?',exampleTr:'Burada kablosuz ağ var mı?'},
  {id:874,topic:'Teknoloji',en:'bluetooth',tr:'bluetooth',type:'isim',exampleEn:'Connect via bluetooth.',exampleTr:'Bluetooth ile bağlan.'},
  {id:875,topic:'Teknoloji',en:'software',tr:'yazılım',type:'isim',exampleEn:'Install the new software.',exampleTr:'Yeni yazılımı yükle.'},
  {id:876,topic:'Teknoloji',en:'hardware',tr:'donanım',type:'isim',exampleEn:'The hardware needs to be upgraded.',exampleTr:'Donanımın yükseltilmesi gerekiyor.'},
  {id:877,topic:'Teknoloji',en:'virus',tr:'virüs',type:'isim',exampleEn:'A virus attacked the computer.',exampleTr:'Bilgisayara virüs bulaştı.'},
  {id:878,topic:'Teknoloji',en:'backup',tr:'yedekleme',type:'isim',exampleEn:'Always make a backup of your files.',exampleTr:'Dosyalarını her zaman yedekle.'},
  {id:879,topic:'Teknoloji',en:'update',tr:'güncelleme',type:'isim',exampleEn:'Install the latest update.',exampleTr:'Son güncellemeyi yükle.'},
  {id:880,topic:'Teknoloji',en:'search',tr:'aramak',type:'fiil',exampleEn:'Search for the answer online.',exampleTr:'Cevabı çevrimiçi ara.'},
  {id:881,topic:'Teknoloji',en:'upload',tr:'yüklemek',type:'fiil',exampleEn:'Upload the photo to the website.',exampleTr:'Fotoğrafı web sitesine yükle.'},
  {id:882,topic:'Teknoloji',en:'share',tr:'paylaşmak',type:'fiil',exampleEn:'Share the link with your friends.',exampleTr:'Bağlantıyı arkadaşlarınla paylaş.'},
  {id:883,topic:'Teknoloji',en:'stream',tr:'yayın akışı',type:'isim',exampleEn:'She streams films every evening.',exampleTr:'Her akşam film yayını izliyor.'},
  {id:884,topic:'Teknoloji',en:'robot',tr:'robot',type:'isim',exampleEn:'The robot helps in the factory.',exampleTr:'Robot fabrikada yardımcı oluyor.'},
  {id:885,topic:'Teknoloji',en:'network',tr:'ağ',type:'isim',exampleEn:'The network connection is slow.',exampleTr:'Ağ bağlantısı yavaş.'}
];

// Load existing A1 words
const a1 = JSON.parse(fs.readFileSync(path.join(__dirname, '../src/data/words.json'), 'utf8'));

// Check for duplicates
const a1Ens = new Set(a1.map(w => w.en));
const a2Ens = a2.map(w => w.en);
const dups = a2Ens.filter(en => a1Ens.has(en));
if (dups.length > 0) {
  console.error('DUPLICATES FOUND:', dups);
  process.exit(1);
}

// Check A2 internal duplicates
const a2EnSet = new Set();
const a2Dups = [];
a2Ens.forEach(en => { if (a2EnSet.has(en)) a2Dups.push(en); else a2EnSet.add(en); });
if (a2Dups.length > 0) {
  console.error('A2 INTERNAL DUPLICATES:', a2Dups);
  process.exit(1);
}

const merged = [...a1, ...a2];
fs.writeFileSync(path.join(__dirname, '../src/data/words.json'), JSON.stringify(merged, null, 2), 'utf8');
console.log('Done! Total words:', merged.length);
console.log('A1:', a1.length, '| A2:', a2.length);
