/**
 * generate_b2.cjs
 * Generates 22 × 20 = 440 B2-level words (IDs 1326-1765),
 * validates no duplicates against existing words.json, then merges.
 */

const fs = require('fs');
const path = require('path');

const WORDS_PATH = path.join(__dirname, '..', 'src', 'data', 'words.json');
const existing = JSON.parse(fs.readFileSync(WORDS_PATH, 'utf8'));
const existingEns = new Set(existing.map(w => w.en));

let id = 1326;

function w(topic, en, tr, type, exampleEn, exampleTr) {
  return { id: id++, topic, en, tr, type, exampleEn, exampleTr };
}

const T = (name) => name + ' (B2)';

const b2 = [

  // ── Selamlaşma ve Tanışma (B2) ────────────────────────────────────────
  w(T('Selamlaşma ve Tanışma'), 'reconciliation',  'uzlaşma',          'isim',  'The reconciliation between the two parties was long overdue.',   'İki taraf arasındaki uzlaşma çok geç kalmıştı.'),
  w(T('Selamlaşma ve Tanışma'), 'diplomacy',       'diplomasi',        'isim',  'Diplomacy is essential in international relations.',             'Uluslararası ilişkilerde diplomasi şarttır.'),
  w(T('Selamlaşma ve Tanışma'), 'protocol',        'protokol',         'isim',  'Following the correct protocol is important at state events.',   'Devlet törenlerinde doğru protokolü izlemek önemlidir.'),
  w(T('Selamlaşma ve Tanışma'), 'charisma',        'karizm',           'isim',  'His charisma made him an effective leader.',                     'Karizmasi onu etkili bir lider yaptı.'),
  w(T('Selamlaşma ve Tanışma'), 'eloquence',       'belagat',          'isim',  'Her eloquence impressed everyone at the summit.',                'Zirvede herkesi etkileyen bir belagata sahipti.'),
  w(T('Selamlaşma ve Tanışma'), 'gregarious',      'sosyal',           'sıfat', 'He is gregarious and loves meeting new people.',                 'Sosyal biri ve yeni insanlarla tanışmayı sever.'),
  w(T('Selamlaşma ve Tanışma'), 'esteem',          'saygınlık',        'isim',  'She is held in high esteem by her colleagues.',                  'Meslektaşları tarafından yüksek saygınlıkla karşılanır.'),
  w(T('Selamlaşma ve Tanışma'), 'etiquette',       'görgü kuralları',  'isim',  'Business etiquette varies across cultures.',                     'İş görgü kuralları kültürden kültüre farklılık gösterir.'),
  w(T('Selamlaşma ve Tanışma'), 'deference',       'saygı gösterme',   'isim',  'He acted with deference towards his elders.',                    'Büyüklerine karşı saygılı davrandı.'),
  w(T('Selamlaşma ve Tanışma'), 'rapport',         'uyum',             'isim',  'Building rapport takes time and consistency.',                   'Uyum kurmak zaman ve tutarlılık gerektirir.'),
  w(T('Selamlaşma ve Tanışma'), 'pleasantry',      'nezaket lafı',     'isim',  'They exchanged pleasantries before the meeting.',                'Toplantı öncesinde nezaket lafları ettiler.'),
  w(T('Selamlaşma ve Tanışma'), 'congenial',       'uyumlu',           'sıfat', 'She found the team very congenial.',                            'Takımı çok uyumlu buldu.'),
  w(T('Selamlaşma ve Tanışma'), 'sociable',        'girişken',         'sıfat', 'Sociable people adapt quickly to new environments.',             'Girişken insanlar yeni ortamlara hızla uyum sağlar.'),
  w(T('Selamlaşma ve Tanışma'), 'intercultural',   'kültürlerarası',   'sıfat', 'Intercultural communication is a key skill today.',              'Kültürlerarası iletişim günümüzde önemli bir beceridir.'),
  w(T('Selamlaşma ve Tanışma'), 'affable',         'güler yüzlü',      'sıfat', 'The receptionist was affable and welcoming.',                   'Resepsiyonist güler yüzlü ve sıcakkanlıydı.'),
  w(T('Selamlaşma ve Tanışma'), 'reciprocate',     'karşılık vermek',  'fiil',  'She reciprocated the kindness he had shown her.',                'Onun gösterdiği nezakete karşılık verdi.'),
  w(T('Selamlaşma ve Tanışma'), 'semblance',       'görünüş',          'isim',  'There was a semblance of normality after the storm.',             'Fırtınadan sonra bir normallik görünüşü vardı.'),
  w(T('Selamlaşma ve Tanışma'), 'amicable',        'dostane',          'sıfat', 'They reached an amicable agreement after the dispute.',          'Anlaşmazlıktan sonra dostane bir uzlaşmaya vardılar.'),
  w(T('Selamlaşma ve Tanışma'), 'convivial',       'neşeli',           'sıfat', 'The atmosphere at the party was convivial.',                     'Partideki atmosfer neşeliydi.'),
  w(T('Selamlaşma ve Tanışma'), 'overture',        'başlatma girişimi','isim',  'He made an overture of friendship.',                             'Dostluk başlatma girişiminde bulundu.'),

  // ── Sayılar (B2) ──────────────────────────────────────────────────────
  w(T('Sayılar'), 'logarithm',    'logaritma',     'isim',  'The logarithm of 100 to base 10 is 2.',          'Tabanı 10 olan 100\'ün logaritması 2\'dir.'),
  w(T('Sayılar'), 'asymptote',    'asimptot',      'isim',  'The graph approaches but never touches the asymptote.', 'Grafik asimptota yaklaşır ama asla dokunmaz.'),
  w(T('Sayılar'), 'permutation',  'permütasyon',   'isim',  'Calculate the number of permutations.',          'Permütasyon sayısını hesaplayın.'),
  w(T('Sayılar'), 'coefficient',  'katsayı',       'isim',  'The coefficient in front of x is 3.',            'x\'in önündeki katsayı 3\'tür.'),
  w(T('Sayılar'), 'magnitude',    'büyüklük',      'isim',  'The magnitude of the earthquake was 7.2.',       'Depremin büyüklüğü 7.2 idi.'),
  w(T('Sayılar'), 'cumulative',   'birikimli',     'sıfat', 'The cumulative total rose sharply this year.',   'Birikimli toplam bu yıl keskin biçimde arttı.'),
  w(T('Sayılar'), 'variance',     'varyans',       'isim',  'Statistical variance measures data spread.',     'İstatistiksel varyans, veri yayılımını ölçer.'),
  w(T('Sayılar'), 'interpolate',  'arasına eklemek','fiil', 'Interpolate the missing values in the dataset.', 'Veri setindeki eksik değerleri arasına ekleyin.'),
  w(T('Sayılar'), 'prime',        'asal',          'sıfat', '7 is a prime number.',                          '7 bir asal sayıdır.'),
  w(T('Sayılar'), 'cardinal',     'temel sayı',    'isim',  'Cardinal numbers express quantity.',              'Temel sayılar niceliği ifade eder.'),
  w(T('Sayılar'), 'ordinal',      'sıra sayısı',   'isim',  'First and second are ordinal numbers.',          'Birinci ve ikinci sıra sayılarıdır.'),
  w(T('Sayılar'), 'exponential',  'üstel',         'sıfat', 'The population grew at an exponential rate.',   'Nüfus üstel bir oranda büyüdü.'),
  w(T('Sayılar'), 'quotient',     'bölüm',         'isim',  'The quotient of 12 divided by 4 is 3.',         '12\'nin 4\'e bölümünün sonucu 3\'tür.'),
  w(T('Sayılar'), 'divisible',    'bölünebilir',   'sıfat', '10 is divisible by 2 and 5.',                   '10, 2 ve 5\'e bölünebilir.'),
  w(T('Sayılar'), 'tangential',   'teğetsel',      'sıfat', 'His comment was tangential to the main topic.', 'Yorumu ana konuya teğetseldi.'),
  w(T('Sayılar'), 'scalar',       'skaler',        'isim',  'A scalar quantity has magnitude but no direction.','Skaler büyüklüğün yönü yoktur, yalnızca değeri vardır.'),
  w(T('Sayılar'), 'iterate',      'yinelemek',     'fiil',  'The algorithm iterates until it finds the solution.', 'Algoritma çözümü bulana kadar yineler.'),
  w(T('Sayılar'), 'rounding',     'yuvarlama',     'isim',  'Rounding to the nearest ten gives 50.',         'En yakın ona yuvarlama 50 verir.'),
  w(T('Sayılar'), 'binary',       'ikili',         'sıfat', 'Computers operate on binary code.',              'Bilgisayarlar ikili kod üzerinde çalışır.'),
  w(T('Sayılar'), 'numeral',      'rakam',         'isim',  'Roman numerals are still used in some contexts.','Roma rakamları bazı bağlamlarda hâlâ kullanılır.'),

  // ── Renkler (B2) ──────────────────────────────────────────────────────
  w(T('Renkler'), 'iridescent',   'sedef renkli',  'sıfat', 'The butterfly wings were iridescent in the sunlight.', 'Kelebek kanatları güneş ışığında sedef renkli parlıyordu.'),
  w(T('Renkler'), 'chromatic',    'kromatik',      'sıfat', 'The chromatic scale includes all twelve tones.', 'Kromatik gam on iki tonu içerir.'),
  w(T('Renkler'), 'luminescent',  'ışıldayan',     'sıfat', 'Luminescent paint glows in the dark.',           'Işıldayan boya karanlıkta parlar.'),
  w(T('Renkler'), 'achromatic',   'renksiz',       'sıfat', 'Grey is considered an achromatic color.',        'Gri, renksiz bir renk olarak kabul edilir.'),
  w(T('Renkler'), 'polychrome',   'çok renkli',    'sıfat', 'The temple was decorated in polychrome tiles.',  'Tapınak çok renkli çinilerle süslenmişti.'),
  w(T('Renkler'), 'opalescent',   'opale benzer',  'sıfat', 'The opalescent glass shimmered beautifully.',    'Opale benzer cam güzelce parıldıyordu.'),
  w(T('Renkler'), 'umber',        'toprak rengi',  'isim',  'The landscape was painted in shades of umber.',  'Manzara toprak rengi tonlarıyla boyanmıştı.'),
  w(T('Renkler'), 'pellucid',     'berrak',        'sıfat', 'The pellucid water revealed the sandy bottom.',  'Berrak su kumlu tabanı ortaya koyuyordu.'),
  w(T('Renkler'), 'ebony',        'abanoz siyahı', 'isim',  'The piano keys were made of ebony.',             'Piyano tuşları abanoz ağacından yapılmıştı.'),
  w(T('Renkler'), 'aubergine',    'patlıcan moru', 'isim',  'She painted the wall a deep aubergine.',         'Duvarı derin bir patlıcan moruna boyadı.'),
  w(T('Renkler'), 'sienna',       'siena rengi',   'isim',  'Raw sienna is a warm earth tone.',               'Ham siena, sıcak bir toprak tonudur.'),
  w(T('Renkler'), 'monochromatic','tek renkli',    'sıfat', 'The photograph was monochromatic.',              'Fotoğraf tek renkliydi.'),
  w(T('Renkler'), 'fluorescent',  'floresan',      'sıfat', 'The workers wore fluorescent vests.',            'İşçiler floresan yelekler giymişti.'),
  w(T('Renkler'), 'translucent',  'yarı saydam',   'sıfat', 'The frosted glass was translucent.',             'Buzlu cam yarı saydamdı.'),
  w(T('Renkler'), 'variegated',   'alacalı',       'sıfat', 'The variegated leaves were striking.',           'Alacalı yapraklar çarpıcıydı.'),
  w(T('Renkler'), 'pigment',      'pigment',       'isim',  'Natural pigments were used for the dyes.',      'Boyalar için doğal pigmentler kullanıldı.'),
  w(T('Renkler'), 'oxidize',      'okside olmak',  'fiil',  'Copper oxidizes and turns green over time.',    'Bakır zamanla okside olur ve yeşile döner.'),
  w(T('Renkler'), 'spectrum',     'spektrum',      'isim',  'White light contains the full visible spectrum.','Beyaz ışık tam görünür spektrumu içerir.'),
  w(T('Renkler'), 'bistre',       'koyu kahverengi','isim', 'The sketch was done in bistre ink.',             'Eskiz koyu kahverengi mürekkeple yapılmıştı.'),
  w(T('Renkler'), 'wavelength',   'dalga boyu',    'isim',  'Different colors have different wavelengths.',  'Farklı renklerin farklı dalga boyları vardır.'),

  // ── Aile (B2) ─────────────────────────────────────────────────────────
  w(T('Aile'), 'patriarchy',      'ataerkillik',     'isim',  'Some cultures still operate under patriarchy.',    'Bazı kültürler hâlâ ataerkillik altında işler.'),
  w(T('Aile'), 'matriarch',       'aile reisi kadın','isim',  'The matriarch held the family together.',          'Aile reisi kadın aileyi bir arada tuttu.'),
  w(T('Aile'), 'consanguinity',   'kan bağı',        'isim',  'Consanguinity refers to blood relationships.',     'Kan bağı, kan akrabalığına atıfta bulunur.'),
  w(T('Aile'), 'filial',          'evlat',           'sıfat', 'Filial piety is deeply rooted in Asian culture.',  'Evlat saygısı Asya kültüründe derinden köklüdür.'),
  w(T('Aile'), 'surrogate',       'vekil',           'sıfat', 'She became a surrogate mother for the couple.',    'O çift için vekil anne oldu.'),
  w(T('Aile'), 'dynastic',        'hanedanlık',      'sıfat', 'Dynastic marriages were common in history.',       'Hanedanlık evlilikleri tarihte yaygındı.'),
  w(T('Aile'), 'bereavement',     'yas',             'isim',  'Bereavement counselling helped her cope.',         'Yas danışmanlığı başa çıkmasına yardımcı oldu.'),
  w(T('Aile'), 'cohabitation',    'birlikte yaşama', 'isim',  'Cohabitation rates have risen in recent years.',  'Son yıllarda birlikte yaşama oranları arttı.'),
  w(T('Aile'), 'alimony',         'nafaka',          'isim',  'He was ordered to pay alimony monthly.',           'Aylık nafaka ödemesi kararlaştırıldı.'),
  w(T('Aile'), 'maternity',       'annelik',         'isim',  'She took three months of maternity leave.',        'Üç ay annelik izni aldı.'),
  w(T('Aile'), 'paternalistic',   'babacan',         'sıfat', 'His paternalistic attitude annoyed his colleagues.','Babacan tutumu meslektaşlarını rahatsız etti.'),
  w(T('Aile'), 'sibling rivalry', 'kardeş rekabeti', 'isim',  'Sibling rivalry is common in large families.',    'Kardeş rekabeti kalabalık ailelerde yaygındır.'),
  w(T('Aile'), 'genealogy',       'soy ağacı',       'isim',  'He studied genealogy to trace his roots.',         'Köklerini bulmak için soy ağacını inceledi.'),
  w(T('Aile'), 'adoptive',        'evlat edinen',    'sıfat', 'Her adoptive parents raised her with love.',       'Evlat edinen ailesi onu sevgiyle yetiştirdi.'),
  w(T('Aile'), 'nuclear family',  'çekirdek aile',   'isim',  'The nuclear family is the most common household type.','Çekirdek aile en yaygın hane tipidir.'),
  w(T('Aile'), 'extended family', 'geniş aile',      'isim',  'They celebrated the holiday with their extended family.','Tatili geniş aileleriyle kutladılar.'),
  w(T('Aile'), 'emancipation',    'özgürleşme',      'isim',  'The emancipation of women changed family structures.','Kadınların özgürleşmesi aile yapılarını değiştirdi.'),
  w(T('Aile'), 'paternal',        'baba tarafı',     'sıfat', 'His paternal grandfather was a sailor.',           'Baba tarafı büyükbabası bir denizciydi.'),
  w(T('Aile'), 'maternal',        'anne tarafı',     'sıfat', 'Her maternal instincts were very strong.',         'Annelik içgüdüleri çok güçlüydü.'),
  w(T('Aile'), 'primogeniture',   'ilk doğan hakkı', 'isim',  'Primogeniture gave the firstborn all inheritance.','İlk doğan hakkı tüm mirası ilk çocuğa verdi.'),

  // ── Vücut (B2) ────────────────────────────────────────────────────────
  w(T('Vücut'), 'cortisol',       'kortizol',        'isim',  'Stress triggers the release of cortisol.',         'Stres kortizol salgılanmasını tetikler.'),
  w(T('Vücut'), 'synaptic',       'sinaptik',        'sıfat', 'Synaptic connections form the basis of memory.',   'Sinaptik bağlantılar hafızanın temelini oluşturur.'),
  w(T('Vücut'), 'mitochondria',   'mitokondri',      'isim',  'Mitochondria produce energy for cells.',           'Mitokondri, hücreler için enerji üretir.'),
  w(T('Vücut'), 'epithelial',     'epitel',          'sıfat', 'Epithelial cells line the inside of organs.',      'Epitel hücreler organların içini kaplar.'),
  w(T('Vücut'), 'tendon',         'tendon',          'isim',  'The tendon connects muscle to bone.',              'Tendon kası kemiğe bağlar.'),
  w(T('Vücut'), 'ligament',       'bağ dokusu',      'isim',  'She tore a ligament in her knee during the race.', 'Yarışta dizindeki bağ dokusunu yırttı.'),
  w(T('Vücut'), 'platelet',       'trombosit',       'isim',  'Platelets help blood to clot after injury.',       'Trombositler yaralanma sonrası kanın pıhtılaşmasına yardımcı olur.'),
  w(T('Vücut'), 'lymph',          'lenf',            'isim',  'Lymph nodes filter harmful substances.',           'Lenf düğümleri zararlı maddeleri filtreler.'),
  w(T('Vücut'), 'cochlea',        'salyangoz',       'isim',  'The cochlea is responsible for hearing.',          'Salyangoz, işitmeden sorumludur.'),
  w(T('Vücut'), 'retina',         'retina',          'isim',  'The retina converts light into nerve signals.',    'Retina ışığı sinir sinyallerine dönüştürür.'),
  w(T('Vücut'), 'diaphragm',      'diyafram',        'isim',  'The diaphragm controls breathing.',                'Diyafram solunumu kontrol eder.'),
  w(T('Vücut'), 'adrenaline',     'adrenalin',       'isim',  'Adrenaline prepares the body for danger.',         'Adrenalin vücudu tehlikeye hazırlar.'),
  w(T('Vücut'), 'marrow',         'kemik iliği',     'isim',  'Bone marrow produces blood cells.',                'Kemik iliği kan hücreleri üretir.'),
  w(T('Vücut'), 'ganglion',       'ganglion',        'isim',  'A ganglion is a cluster of nerve cells.',          'Ganglion, sinir hücrelerinden oluşan bir kümedir.'),
  w(T('Vücut'), 'peristalsis',    'peristaltizm',    'isim',  'Peristalsis moves food through the digestive tract.','Peristaltizm yiyeceği sindirim kanalından taşır.'),
  w(T('Vücut'), 'epidermis',      'epidermis',       'isim',  'The epidermis is the outermost skin layer.',       'Epidermis, derinin en dış katmanıdır.'),
  w(T('Vücut'), 'ossification',   'kemikleşme',      'isim',  'Ossification hardens cartilage into bone.',        'Kemikleşme kıkırdağı kemiğe dönüştürür.'),
  w(T('Vücut'), 'proprioception', 'propriyosepsiyon','isim',  'Proprioception helps us sense body position.',     'Propriyosepsiyon beden konumunu algılamamıza yardımcı olur.'),
  w(T('Vücut'), 'capillary',      'kılcal damar',    'isim',  'Oxygen passes through capillary walls to cells.',  'Oksijen kılcal damar duvarlarından hücrelere geçer.'),
  w(T('Vücut'), 'eardrum',        'kulak zarı',      'isim',  'A ruptured eardrum causes temporary hearing loss.','Yırtık kulak zarı geçici işitme kaybına yol açar.'),

  // ── Yiyecekler (B2) ───────────────────────────────────────────────────
  w(T('Yiyecekler'), 'umami',          'umami',            'isim',  'Umami is described as the fifth taste.',            'Umami beşinci tat olarak tanımlanır.'),
  w(T('Yiyecekler'), 'emulsify',       'emülsifiye etmek', 'fiil',  'Whisk the oil slowly to emulsify it.',             'Yağı emülsifiye etmek için yavaşça çırpın.'),
  w(T('Yiyecekler'), 'blanch',         'haşlamak',         'fiil',  'Blanch the vegetables before freezing them.',      'Dondurmadan önce sebzeleri haşlayın.'),
  w(T('Yiyecekler'), 'reduce',         'koyulaştırmak',    'fiil',  'Reduce the sauce until it thickens.',              'Sos koyulaşana kadar kaynatın.'),
  w(T('Yiyecekler'), 'caramelise',     'karamelize etmek', 'fiil',  'Caramelise the onions over low heat.',             'Soğanları düşük ısıda karamelize edin.'),
  w(T('Yiyecekler'), 'infuse',         'demlemek',         'fiil',  'Infuse the herbs in hot oil for five minutes.',    'Bitkileri beş dakika sıcak yağda demleyin.'),
  w(T('Yiyecekler'), 'molecular',      'moleküler',        'sıfat', 'Molecular gastronomy uses science in cooking.',    'Moleküler gastronomi mutfakta bilimi kullanır.'),
  w(T('Yiyecekler'), 'gluten',         'glüten',           'isim',  'Some people are intolerant to gluten.',            'Bazı insanlar glütene tahammülsüzdür.'),
  w(T('Yiyecekler'), 'probiotics',     'probiyotik',       'isim',  'Probiotics support gut health.',                   'Probiyotikler bağırsak sağlığını destekler.'),
  w(T('Yiyecekler'), 'delicacy',       'nefaset',          'isim',  'Truffles are considered a rare delicacy.',         'Trüfler nadir bir nefaset olarak kabul edilir.'),
  w(T('Yiyecekler'), 'foraging',       'yiyecek arama',    'isim',  'Foraging for wild mushrooms requires expertise.',  'Yabani mantar aramak uzmanlık gerektirir.'),
  w(T('Yiyecekler'), 'gastronomy',     'gastronomi',       'isim',  'She studied gastronomy in Paris.',                 'Paris\'te gastronomi okudu.'),
  w(T('Yiyecekler'), 'dehydrate',      'kurutmak',         'fiil',  'Dehydrate the fruit to preserve it longer.',       'Meyveyi daha uzun süre korumak için kurutun.'),
  w(T('Yiyecekler'), 'artisanal',      'el yapımı',        'sıfat', 'Artisanal bread is made in small batches.',       'El yapımı ekmek küçük miktarlarda üretilir.'),
  w(T('Yiyecekler'), 'palate',         'damak tadı',       'isim',  'He has a refined palate for wine.',                'Şarap için rafine bir damak tadına sahiptir.'),
  w(T('Yiyecekler'), 'cholesterol',    'kolesterol',       'isim',  'High cholesterol increases heart disease risk.',   'Yüksek kolesterol kalp hastalığı riskini artırır.'),
  w(T('Yiyecekler'), 'gelatine',       'jelatin',          'isim',  'Gelatine is used to set jellies and desserts.',    'Jelatin, jelatinleri ve tatlıları katılaştırmak için kullanılır.'),
  w(T('Yiyecekler'), 'brine',          'salamura',         'isim',  'Soak the chicken in brine overnight.',             'Tavuğu bir gece salamurada bekletin.'),
  w(T('Yiyecekler'), 'macerate',       'bekletmek',        'fiil',  'Macerate the fruit in sugar for an hour.',         'Meyveyi bir saat şeker içinde bekletin.'),
  w(T('Yiyecekler'), 'epicure',        'gurme',            'isim',  'An epicure savors fine food and wine.',            'Gurme, kaliteli yiyecek ve şarabın tadını çıkarır.'),

  // ── Giyim (B2) ────────────────────────────────────────────────────────
  w(T('Giyim'), 'couture',          'yüksek moda',     'isim',  'Haute couture is made exclusively for the client.', 'Yüksek moda, yalnızca müşteri için yapılır.'),
  w(T('Giyim'), 'drape',            'döküm',           'isim',  'The dress had a beautiful drape.',                  'Elbisenin güzel bir dökümü vardı.'),
  w(T('Giyim'), 'motif',            'desen',           'isim',  'The fabric featured a floral motif.',               'Kumaşta çiçek desenli bir motif vardı.'),
  w(T('Giyim'), 'brocade',          'brokar',          'isim',  'She wore a brocade jacket to the gala.',            'Galaya brokar bir ceket giydi.'),
  w(T('Giyim'), 'silhouette',       'siluet',          'isim',  'The silhouette of the dress was very sleek.',       'Elbisenin silueti çok şıktı.'),
  w(T('Giyim'), 'lapel',            'yaka',            'isim',  'The lapel on his jacket was wide.',                 'Ceketinin yakası genişti.'),
  w(T('Giyim'), 'gorge',            'yaka çizgisi',    'isim',  'The gorge of the suit jacket was well-tailored.',   'Takım ceketinin yaka çizgisi iyi dikilmişti.'),
  w(T('Giyim'), 'pilling',          'topaklanma',      'isim',  'Pilling occurs when fabric fibres clump together.', 'Topaklanma, kumaş lifleri bir araya geldiğinde oluşur.'),
  w(T('Giyim'), 'mercerize',        'merseri yapmak',  'fiil',  'Mercerized cotton is stronger and shinier.',        'Merseri pamuk daha sağlam ve parlaktır.'),
  w(T('Giyim'), 'sartorial',        'terziye ait',     'sıfat', 'He was known for his sartorial elegance.',         'Terziye yakışır zarafetiyle tanınırdı.'),
  w(T('Giyim'), 'toile',            'prova kumaşı',    'isim',  'A toile is a trial garment made before the real one.','Toile, gerçeğinden önce yapılan bir deneme giysisidir.'),
  w(T('Giyim'), 'pleat',            'pile',            'isim',  'The trousers had sharp pleats at the front.',       'Pantolonun önünde keskin pileler vardı.'),
  w(T('Giyim'), 'welt',             'dikiş kenarı',    'isim',  'The welt on the boot was hand-stitched.',           'Çizmedeki dikiş kenarı elle dikilmişti.'),
  w(T('Giyim'), 'avant-garde',      'öncü',            'sıfat', 'Her fashion choices were avant-garde.',             'Moda seçimleri öncüydü.'),
  w(T('Giyim'), 'prêt-à-porter',    'hazır giyim',     'isim',  'The brand sells both prêt-à-porter and couture.',  'Marka hem hazır giyim hem yüksek moda satıyor.'),
  w(T('Giyim'), 'mercantile',       'ticari',          'sıfat', 'The mercantile success of the brand was remarkable.','Markanın ticari başarısı dikkat çekiciydi.'),
  w(T('Giyim'), 'epaulette',        'apolet',          'isim',  'The uniform had golden epaulettes.',                'Üniforma altın apoletlere sahipti.'),
  w(T('Giyim'), 'tweed',            'tüvit',           'isim',  'The tweed jacket was ideal for cool weather.',     'Tüvit ceket serin hava için idealdi.'),
  w(T('Giyim'), 'ruche',            'büzgü',           'isim',  'The blouse had a ruche along the neckline.',        'Bluzun yakası boyunca büzgü vardı.'),
  w(T('Giyim'), 'appliqué',         'aplike',          'isim',  'The dress was adorned with floral appliqué.',       'Elbise çiçek aplikeleriyle süslenmişti.'),

  // ── Ev ve Mobilya (B2) ────────────────────────────────────────────────
  w(T('Ev ve Mobilya'), 'ergonomic',     'ergonomik',       'sıfat', 'An ergonomic chair reduces back strain.',          'Ergonomik sandalye sırt gerginliğini azaltır.'),
  w(T('Ev ve Mobilya'), 'minimalist',    'minimalist',      'sıfat', 'She prefers a minimalist interior design.',        'Minimalist iç tasarımı tercih eder.'),
  w(T('Ev ve Mobilya'), 'cantilevered',  'konsol',          'sıfat', 'The cantilevered balcony overlooked the sea.',     'Konsol balkon denize bakıyordu.'),
  w(T('Ev ve Mobilya'), 'parquet',       'parke',           'isim',  'The living room had a beautiful parquet floor.',   'Oturma odasında güzel bir parke zemin vardı.'),
  w(T('Ev ve Mobilya'), 'mezzanine',     'asma kat',        'isim',  'The mezzanine level had a small library.',         'Asma katta küçük bir kütüphane vardı.'),
  w(T('Ev ve Mobilya'), 'eaves',         'saçak',           'isim',  'Water dripped from the eaves during the storm.',   'Fırtına sırasında saçaktan su damladı.'),
  w(T('Ev ve Mobilya'), 'corbel',        'konsol taşı',     'isim',  'Stone corbels supported the upper floor.',         'Taş konsol taşları üst katı destekliyordu.'),
  w(T('Ev ve Mobilya'), 'coping',        'duvar tacı',      'isim',  'The coping on the wall prevented water damage.',   'Duvar tacı su hasarını önledi.'),
  w(T('Ev ve Mobilya'), 'caulk',         'macun doldurmak', 'fiil',  'Caulk the gaps around the bathtub.',               'Küvet etrafındaki boşlukları macunla doldurun.'),
  w(T('Ev ve Mobilya'), 'joinery',       'doğrama işleri',  'isim',  'Fine joinery was used throughout the house.',      'Evin her yerine güzel doğrama işleri yapıldı.'),
  w(T('Ev ve Mobilya'), 'skirting',      'süpürgelik',      'isim',  'The skirting boards were painted white.',          'Süpürgelikler beyaza boyandı.'),
  w(T('Ev ve Mobilya'), 'load-bearing',  'yük taşıyan',     'sıfat', 'Do not remove load-bearing walls.',               'Yük taşıyan duvarları kaldırmayın.'),
  w(T('Ev ve Mobilya'), 'cornice',       'korniş',          'isim',  'The ornate cornice framed the ceiling beautifully.','Süslü korniş tavanı güzelce çerçeveledi.'),
  w(T('Ev ve Mobilya'), 'dormer',        'çatı penceresi',  'isim',  'The dormer window let in natural light.',          'Çatı penceresi doğal ışık aldı.'),
  w(T('Ev ve Mobilya'), 'wainscoting',   'ahşap kaplama',   'isim',  'Wainscoting added character to the room.',         'Ahşap kaplama odaya karakter kattı.'),
  w(T('Ev ve Mobilya'), 'buttress',      'payanda',         'isim',  'Flying buttresses support the cathedral walls.',   'Uçan payandalar katedralin duvarlarını destekler.'),
  w(T('Ev ve Mobilya'), 'cladding',      'kaplama',         'isim',  'Timber cladding was used on the exterior.',        'Dış cephe için ahşap kaplama kullanıldı.'),
  w(T('Ev ve Mobilya'), 'fascia',        'ön yüz',          'isim',  'The fascia board sealed the roof edge.',           'Ön yüz tahtası çatı kenarını kapattı.'),
  w(T('Ev ve Mobilya'), 'lintel',        'lento',           'isim',  'The lintel above the door was made of stone.',     'Kapının üzerindeki lento taştan yapılmıştı.'),
  w(T('Ev ve Mobilya'), 'glazing',       'cam kaplama',     'isim',  'Double glazing improves energy efficiency.',       'Çift cam kaplama enerji verimliliğini artırır.'),

  // ── Hayvanlar (B2) ────────────────────────────────────────────────────
  w(T('Hayvanlar'), 'symbiosis',      'simbiyoz',           'isim',  'The clownfish and anemone live in symbiosis.',     'Palyaço balığı ve anemon simbiyoz içinde yaşar.'),
  w(T('Hayvanlar'), 'bioluminescence','biyolüminesans',     'isim',  'Deep-sea creatures use bioluminescence to communicate.','Derin deniz canlıları iletişim için biyolüminesans kullanır.'),
  w(T('Hayvanlar'), 'cryptic',        'gizli',              'sıfat', 'The cryptic coloring of the moth hid it perfectly.','Güvenin gizli renklenmesi onu mükemmel şekilde sakladı.'),
  w(T('Hayvanlar'), 'crepuscular',    'alacakaranlıkta aktif','sıfat','Deer are crepuscular, most active at dawn and dusk.','Geyikler alacakaranlık saatlerinde en aktif hayvanlardır.'),
  w(T('Hayvanlar'), 'troglodytic',     'mağara yaşamlı',     'sıfat', 'Troglodytic animals live exclusively in caves.',   'Mağara yaşamlı hayvanlar yalnızca mağaralarda yaşar.'),
  w(T('Hayvanlar'), 'apex predator',  'zincir tepesi',      'isim',  'Sharks are apex predators in the ocean.',          'Köpek balıkları okyanusun zincir tepesi yırtıcılarıdır.'),
  w(T('Hayvanlar'), 'molting',        'tüy dökme',          'isim',  'Snakes undergo molting to shed their skin.',       'Yılanlar derisini dökmek için tüy dökme sürecinden geçer.'),
  w(T('Hayvanlar'), 'scavenger',      'leşçi',              'isim',  'Vultures are nature\'s primary scavengers.',       'Akbabalar doğanın birincil leşçileridir.'),
  w(T('Hayvanlar'), 'pheromone',      'feromon',            'isim',  'Ants use pheromones to communicate.',              'Karıncalar iletişim için feromon kullanır.'),
  w(T('Hayvanlar'), 'phenotype',       'fenotip',            'isim',  'The phenotype is the visible trait of an organism.','Fenotip, bir organizmanın görünür özelliğidir.'),
  w(T('Hayvanlar'), 'polymorphism',   'polimorfizm',        'isim',  'Polymorphism allows one species to have multiple forms.','Polimorfizm bir türün birden fazla forma sahip olmasına izin verir.'),
  w(T('Hayvanlar'), 'aestivation',    'yaz uykusu',         'isim',  'Lungfish enter aestivation during dry seasons.',   'Akciğer balığı kuru mevsimlerde yaz uykusuna girer.'),
  w(T('Hayvanlar'), 'echolocation',   'ekolokasyon',        'isim',  'Bats use echolocation to navigate in the dark.',   'Yarasalar karanlıkta yön bulmak için ekolokasyon kullanır.'),
  w(T('Hayvanlar'), 'cryptozoology',  'kriptozooji',        'isim',  'Cryptozoology studies unknown animal species.',    'Kriptozooji bilinmeyen hayvan türlerini inceler.'),
  w(T('Hayvanlar'), 'parthenogenesis','partenogenez',       'isim',  'Some reptiles reproduce via parthenogenesis.',     'Bazı sürüngenler partenogenez yoluyla ürer.'),
  w(T('Hayvanlar'), 'mutualism',      'karşılıklı yarar',   'isim',  'Mutualism benefits both species involved.',        'Karşılıklı yarar, ilgili her iki türe de fayda sağlar.'),
  w(T('Hayvanlar'), 'arboreal',       'ağaçlık',            'sıfat', 'Koalas are arboreal animals.',                     'Koalalar ağaçlık ortamlarda yaşayan hayvanlardır.'),
  w(T('Hayvanlar'), 'obligate',       'zorunlu',            'sıfat', 'Cats are obligate carnivores.',                    'Kediler zorunlu etçillerdir.'),
  w(T('Hayvanlar'), 'xenobiotic',     'yabancı madde',      'isim',  'Xenobiotics are substances foreign to organisms.', 'Yabancı maddeler, organizmalara yabancı olan maddelerdir.'),
  w(T('Hayvanlar'), 'bipedal',        'iki ayaklı',         'sıfat', 'Humans and some dinosaurs were bipedal.',          'İnsanlar ve bazı dinozorlar iki ayaklıydı.'),

  // ── Günlük Fiiller (B2) ───────────────────────────────────────────────
  w(T('Günlük Fiiller'), 'deliberate',  'kasıtlı',         'sıfat', 'Her decision was careful and deliberate.',         'Kararı dikkatli ve kasıtlıydı.'),
  w(T('Günlük Fiiller'), 'juxtapose',   'yan yana koymak', 'fiil',  'The exhibition juxtaposed old and new art.',       'Sergi eski ve yeni sanatı yan yana koydu.'),
  w(T('Günlük Fiiller'), 'scrutinize',  'dikkatle incelemek','fiil','He scrutinized the contract before signing.',      'İmzalamadan önce sözleşmeyi dikkatle inceledi.'),
  w(T('Günlük Fiiller'), 'mitigate',    'hafifletmek',     'fiil',  'Trees help mitigate the effects of pollution.',    'Ağaçlar kirliliğin etkilerini hafifletmeye yardımcı olur.'),
  w(T('Günlük Fiiller'), 'perpetuate',  'sürdürmek',       'fiil',  'Stereotypes perpetuate social inequality.',        'Kalıp yargılar toplumsal eşitsizliği sürdürür.'),
  w(T('Günlük Fiiller'), 'relinquish',  'bırakmak',        'fiil',  'He relinquished his claim to the throne.',         'Tahta olan hakkından vazgeçti.'),
  w(T('Günlük Fiiller'), 'exacerbate',  'kötüleştirmek',   'fiil',  'Pollution exacerbates respiratory illnesses.',     'Kirlilik solunum hastalıklarını kötüleştirir.'),
  w(T('Günlük Fiiller'), 'embody',      'somutlaştırmak',  'fiil',  'The sculpture embodies the spirit of freedom.',    'Heykel özgürlük ruhunu somutlaştırıyor.'),
  w(T('Günlük Fiiller'), 'circumvent',  'atlatmak',        'fiil',  'He tried to circumvent the regulations.',          'Düzenlemeleri atlatmaya çalıştı.'),
  w(T('Günlük Fiiller'), 'corroborate', 'doğrulamak',      'fiil',  'Evidence corroborated the witness statement.',     'Kanıtlar tanık ifadesini doğruladı.'),
  w(T('Günlük Fiiller'), 'extrapolate', 'dışarıya aktarmak','fiil', 'We can extrapolate future trends from the data.',  'Verilerden gelecekteki eğilimleri çıkarabiliriz.'),
  w(T('Günlük Fiiller'), 'instigate',   'kışkırtmak',      'fiil',  'He instigated the argument between the two teams.','İki takım arasındaki tartışmayı kışkırttı.'),
  w(T('Günlük Fiiller'), 'retaliate',   'misillemede bulunmak','fiil','He retaliated after the unfair attack.',           'Haksız saldırıdan sonra misillemede bulundu.'),
  w(T('Günlük Fiiller'), 'vindicate',   'haklı çıkarmak',  'fiil',  'The verdict vindicated the accused.',              'Karar sanığı haklı çıkardı.'),
  w(T('Günlük Fiiller'), 'exonerate',   'aklamak',         'fiil',  'New evidence exonerated the suspect.',             'Yeni kanıtlar şüpheliyi akladı.'),
  w(T('Günlük Fiiller'), 'enunciate',   'açıkça dile getirmek','fiil','He enunciated his concerns clearly in the meeting.','Toplantıda endişelerini açıkça dile getirdi.'),
  w(T('Günlük Fiiller'), 'alleviate',   'gidermek',        'fiil',  'Exercise can alleviate symptoms of depression.',   'Egzersiz depresyon belirtilerini giderebilir.'),
  w(T('Günlük Fiiller'), 'contravene',  'ihlal etmek',     'fiil',  'The policy contravened human rights laws.',        'Politika insan hakları yasalarını ihlal etti.'),
  w(T('Günlük Fiiller'), 'synthesize',  'sentezlemek',     'fiil',  'Researchers synthesize new compounds in the lab.', 'Araştırmacılar laboratuvarda yeni bileşikler sentezler.'),
  w(T('Günlük Fiiller'), 'capitulate',  'teslim olmak',    'fiil',  'The company capitulated to public pressure.',      'Şirket kamuoyu baskısına teslim oldu.'),

  // ── Doğa ve Hava (B2) ─────────────────────────────────────────────────
  w(T('Doğa ve Hava'), 'permafrost',   'kalıcı donmuş toprak','isim','Permafrost is thawing due to global warming.',    'Kalıcı donmuş toprak küresel ısınma nedeniyle eriyor.'),
  w(T('Doğa ve Hava'), 'catchment',    'su toplama havzası','isim', 'The catchment area feeds the river downstream.',   'Su toplama havzası aşağı akışta nehri besler.'),
  w(T('Doğa ve Hava'), 'lithosphere',  'litosfer',          'isim', 'The lithosphere includes Earth\'s crust.',         'Litosfer, Dünya\'nın kabuğunu içerir.'),
  w(T('Doğa ve Hava'), 'stratosphere', 'stratosfer',        'isim', 'The ozone layer is in the stratosphere.',          'Ozon tabakası stratosferde yer alır.'),
  w(T('Doğa ve Hava'), 'anthropogenic','insan kaynaklı',    'sıfat','Anthropogenic emissions cause climate change.',    'İnsan kaynaklı emisyonlar iklim değişikliğine yol açar.'),
  w(T('Doğa ve Hava'), 'geomorphology','jeomorfoloji',      'isim', 'Geomorphology studies landform processes.',        'Jeomorfoloji, yer şekli süreçlerini inceler.'),
  w(T('Doğa ve Hava'), 'mangrove',     'mangrov',           'isim', 'Mangrove forests protect coastlines from erosion.','Mangrov ormanları kıyıları erozyondan korur.'),
  w(T('Doğa ve Hava'), 'aquifer',      'akifer',            'isim', 'Many cities rely on aquifers for drinking water.', 'Birçok şehir içme suyu için akiferlere güvenir.'),
  w(T('Doğa ve Hava'), 'hydrological', 'hidrolojik',        'sıfat','The hydrological cycle regulates water on Earth.','Hidrolojik döngü, Dünya\'daki suyu düzenler.'),
  w(T('Doğa ve Hava'), 'sediment',     'tortu',             'isim', 'River sediment builds up at the delta.',           'Nehir tortusu deltada birikir.'),
  w(T('Doğa ve Hava'), 'biome',        'biyom',             'isim', 'The Amazon is the world\'s largest tropical biome.','Amazon, dünyanın en büyük tropikal biyomudur.'),
  w(T('Doğa ve Hava'), 'tectonic',     'tektonik',          'sıfat','Tectonic movement causes earthquakes.',            'Tektonik hareket depremlere neden olur.'),
  w(T('Doğa ve Hava'), 'cyclone',      'siklon',            'isim', 'A powerful cyclone hit the coast last night.',     'Güçlü bir siklon dün gece kıyıya çarptı.'),
  w(T('Doğa ve Hava'), 'albedo',       'albedo',            'isim', 'Ice has a high albedo, reflecting sunlight.',      'Buz, güneş ışığını yansıtan yüksek bir albedoya sahiptir.'),
  w(T('Doğa ve Hava'), 'sublimation',  'süblimleşme',       'isim', 'Dry ice undergoes sublimation at room temperature.','Kuru buz oda sıcaklığında süblimleşmeye uğrar.'),
  w(T('Doğa ve Hava'), 'particulate',  'partiküllü',        'sıfat','Particulate matter in air causes lung disease.',   'Havadaki partiküllü madde akciğer hastalığına yol açar.'),
  w(T('Doğa ve Hava'), 'vortex',       'girdap',            'isim', 'The tornado formed a powerful vortex.',            'Tornado güçlü bir girdap oluşturdu.'),
  w(T('Doğa ve Hava'), 'turbulence',   'türbülans',         'isim', 'Atmospheric turbulence disrupted the flight.',     'Atmosferik türbülans uçuşu engelledi.'),
  w(T('Doğa ve Hava'), 'eutrophication','ötrofikasyon',     'isim', 'Eutrophication depletes oxygen in water bodies.',  'Ötrofikasyon su kütlelerindeki oksijeni tüketir.'),
  w(T('Doğa ve Hava'), 'intertidal',   'gelgit arası',      'sıfat','Intertidal zones are home to many species.',       'Gelgit arası bölgeler birçok türe ev sahipliği yapar.'),

  // ── Günler, Aylar, Mevsimler (B2) ─────────────────────────────────────
  w(T('Günler, Aylar, Mevsimler'), 'synchronize',   'senkronize etmek','fiil', 'Synchronize your calendar with the team.',       'Takviminizi ekiple senkronize edin.'),
  w(T('Günler, Aylar, Mevsimler'), 'iterative',     'döngüsel',      'sıfat', 'Climate change creates iterative extreme weather cycles.','İklim değişikliği döngüsel aşırı hava döngüleri yaratır.'),
  w(T('Günler, Aylar, Mevsimler'), 'circadian',     'sirkadiyen',    'sıfat', 'Circadian rhythms regulate sleep and waking.',  'Sirkadiyen ritimler uyku ve uyanıklığı düzenler.'),
  w(T('Günler, Aylar, Mevsimler'), 'quotidian',     'gündelik',      'sıfat', 'Quotidian routines help maintain order.',        'Gündelik rutinler düzeni korumaya yardımcı olur.'),
  w(T('Günler, Aylar, Mevsimler'), 'phenology',     'fenoloji',      'isim',  'Phenology studies seasonal natural phenomena.',  'Fenoloji mevsimsel doğal olayları inceler.'),
  w(T('Günler, Aylar, Mevsimler'), 'centennial',    'yüzyıllık',     'sıfat', 'The centennial celebration attracted thousands.','Yüzyıllık kutlama binlerce kişiyi çekti.'),
  w(T('Günler, Aylar, Mevsimler'), 'biennial',      'iki yılda bir', 'sıfat', 'The biennial festival was held last summer.',    'İki yılda bir düzenlenen festival geçen yaz yapıldı.'),
  w(T('Günler, Aylar, Mevsimler'), 'transitory',    'geçici',        'sıfat', 'Fame is often transitory.',                      'Şöhret çoğu zaman geçicidir.'),
  w(T('Günler, Aylar, Mevsimler'), 'bygone',        'geçmişe ait',   'sıfat', 'She recalled the bygone days of her youth.',    'Gençliğinin geçmişe ait günlerini hatırladı.'),
  w(T('Günler, Aylar, Mevsimler'), 'contemporaneous','eş zamanlı',   'sıfat', 'The two events were contemporaneous.',          'İki olay eş zamanlıydı.'),
  w(T('Günler, Aylar, Mevsimler'), 'intercalary',   'artık',         'sıfat', 'An intercalary day is added in leap years.',    'Artık yıllarda artık bir gün eklenir.'),
  w(T('Günler, Aylar, Mevsimler'), 'meridian',      'meridyen',      'isim',  'Time zones are calculated from the prime meridian.','Saat dilimleri başlangıç meridyeninden hesaplanır.'),
  w(T('Günler, Aylar, Mevsimler'), 'antediluvian',  'tufandan önceki','sıfat','His views seemed antediluvian to modern thinkers.','Görüşleri modern düşünürlere tufandan önceki gibi görünüyordu.'),
  w(T('Günler, Aylar, Mevsimler'), 'anachronism',   'anakronizm',    'isim',  'Using a fax machine today is an anachronism.',  'Bugün faks makinesi kullanmak bir anakronizmdir.'),
  w(T('Günler, Aylar, Mevsimler'), 'vernal',        'ilkbahara ait', 'sıfat', 'The vernal equinox marks the start of spring.', 'Vernal ekinoks ilkbaharın başlangıcını işaret eder.'),
  w(T('Günler, Aylar, Mevsimler'), 'autumnal',      'sonbahara ait', 'sıfat', 'The autumnal colors of the leaves were vivid.',  'Yaprakların sonbahar renkleri canlıydı.'),
  w(T('Günler, Aylar, Mevsimler'), 'nocturne',      'gece parçası',  'isim',  'He composed a haunting nocturne.',              'Büyüleyici bir gece parçası besteledi.'),
  w(T('Günler, Aylar, Mevsimler'), 'recurrence',    'tekrarlanma',   'isim',  'The recurrence of the event was predictable.',  'Olayın tekrarlanması öngörülebilirdi.'),
  w(T('Günler, Aylar, Mevsimler'), 'penultimate',   'sondan bir önceki','sıfat','This is the penultimate chapter of the book.','Bu kitabın sondan bir önceki bölümüdür.'),
  w(T('Günler, Aylar, Mevsimler'), 'hourly',        'saatlik',       'sıfat', 'Hourly weather updates were broadcast.',         'Saatlik hava güncellemeleri yayınlandı.'),

  // ── Zaman (B2) ────────────────────────────────────────────────────────
  w(T('Zaman'), 'temporal',       'zamansal',        'sıfat', 'There is a temporal gap between cause and effect.','Sebep ve sonuç arasında zamansal bir boşluk vardır.'),
  w(T('Zaman'), 'anachronistic',  'zamana aykırı',   'sıfat', 'The costume was anachronistic for the period.',   'Kostüm o döneme göre zamana aykırıydı.'),
  w(T('Zaman'), 'transient',      'geçici',          'sıfat', 'The pain was transient and disappeared quickly.', 'Acı geçiciydi ve hızla geçti.'),
  w(T('Zaman'), 'protracted',     'uzatılmış',       'sıfat', 'The protracted negotiations finally concluded.',  'Uzatılmış müzakereler sonunda tamamlandı.'),
  w(T('Zaman'), 'inveterate',     'köklü',           'sıfat', 'Traffic congestion is an inveterate urban problem.','Trafik tıkanıklığı köklü bir kentsel sorundur.'),
  w(T('Zaman'), 'hiatus',         'ara',             'isim',  'The band returned after a two-year hiatus.',      'Grup iki yıllık bir aradan sonra geri döndü.'),
  w(T('Zaman'), 'watershed',      'dönüm noktası',   'isim',  'The invention of the internet was a watershed moment.','İnternetin icadı bir dönüm noktasıydı.'),
  w(T('Zaman'), 'deferred',       'ertelenmiş',      'sıfat', 'The deferred payment plan helped many customers.','Ertelenmiş ödeme planı birçok müşteriye yardımcı oldu.'),
  w(T('Zaman'), 'antecedent',     'önceki',          'sıfat', 'The antecedent events led to the conflict.',     'Önceki olaylar çatışmaya yol açtı.'),
  w(T('Zaman'), 'lacuna',         'boşluk',          'isim',  'There is a lacuna in our knowledge of that period.','O döneme dair bilgimizde bir boşluk var.'),
  w(T('Zaman'), 'brevity',        'kısalık',         'isim',  'The brevity of the speech was appreciated.',     'Konuşmanın kısalığı takdirle karşılandı.'),
  w(T('Zaman'), 'perpetuity',     'sonsuza dek',     'isim',  'The land was given to the community in perpetuity.','Arazi sonsuza dek topluluğa verildi.'),
  w(T('Zaman'), 'nascent',        'henüz doğmakta',  'sıfat', 'The nascent industry needed support.',           'Henüz doğmakta olan sektör desteğe ihtiyaç duyuyordu.'),
  w(T('Zaman'), 'interlude',      'ara bölüm',       'isim',  'The peaceful interlude was short-lived.',        'Huzurlu ara bölüm kısa sürdü.'),
  w(T('Zaman'), 'epoch-making',   'çağ açan',        'sıfat', 'The discovery was epoch-making in science.',     'Keşif bilimde çağ açıcıydı.'),
  w(T('Zaman'), 'stasis',         'durağanlık',      'isim',  'The economy remained in a state of stasis.',     'Ekonomi bir durağanlık halinde kaldı.'),
  w(T('Zaman'), 'turnaround',     'toparlanma',      'isim',  'The company achieved a remarkable turnaround.',  'Şirket dikkat çekici bir toparlanma sağladı.'),
  w(T('Zaman'), 'flux',           'değişkenlik',     'isim',  'Society is in a constant state of flux.',        'Toplum sürekli bir değişkenlik halindedir.'),
  w(T('Zaman'), 'abrupt',         'ani',             'sıfat', 'There was an abrupt change in the weather.',     'Havada ani bir değişiklik oldu.'),
  w(T('Zaman'), 'evanescent',     'anlık',           'sıfat', 'The beauty of cherry blossoms is evanescent.',  'Kiraz çiçeklerinin güzelliği anlıktır.'),

  // ── Ulaşım (B2) ───────────────────────────────────────────────────────
  w(T('Ulaşım'), 'aerodynamic',   'aerodinamik',     'sıfat', 'The car has a highly aerodynamic design.',       'Arabanın son derece aerodinamik bir tasarımı var.'),
  w(T('Ulaşım'), 'propulsion',    'itici güç',       'isim',  'Jet propulsion powers modern aircraft.',         'Jet itici gücü modern uçakları güçlendirir.'),
  w(T('Ulaşım'), 'axle',          'aks',             'isim',  'The front axle was damaged in the accident.',    'Ön aks kazada hasar gördü.'),
  w(T('Ulaşım'), 'chassis',       'şasi',            'isim',  'The chassis of the truck was reinforced.',       'Kamyonun şasisi güçlendirildi.'),
  w(T('Ulaşım'), 'viaduct',       'viyadük',         'isim',  'The viaduct carries traffic over the valley.',   'Viyadük, trafiği vadinin üzerinden taşır.'),
  w(T('Ulaşım'), 'embankment',    'set',             'isim',  'The railway embankment runs along the river.',   'Demiryolu seti nehir boyunca uzanır.'),
  w(T('Ulaşım'), 'intermodal',    'çok modlu',       'sıfat', 'Intermodal transport links rail, road and sea.', 'Çok modlu taşımacılık demiryolu, karayolu ve denizi birbirine bağlar.'),
  w(T('Ulaşım'), 'turbocharge',   'turbolu hale getirmek','fiil','Engineers turbocharged the engine for better performance.','Mühendisler daha iyi performans için motoru turbolu hale getirdi.'),
  w(T('Ulaşım'), 'hovercraft',    'hoverkraft',      'isim',  'The hovercraft crossed the channel in two hours.','Hoverkraft kanalı iki saatte geçti.'),
  w(T('Ulaşım'), 'deregulate',    'kuralsızlaştırmak','fiil', 'The government deregulated the airline industry.','Hükümet havayolu endüstrisini kuralsızlaştırdı.'),
  w(T('Ulaşım'), 'freight',       'yük taşımacılığı','isim',  'Freight trains carry goods across the country.',  'Yük trenleri ülke genelinde mal taşır.'),
  w(T('Ulaşım'), 'pilotage',      'kılavuzluk',      'isim',  'Pilotage services guide ships into port.',       'Kılavuzluk hizmetleri gemilere limana giriş yardımı sağlar.'),
  w(T('Ulaşım'), 'sanction',      'yaptırım',        'isim',  'A transport sanction was placed on the country.','Ülkeye ulaşım yaptırımı uygulandı.'),
  w(T('Ulaşım'), 'ballast',       'balast',          'isim',  'Ballast keeps ships stable in rough seas.',      'Balast, gemileri dalgalı denizlerde dengede tutar.'),
  w(T('Ulaşım'), 'aerofoil',      'hava kanadı',     'isim',  'The aerofoil shape generates lift for the plane.','Hava kanadı şekli uçak için kaldırma kuvveti oluşturur.'),
  w(T('Ulaşım'), 'hydro-plane',   'hidroplan',       'isim',  'The hydroplane glided across the water surface.','Hidroplan su yüzeyinde süzüldü.'),
  w(T('Ulaşım'), 'subsonic',      'ses altı',        'sıfat', 'Most commercial flights are subsonic.',          'Çoğu ticari uçuş ses altı hızdadır.'),
  w(T('Ulaşım'), 'supersonic',    'ses üstü',        'sıfat', 'Concorde was a supersonic passenger aircraft.',  'Concorde ses üstü hızda bir yolcu uçağıydı.'),
  w(T('Ulaşım'), 'throttle',      'gaz kolu',        'isim',  'He eased the throttle as they approached the runway.','Pisiste yaklaşırken gaz kolunu azalttı.'),
  w(T('Ulaşım'), 'catamaran',     'katamaran',       'isim',  'The catamaran sailed smoothly in choppy waters.', 'Katamaran çalkantılı sularda düzgün seyretti.'),

  // ── Şehir ve Mekanlar (B2) ────────────────────────────────────────────
  w(T('Şehir ve Mekanlar'), 'conurbation',  'kentsel yığılma',  'isim',  'The conurbation extended far beyond the city limits.','Kentsel yığılma şehir sınırlarının çok ötesine uzanıyordu.'),
  w(T('Şehir ve Mekanlar'), 'megalopolis',  'megalopol',        'isim',  'Tokyo is a classic example of a megalopolis.',      'Tokyo, bir megalopolün klasik bir örneğidir.'),
  w(T('Şehir ve Mekanlar'), 'enclave',      'yerleşim alanı',   'isim',  'The diplomatic enclave was heavily guarded.',       'Diplomatik yerleşim alanı ağır şekilde korunuyordu.'),
  w(T('Şehir ve Mekanlar'), 'sprawl',       'yayılma',          'isim',  'Urban sprawl has consumed surrounding farmland.',   'Kentsel yayılma, çevredeki tarım arazilerini tüketti.'),
  w(T('Şehir ve Mekanlar'), 'agglomeration','aglomerasyon',     'isim',  'Economic agglomeration occurs in large cities.',    'Ekonomik aglomerasyon büyük şehirlerde gerçekleşir.'),
  w(T('Şehir ve Mekanlar'), 'tenement',     'kiralık apartman', 'isim',  'The tenement buildings were in poor condition.',    'Kiralık apartman binaları kötü durumdaydı.'),
  w(T('Şehir ve Mekanlar'), 'promenade',    'gezinti yeri',     'isim',  'The seafront promenade was full of tourists.',      'Deniz kenarındaki gezinti yeri turistlerle doluydu.'),
  w(T('Şehir ve Mekanlar'), 'colosseum',    'amfitiyatro',      'isim',  'The ancient colosseum attracted millions of visitors.','Antik amfitiyatro milyonlarca ziyaretçi çekti.'),
  w(T('Şehir ve Mekanlar'), 'slum',         'gecekondu',        'isim',  'The slum was demolished to make way for new housing.','Yeni konutlar için gecekondu yıkıldı.'),
  w(T('Şehir ve Mekanlar'), 'citadel',      'iç kale',          'isim',  'The citadel overlooked the entire city.',           'İç kale, şehrin tamamına hakim konumdaydı.'),
  w(T('Şehir ve Mekanlar'), 'esplanade',    'rıhtım yolu',      'isim',  'We strolled along the esplanade at sunset.',        'Gün batımında rıhtım yolunda yürüdük.'),
  w(T('Şehir ve Mekanlar'), 'almshouse',    'yoksullar evi',    'isim',  'The almshouse was built in the 19th century.',     'Yoksullar evi 19. yüzyılda inşa edildi.'),
  w(T('Şehir ve Mekanlar'), 'colonnade',    'sütunlu revak',    'isim',  'The colonnade lined the main square.',              'Sütunlu revak ana meydanı çevreliyordu.'),
  w(T('Şehir ve Mekanlar'), 'hinterland',   'arka bölge',       'isim',  'The city\'s hinterland provides fresh produce.',    'Şehrin arka bölgesi taze ürün sağlar.'),
  w(T('Şehir ve Mekanlar'), 'polis',        'şehir devleti',    'isim',  'Athens was an influential ancient polis.',          'Atina etkili bir antik şehir devletiydi.'),
  w(T('Şehir ve Mekanlar'), 'thoroughfare', 'ana cadde',        'isim',  'The thoroughfare was closed for the parade.',       'Ana cadde geçit töreni için kapatıldı.'),
  w(T('Şehir ve Mekanlar'), 'quay',         'rıhtım',           'isim',  'The ship docked at the quay at dawn.',              'Gemi şafakta rıhtıma yanaştı.'),
  w(T('Şehir ve Mekanlar'), 'piazza',       'açık meydan',      'isim',  'The piazza was filled with market stalls.',         'Açık meydan pazar tezgahlarıyla doluydu.'),
  w(T('Şehir ve Mekanlar'), 'ghetto',       'izole mahalle',    'isim',  'The ghetto was a result of economic segregation.',  'İzole mahalle ekonomik ayrımcılığın bir sonucuydu.'),
  w(T('Şehir ve Mekanlar'), 'metropolis',   'büyük şehir',      'isim',  'New York is one of the world\'s greatest metropolises.','New York dünyanın en büyük şehirlerinden biridir.'),

  // ── Alışveriş (B2) ────────────────────────────────────────────────────
  w(T('Alışveriş'), 'arbitrage',      'arbitraj',           'isim',  'Arbitrage exploits price differences across markets.', 'Arbitraj, piyasalar arasındaki fiyat farklılıklarından yararlanır.'),
  w(T('Alışveriş'), 'liquidate',      'tasfiye etmek',      'fiil',  'The company was forced to liquidate its assets.',      'Şirket varlıklarını tasfiye etmek zorunda kaldı.'),
  w(T('Alışveriş'), 'procurement',    'tedarik',            'isim',  'The procurement process was reviewed for efficiency.',  'Tedarik süreci verimlilik açısından gözden geçirildi.'),
  w(T('Alışveriş'), 'solvent',        'borç ödeme gücüne sahip','sıfat','The company remained solvent despite losses.',       'Şirket zararlara rağmen borç ödeme gücünü korudu.'),
  w(T('Alışveriş'), 'markdown',       'indirim',            'isim',  'The markdown reduced the price by 40%.',               'İndirim fiyatı yüzde 40 düşürdü.'),
  w(T('Alışveriş'), 'consignment',    'konsinye',           'isim',  'The goods were sent on consignment.',                  'Mallar konsinye olarak gönderildi.'),
  w(T('Alışveriş'), 'aggregate',      'toplam',             'sıfat', 'The aggregate demand rose sharply.',                   'Toplam talep keskin biçimde arttı.'),
  w(T('Alışveriş'), 'deficit',        'açık',               'isim',  'The trade deficit widened this quarter.',              'Ticaret açığı bu çeyrekte genişledi.'),
  w(T('Alışveriş'), 'monopoly',       'tekel',              'isim',  'The company held a monopoly on the market.',           'Şirket piyasada tekel konumundaydı.'),
  w(T('Alışveriş'), 'oligopoly',      'oligopol',           'isim',  'The telecom sector is an oligopoly.',                  'Telecom sektörü bir oligopoldür.'),
  w(T('Alışveriş'), 'depreciation',   'değer kaybı',        'isim',  'The car lost value through annual depreciation.',      'Araba yıllık değer kaybı yoluyla değerini yitirdi.'),
  w(T('Alışveriş'), 'remittance',     'havale',             'isim',  'He sent a remittance to his family abroad.',           'Yurt dışındaki ailesine havale gönderdi.'),
  w(T('Alışveriş'), 'leverage',       'kaldıraç',           'isim',  'The investor used leverage to increase returns.',      'Yatırımcı getirileri artırmak için kaldıraç kullandı.'),
  w(T('Alışveriş'), 'dividend',       'temettü',            'isim',  'Shareholders received a generous dividend.',          'Hissedarlar cömert bir temettü aldı.'),
  w(T('Alışveriş'), 'solvency',       'ödeme gücü',         'isim',  'The auditor assessed the company\'s solvency.',       'Denetçi şirketin ödeme gücünü değerlendirdi.'),
  w(T('Alışveriş'), 'hedging',        'riskten korunma',    'isim',  'Hedging protects against financial risk.',             'Riskten korunma finansal riske karşı koruma sağlar.'),
  w(T('Alışveriş'), 'embargo',        'ticaret yasağı',     'isim',  'The embargo restricted all imports of oil.',          'Ticaret yasağı tüm petrol ithalatını kısıtladı.'),
  w(T('Alışveriş'), 'speculate',      'spekülasyon yapmak', 'fiil',  'Investors speculated on rising property prices.',      'Yatırımcılar artan konut fiyatları üzerine spekülasyon yaptı.'),
  w(T('Alışveriş'), 'equilibrium',    'denge',              'isim',  'The market reached equilibrium at a fair price.',     'Piyasa adil bir fiyatta dengeye ulaştı.'),
  w(T('Alışveriş'), 'cartel',         'kartel',             'isim',  'A cartel was formed to control oil prices.',          'Petrol fiyatlarını kontrol etmek için bir kartel kuruldu.'),

  // ── Meslekler (B2) ────────────────────────────────────────────────────
  w(T('Meslekler'), 'ombudsman',      'ombudsman',          'isim',  'The ombudsman investigated the complaint.',           'Ombudsman şikayeti inceledi.'),
  w(T('Meslekler'), 'podiatrist',     'ayak doktoru',       'isim',  'The podiatrist treated her ingrown toenail.',         'Ayak doktoru içe dönük tırnak problemini tedavi etti.'),
  w(T('Meslekler'), 'orthodontist',   'ortodontist',        'isim',  'The orthodontist fitted her braces.',                 'Ortodontist diş telini taktı.'),
  w(T('Meslekler'), 'chiropractor',   'kiropraktisyen',     'isim',  'The chiropractor adjusted his spine.',                'Kiropraktisyen omurgasını düzeltti.'),
  w(T('Meslekler'), 'epidemiologist', 'epidemiyolog',       'isim',  'The epidemiologist tracked the disease outbreak.',    'Epidemiyolog hastalık salgınını takip etti.'),
  w(T('Meslekler'), 'geologist',      'jeolog',             'isim',  'The geologist studied rock formations.',              'Jeolog kaya oluşumlarını inceledi.'),
  w(T('Meslekler'), 'cartographer',   'haritacı',           'isim',  'The cartographer drew detailed maps of the region.',  'Haritacı bölgenin ayrıntılı haritalarını çizdi.'),
  w(T('Meslekler'), 'lexicographer',  'sözlükbilimci',      'isim',  'The lexicographer compiled the new dictionary.',      'Sözlükbilimci yeni sözlüğü derledi.'),
  w(T('Meslekler'), 'anthropologist', 'antropolog',         'isim',  'The anthropologist studied ancient human cultures.',   'Antropolog eski insan kültürlerini inceledi.'),
  w(T('Meslekler'), 'numismatist',    'numizmatik uzmanı',  'isim',  'The numismatist appraised the rare coins.',           'Numizmatik uzmanı nadir madeni paraları değerlendirdi.'),
  w(T('Meslekler'), 'toxicologist',   'toksikolog',         'isim',  'The toxicologist identified the poison.',             'Toksikolog zehri tanımladı.'),
  w(T('Meslekler'), 'archivist',      'arşivci',            'isim',  'The archivist preserved centuries-old documents.',    'Arşivci yüzyıllık belgeleri korudu.'),
  w(T('Meslekler'), 'sommelier',      'şarap uzmanı',       'isim',  'The sommelier recommended the perfect wine.',         'Şarap uzmanı mükemmel şarabı önerdi.'),
  w(T('Meslekler'), 'cryptographer',  'kriptograf',         'isim',  'The cryptographer designed secure communication systems.','Kriptograf güvenli iletişim sistemleri tasarladı.'),
  w(T('Meslekler'), 'coroner',        'adli tabip',         'isim',  'The coroner determined the cause of death.',          'Adli tabip ölüm nedenini belirledi.'),
  w(T('Meslekler'), 'notary',         'noter',              'isim',  'The notary certified the legal documents.',           'Noter yasal belgeleri onayladı.'),
  w(T('Meslekler'), 'demographer',    'demograf',           'isim',  'The demographer analyzed population trends.',         'Demograf nüfus eğilimlerini analiz etti.'),
  w(T('Meslekler'), 'neurosurgeon',   'beyin cerrahı',      'isim',  'The neurosurgeon performed a delicate brain operation.','Beyin cerrahı hassas bir beyin ameliyatı gerçekleştirdi.'),
  w(T('Meslekler'), 'theologian',     'ilahiyatçı',         'isim',  'The theologian wrote extensively on religious ethics.','İlahiyatçı dini etik üzerine kapsamlı eserler yazdı.'),
  w(T('Meslekler'), 'stenographer',   'steno yazan',        'isim',  'The stenographer recorded every word of the trial.',  'Steno yazan duruşmadaki her kelimeyi kaydetti.'),

  // ── Okul ve Eğitim (B2) ───────────────────────────────────────────────
  w(T('Okul ve Eğitim'), 'epistemology',  'epistemoloji',    'isim',  'Epistemology is the study of knowledge.',            'Epistemoloji, bilginin incelemesidir.'),
  w(T('Okul ve Eğitim'), 'heuristic',     'sezgisel yöntem', 'isim',  'Heuristic learning encourages discovery.',           'Sezgisel öğrenme keşfi teşvik eder.'),
  w(T('Okul ve Eğitim'), 'didactic',      'öğretici',        'sıfat', 'The didactic approach focused on direct instruction.','Öğretici yaklaşım doğrudan öğretimi ön plana çıkardı.'),
  w(T('Okul ve Eğitim'), 'accreditation','akreditasyon',     'isim',  'The university received international accreditation.','Üniversite uluslararası akreditasyon aldı.'),
  w(T('Okul ve Eğitim'), 'andragogy',     'yetişkin eğitimi','isim',  'Andragogy focuses on adult learning principles.',    'Yetişkin eğitimi, yetişkin öğrenme ilkelerine odaklanır.'),
  w(T('Okul ve Eğitim'), 'metacognition', 'üst biliş',       'isim',  'Metacognition helps students understand their own learning.','Üst biliş öğrencilerin kendi öğrenmelerini anlamalarına yardımcı olur.'),
  w(T('Okul ve Eğitim'), 'constructivism','yapılandırmacılık','isim', 'Constructivism argues knowledge is actively constructed.','Yapılandırmacılık bilginin aktif olarak inşa edildiğini öne sürer.'),
  w(T('Okul ve Eğitim'), 'seminar',       'seminer',         'isim',  'The professor held a weekly seminar.',               'Profesör haftalık seminer düzenledi.'),
  w(T('Okul ve Eğitim'), 'monograph',     'monografi',       'isim',  'Her monograph explored postcolonial literature.',     'Monografisi postkolonyal edebiyatı inceledi.'),
  w(T('Okul ve Eğitim'), 'sabbatical',    'sabbatik izin',   'isim',  'The professor took a sabbatical to write a book.',   'Profesör kitap yazmak için sabbatik izne çıktı.'),
  w(T('Okul ve Eğitim'), 'typology',      'tipoloji',        'isim',  'Bloom\'s typology categorises learning objectives.',  'Bloom\'un tipolojisi öğrenme hedeflerini kategorize eder.'),
  w(T('Okul ve Eğitim'), 'remedial',      'telafi edici',    'sıfat', 'She attended remedial classes to improve her maths.','Matematikini geliştirmek için telafi edici derslere katıldı.'),
  w(T('Okul ve Eğitim'), 'tenured',       'kadrolu',         'sıfat', 'Getting tenured at a university is competitive.',    'Üniversitede kadrolu olmak rekabetçidir.'),
  w(T('Okul ve Eğitim'), 'vocational',    'mesleki',         'sıfat', 'Vocational training prepares students for work.',    'Mesleki eğitim öğrencileri çalışma hayatına hazırlar.'),
  w(T('Okul ve Eğitim'), 'comprehensive', 'kapsamlı',        'sıfat', 'The comprehensive exam covered all subjects.',       'Kapsamlı sınav tüm konuları kapsıyordu.'),
  w(T('Okul ve Eğitim'), 'pupil',         'öğrenci',         'isim',  'The gifted pupil won multiple awards.',              'Yetenekli öğrenci birden fazla ödül kazandı.'),
  w(T('Okul ve Eğitim'), 'rote',          'ezber',           'isim',  'Rote learning has its place in early education.',    'Ezber öğrenmenin erken eğitimde bir yeri vardır.'),
  w(T('Okul ve Eğitim'), 'pedagogue',     'pedagog',         'isim',  'The pedagogue inspired her students every day.',     'Pedagog her gün öğrencilere ilham verdi.'),
  w(T('Okul ve Eğitim'), 'autodidact',    'kendi kendine öğrenen','isim','An autodidact learns without formal instruction.',  'Kendi kendine öğrenen, resmi eğitim almadan öğrenir.'),
  w(T('Okul ve Eğitim'), 'syllogism',     'mantık yürütme',  'isim',  'A syllogism is a form of logical reasoning.',        'Mantık yürütme, mantıksal akıl yürütmenin bir biçimidir.'),

  // ── Sağlık (B2) ───────────────────────────────────────────────────────
  w(T('Sağlık'), 'comorbidity',    'eş hastalık',     'isim',  'Comorbidity complicates treatment planning.',         'Eş hastalık, tedavi planlamayı karmaşıklaştırır.'),
  w(T('Sağlık'), 'iatrogenic',     'iyatrojenik',     'sıfat', 'An iatrogenic illness is caused by medical treatment.','İyatrojenik hastalık tıbbi tedavinin neden olduğu bir hastalıktır.'),
  w(T('Sağlık'), 'pharmacokinetics','farmakokinetik', 'isim',  'Pharmacokinetics studies how drugs move through the body.','Farmakokinetik, ilaçların vücutta nasıl hareket ettiğini inceler.'),
  w(T('Sağlık'), 'aetiology',      'etiyoloji',       'isim',  'The aetiology of the disease was unknown.',           'Hastalığın etiyolojisi bilinmiyordu.'),
  w(T('Sağlık'), 'immunotherapy',  'immünoterapi',    'isim',  'Immunotherapy uses the immune system to fight cancer.','İmmünoterapi, kansere karşı savaşmak için bağışıklık sistemini kullanır.'),
  w(T('Sağlık'), 'latent',         'gizli',           'sıfat', 'The latent virus reactivated years later.',           'Gizli virüs yıllar sonra yeniden aktive oldu.'),
  w(T('Sağlık'), 'remission',      'gerileme',        'isim',  'The cancer entered remission after chemotherapy.',    'Kanser kemoterapi sonrası gerilemeye girdi.'),
  w(T('Sağlık'), 'contraindication','kontrendikasyon','isim',  'Pregnancy is a contraindication for this drug.',      'Hamilelik bu ilaç için bir kontrendikasyondur.'),
  w(T('Sağlık'), 'thrombosis',     'tromboz',         'isim',  'Thrombosis occurs when blood clots form in vessels.',  'Tromboz, damarlarda kan pıhtıları oluştuğunda meydana gelir.'),
  w(T('Sağlık'), 'pathogenesis',   'patogenez',       'isim',  'Understanding pathogenesis helps in drug design.',     'Patogenezi anlamak ilaç tasarımına yardımcı olur.'),
  w(T('Sağlık'), 'analgesic',      'ağrı kesici',     'isim',  'The doctor prescribed an analgesic for the pain.',    'Doktor ağrı için bir ağrı kesici reçete etti.'),
  w(T('Sağlık'), 'benign',         'iyi huylu',       'sıfat', 'The tumour was benign and not cancerous.',            'Tümör iyi huylu ve kanserli değildi.'),
  w(T('Sağlık'), 'malignant',      'kötü huylu',      'sıfat', 'The malignant cells spread rapidly.',                 'Kötü huylu hücreler hızla yayıldı.'),
  w(T('Sağlık'), 'palliative',     'palyatif',        'sıfat', 'Palliative care focuses on comfort, not cure.',       'Palyatif bakım tedavi değil, rahatlığa odaklanır.'),
  w(T('Sağlık'), 'anaphylaxis',    'anafilaksi',      'isim',  'She carried an epi-pen in case of anaphylaxis.',      'Anafilaksi durumuna karşı epipen taşıyordu.'),
  w(T('Sağlık'), 'cachexia',       'kaşeksi',         'isim',  'Cancer-related cachexia causes severe muscle loss.',   'Kanserle ilişkili kaşeksi ciddi kas kaybına yol açar.'),
  w(T('Sağlık'), 'necrosis',       'nekroz',          'isim',  'Necrosis is the death of body tissue.',               'Nekroz, vücut dokusunun ölümüdür.'),
  w(T('Sağlık'), 'suture',         'sütür',           'isim',  'The wound required six sutures.',                     'Yaranın altı süture ihtiyacı vardı.'),
  w(T('Sağlık'), 'haemoglobin',    'hemoglobin',      'isim',  'Haemoglobin carries oxygen in red blood cells.',      'Hemoglobin, kırmızı kan hücrelerinde oksijen taşır.'),
  w(T('Sağlık'), 'neuropathy',     'nöropati',        'isim',  'Diabetic neuropathy affects the nerves in the feet.', 'Diyabetik nöropati, ayaklardaki sinirleri etkiler.'),

  // ── Spor (B2) ─────────────────────────────────────────────────────────
  w(T('Spor'), 'biomechanics',    'biyomekanik',     'isim',  'Biomechanics improves athletic performance.',         'Biyomekanik atletik performansı iyileştirir.'),
  w(T('Spor'), 'decathlon',       'dekatlon',        'isim',  'The decathlon tests athletes in ten events.',         'Dekatlon, sporcuları on branşta test eder.'),
  w(T('Spor'), 'relegation',      'düşme',           'isim',  'The team faced relegation to the lower division.',   'Takım alt ligye düşme tehlikesiyle karşı karşıya kaldı.'),
  w(T('Spor'), 'concussion',      'sarsıntı',        'isim',  'The player was sidelined with a concussion.',        'Oyuncu sarsıntı nedeniyle devre dışı kaldı.'),
  w(T('Spor'), 'aerobic',         'aerobik',         'sıfat', 'Aerobic exercise strengthens the cardiovascular system.','Aerobik egzersiz kardiyovasküler sistemi güçlendirir.'),
  w(T('Spor'), 'anaerobic',       'anaerobik',       'sıfat', 'Sprinting is an anaerobic form of exercise.',        'Kısa mesafe koşusu anaerobik bir egzersiz biçimidir.'),
  w(T('Spor'), 'periodization',   'periodizasyon',   'isim',  'Periodization divides training into phases.',        'Periodizasyon antrenmanı aşamalara böler.'),
  w(T('Spor'), 'proprioceptive',  'propriyoseptif',  'sıfat', 'Proprioceptive training improves balance.',          'Propriyoseptif antrenman dengeyi geliştirir.'),
  w(T('Spor'), 'plyometric',      'pliometrik',      'sıfat', 'Plyometric exercises develop explosive power.',      'Pliometrik egzersizler patlayıcı güç geliştirir.'),
  w(T('Spor'), 'glycogen',        'glikojen',        'isim',  'Athletes deplete glycogen stores during long races.', 'Sporcular uzun yarışlarda glikojen depolarını tüketir.'),
  w(T('Spor'), 'lactic acid',     'laktik asit',     'isim',  'Lactic acid buildup causes muscle fatigue.',         'Laktik asit birikimi kas yorgunluğuna neden olur.'),
  w(T('Spor'), 'ergogenic',       'ergojenik',       'sıfat', 'Caffeine is an ergogenic aid for athletes.',         'Kafein sporcular için bir ergojenik yardımdır.'),
  w(T('Spor'), 'kinesthesia',     'kinestetik duygu','isim',  'Kinesthesia helps gymnasts control their movements.',  'Kinestetik duygu, jimnastikçilerin hareketlerini kontrol etmesine yardımcı olur.'),
  w(T('Spor'), 'overtraining',    'aşırı antrenman', 'isim',  'Overtraining can lead to injury and burnout.',       'Aşırı antrenman yaralanma ve tükenmişliğe yol açabilir.'),
  w(T('Spor'), 'concede',         'gol yemek',       'fiil',  'The team conceded three goals in the first half.',   'Takım ilk yarıda üç gol yedi.'),
  w(T('Spor'), 'stoppage time',   'uzatma dakikaları','isim', 'They scored in stoppage time to equalize.',          'Uzatma dakikalarında skoru eşitlediler.'),
  w(T('Spor'), 'foul',            'faul',            'isim',  'The player committed a foul near the penalty area.','Oyuncu ceza sahası yakınında faul yaptı.'),
  w(T('Spor'), 'fortitude',       'metanet',         'isim',  'She showed great fortitude in recovering from injury.','Yaralanmadan iyileşmede büyük bir metanet gösterdi.'),
  w(T('Spor'), 'stratagem',       'strateji',        'isim',  'The coach used a clever stratagem in the final.',    'Koç finalde akıllıca bir strateji kullandı.'),
  w(T('Spor'), 'quintathlon',     'beşli atletizm',  'isim',  'The quintathlon combines five athletic disciplines.','Beşli atletizm beş atletik dalı birleştirir.'),

  // ── Duygular (B2) ─────────────────────────────────────────────────────
  w(T('Duygular'), 'equanimity',    'ruh huzuru',       'isim',  'She faced difficulties with equanimity.',            'Zorlukları ruh huzuruyla karşıladı.'),
  w(T('Duygular'), 'schadenfreude', 'başkasının acısına gülme','isim','Schadenfreude is taking pleasure in others\' misfortune.','Başkasının acısına gülme, başkalarının talihsizliğinden zevk almaktır.'),
  w(T('Duygular'), 'catharsis',     'arınma',           'isim',  'The film provided emotional catharsis.',             'Film duygusal bir arınma sağladı.'),
  w(T('Duygular'), 'trepidation',   'korku',            'isim',  'She waited with a sense of trepidation.',           'Bir korku duygusuyla bekledi.'),
  w(T('Duygular'), 'magnanimous',   'cömert kalpli',    'sıfat', 'He was magnanimous in defeat.',                     'Yenilgide cömert kalpli davrandı.'),
  w(T('Duygular'), 'despondent',    'umutsuz',          'sıfat', 'She felt despondent after the rejection.',          'Reddetmeden sonra umutsuz hissetti.'),
  w(T('Duygular'), 'euphoria',      'coşku',            'isim',  'The team was overcome with euphoria after winning.', 'Takım kazandıktan sonra coşkuya kapıldı.'),
  w(T('Duygular'), 'anguish',       'acı',              'isim',  'The loss caused him great anguish.',                'Kayıp ona büyük acı yaşattı.'),
  w(T('Duygular'), 'stoic',         'metanetli',        'sıfat', 'She remained stoic throughout the ordeal.',         'Çile boyunca metanetini korudu.'),
  w(T('Duygular'), 'melancholy',    'hüzün',            'isim',  'Autumn often brings a sense of melancholy.',        'Sonbahar çoğu zaman bir hüzün duygusu getirir.'),
  w(T('Duygular'), 'hubris',        'kibir',            'isim',  'His hubris eventually led to his downfall.',        'Kibri sonunda çöküşüne yol açtı.'),
  w(T('Duygular'), 'equivocal',     'muğlak',           'sıfat', 'His answer was equivocal and confusing.',           'Yanıtı muğlak ve kafa karıştırıcıydı.'),
  w(T('Duygular'), 'petulant',      'huysuz',           'sıfat', 'The child became petulant when overtired.',         'Çok yorulunca çocuk huysuz oldu.'),
  w(T('Duygular'), 'sanguine',      'iyimser',          'sıfat', 'He remained sanguine about the outcome.',           'Sonuç konusunda iyimser kalmaya devam etti.'),
  w(T('Duygular'), 'disconsolate',  'teselli edilemez', 'sıfat', 'She was disconsolate after the loss.',              'Kayıptan sonra teselli edilemez durumdaydı.'),
  w(T('Duygular'), 'ambiguity',     'belirsizlik',      'isim',  'The ambiguity of the situation stressed her.',      'Durumun belirsizliği onu strese soktu.'),
  w(T('Duygular'), 'indignation',   'öfke',             'isim',  'She felt righteous indignation at the injustice.',  'Adaletsizlik karşısında haklı bir öfke hissetti.'),
  w(T('Duygular'), 'awe',           'hayranlık',        'isim',  'The view from the summit filled her with awe.',     'Zirvedeki manzara onu hayranlıkla doldurdu.'),
  w(T('Duygular'), 'mortified',     'utanmış',          'sıfat', 'He was mortified by his public mistake.',           'Toplum önündeki hatasından utanmıştı.'),
  w(T('Duygular'), 'rancour',       'kin',              'isim',  'Years of rancour divided the two families.',        'Yıllarca süren kin iki aileyi böldü.'),

  // ── Teknoloji (B2) ────────────────────────────────────────────────────
  w(T('Teknoloji'), 'neural network',  'sinir ağı',      'isim',  'Neural networks mimic the human brain.',             'Sinir ağları insan beynini taklit eder.'),
  w(T('Teknoloji'), 'cryptography',    'kriptografi',    'isim',  'Cryptography secures digital communications.',       'Kriptografi dijital iletişimi güvence altına alır.'),
  w(T('Teknoloji'), 'quantum',         'kuantum',        'isim',  'Quantum computing could revolutionize technology.',  'Kuantum bilişim teknolojiyi devrim yaratabilir.'),
  w(T('Teknoloji'), 'semiconductor',   'yarı iletken',   'isim',  'Semiconductors are the foundation of electronics.',  'Yarı iletkenler elektroniğin temelidir.'),
  w(T('Teknoloji'), 'tokenization',    'tokenizasyon',   'isim',  'Tokenization converts data into secure tokens.',     'Tokenizasyon veriyi güvenli jetonlara dönüştürür.'),
  w(T('Teknoloji'), 'edge computing',  'uç bilişim',     'isim',  'Edge computing processes data closer to the source.','Uç bilişim veriyi kaynağa daha yakın işler.'),
  w(T('Teknoloji'), 'neural',          'sinirsel',       'sıfat', 'Neural interfaces connect brains to computers.',     'Sinirsel arayüzler beyinleri bilgisayarlara bağlar.'),
  w(T('Teknoloji'), 'biometric',       'biyometrik',     'sıfat', 'Biometric data includes fingerprints and iris scans.','Biyometrik veriler parmak izleri ve iris taramalarını içerir.'),
  w(T('Teknoloji'), 'nanotechnology',  'nanoteknoloji',  'isim',  'Nanotechnology operates at the molecular scale.',    'Nanoteknoloji moleküler ölçekte çalışır.'),
  w(T('Teknoloji'), 'photovoltaic',    'fotovoltaik',    'sıfat', 'Photovoltaic cells convert sunlight into electricity.','Fotovoltaik hücreler güneş ışığını elektriğe dönüştürür.'),
  w(T('Teknoloji'), 'telemetry',       'telemetri',      'isim',  'Telemetry collects data from remote sensors.',       'Telemetri uzak sensörlerden veri toplar.'),
  w(T('Teknoloji'), 'obsolescence',    'eskime',         'isim',  'Planned obsolescence makes products expire sooner.',  'Planlı eskime ürünlerin daha erken sona ermesine neden olur.'),
  w(T('Teknoloji'), 'haptic',          'dokunsal',       'sıfat', 'Haptic feedback provides a realistic touch sensation.','Dokunsal geri bildirim gerçekçi bir dokunma hissi sağlar.'),
  w(T('Teknoloji'), 'overclocking',    'aşırı hızlandırma','isim','Overclocking speeds up processor performance.',       'Aşırı hızlandırma işlemci performansını artırır.'),
  w(T('Teknoloji'), 'microprocessor',  'mikroişlemci',   'isim',  'The microprocessor is the brain of the computer.',   'Mikroişlemci bilgisayarın beynidir.'),
  w(T('Teknoloji'), 'superconductor',  'süper iletken',  'isim',  'Superconductors have zero electrical resistance.',   'Süper iletkenler sıfır elektrik direncine sahiptir.'),
  w(T('Teknoloji'), 'hypertext',       'hiper metin',    'isim',  'HTML is a hypertext markup language.',                'HTML bir hiper metin işaret dilidir.'),
  w(T('Teknoloji'), 'transistor',      'transistör',     'isim',  'The transistor revolutionized electronics.',          'Transistör elektroniği devrim yaptı.'),
  w(T('Teknoloji'), 'metamaterial',    'metamalzeme',    'isim',  'Metamaterials can bend electromagnetic waves.',       'Metamalzemeler elektromanyetik dalgaları bükülebilir.'),
  w(T('Teknoloji'), 'neuromorphic',    'nöromorfik',     'sıfat', 'Neuromorphic chips replicate brain functions.',       'Nöromorfik çipler beyin fonksiyonlarını kopyalar.'),
];

// ── Duplicate check ───────────────────────────────────────────────────────────
const b2Ens = b2.map(w => w.en);
const internalDups = b2Ens.filter((en, i) => b2Ens.indexOf(en) !== i);
if (internalDups.length > 0) {
  console.error('INTERNAL DUPLICATES in B2:', [...new Set(internalDups)]);
  process.exit(1);
}

const crossDups = b2Ens.filter(en => existingEns.has(en));
if (crossDups.length > 0) {
  console.error('CROSS DUPLICATES (already in words.json):', crossDups);
  process.exit(1);
}

const merged = [...existing, ...b2];
fs.writeFileSync(WORDS_PATH, JSON.stringify(merged, null, 2));
console.log(`✅ Done! Added ${b2.length} B2 words. Total: ${merged.length}`);
